services:
  app:
    image: docker.io/mvsrinath/sprintboard:${VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    restart: unless-stopped
    ports:
      - 1341:1341
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    container_name: bureaucat-garage
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
    env_file:
      - .postgres.env
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 10s
      timeout: 5s
      retries: 5
