-- PostgreSQL cannot drop a single enum value without recreating the type and
-- rewriting every dependent column, so this down migration is intentionally a
-- no-op. The unused 'ongoing' value is harmless if left in place.
