// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAttachmentsByUpload = `-- name: CountAttachmentsByUpload :one
SELECT count(*) FROM attachments WHERE upload_id = $1
`

func (q *Queries) CountAttachmentsByUpload(ctx context.Context, uploadID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByUpload, uploadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (upload_id, entity_type, entity_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, upload_id, entity_type, entity_id, created_by, created_at
`

type CreateAttachmentParams struct {
	UploadID   uuid.UUID `json:"upload_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	CreatedBy  uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.UploadID,
		arg.EntityType,
		arg.EntityID,
		arg.CreatedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments WHERE id = $1 RETURNING upload_id
`

// Returns the upload_id so the caller can clean up the underlying file once no
// attachment references it anymore.
func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var upload_id uuid.UUID
	err := row.Scan(&upload_id)
	return upload_id, err
}

const deleteAttachmentsByEntity = `-- name: DeleteAttachmentsByEntity :exec
DELETE FROM attachments WHERE entity_type = $1 AND entity_id = $2
`

type DeleteAttachmentsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteAttachmentsByEntity(ctx context.Context, arg DeleteAttachmentsByEntityParams) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByEntity, arg.EntityType, arg.EntityID)
	return err
}

const listAttachmentsByEntity = `-- name: ListAttachmentsByEntity :many
SELECT a.id, a.upload_id, a.entity_type, a.entity_id, a.created_by, a.created_at,
       u.filename, u.mime_type, u.size_bytes
FROM attachments a
JOIN uploads u ON u.id = a.upload_id
WHERE a.entity_type = $1 AND a.entity_id = $2
ORDER BY a.created_at
`

type ListAttachmentsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

type ListAttachmentsByEntityRow struct {
	ID         uuid.UUID          `json:"id"`
	UploadID   uuid.UUID          `json:"upload_id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Filename   string             `json:"filename"`
	MimeType   string             `json:"mime_type"`
	SizeBytes  int64              `json:"size_bytes"`
}

func (q *Queries) ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]ListAttachmentsByEntityRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsByEntityRow{}
	for rows.Next() {
		var i ListAttachmentsByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
