// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRefreshTokens = `-- name: CountActiveRefreshTokens :one
SELECT COUNT(*)
FROM refresh_tokens
WHERE revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountActiveRefreshTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRefreshTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM users
WHERE username ILIKE '%' || $1 || '%'
   OR email ILIKE '%' || $1 || '%'
   OR first_name ILIKE '%' || $1 || '%'
   OR last_name ILIKE '%' || $1 || '%'
   OR (first_name || ' ' || last_name) ILIKE '%' || $1 || '%'
`

func (q *Queries) CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createSSOUser = `-- name: CreateSSOUser :one
INSERT INTO users (username, email, first_name, last_name, user_type, auth_provider, provider_user_id, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, first_name, last_name, user_type, auth_provider, provider_user_id, avatar_url, created_at, updated_at
`

type CreateSSOUserParams struct {
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	UserType       string      `json:"user_type"`
	AuthProvider   pgtype.Text `json:"auth_provider"`
	ProviderUserID pgtype.Text `json:"provider_user_id"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

type CreateSSOUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	UserType       string             `json:"user_type"`
	AuthProvider   pgtype.Text        `json:"auth_provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (CreateSSOUserRow, error) {
	row := q.db.QueryRow(ctx, createSSOUser,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserType,
		arg.AuthProvider,
		arg.ProviderUserID,
		arg.AvatarUrl,
	)
	var i CreateSSOUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, first_name, last_name, user_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, first_name, last_name, user_type, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	UserType     string      `json:"user_type"`
}

type CreateUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	UserType  string             `json:"user_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.UserType,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, first_name, last_name, user_type,
       auth_provider, provider_user_id, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	UserType       string             `json:"user_type"`
	AuthProvider   pgtype.Text        `json:"auth_provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, username, email, password_hash, first_name, last_name, user_type,
       avatar_url, auth_provider, provider_user_id, created_at, updated_at
FROM users
WHERE email = $1 OR username = $1
`

type GetUserByEmailOrUsernameRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	UserType       string             `json:"user_type"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	AuthProvider   pgtype.Text        `json:"auth_provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i GetUserByEmailOrUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.AvatarUrl,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, first_name, last_name, user_type, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	UserType  string             `json:"user_type"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, username, email, password_hash, first_name, last_name, user_type,
       auth_provider, provider_user_id, created_at, updated_at
FROM users
WHERE auth_provider = $1 AND provider_user_id = $2
`

type GetUserByProviderIDParams struct {
	AuthProvider   pgtype.Text `json:"auth_provider"`
	ProviderUserID pgtype.Text `json:"provider_user_id"`
}

type GetUserByProviderIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	UserType       string             `json:"user_type"`
	AuthProvider   pgtype.Text        `json:"auth_provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.AuthProvider, arg.ProviderUserID)
	var i GetUserByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash
FROM users
WHERE id = $1
`

// Deliberately narrow: only the password hash, so it is never carried around on
// the general-purpose user row. Used to verify the current password on change.
func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash pgtype.Text
	err := row.Scan(&password_hash)
	return password_hash, err
}

const isUserActive = `-- name: IsUserActive :one
SELECT is_active FROM users WHERE id = $1
`

func (q *Queries) IsUserActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserActive, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const linkProviderToUser = `-- name: LinkProviderToUser :exec
UPDATE users
SET auth_provider = $2, provider_user_id = $3, updated_at = NOW()
WHERE id = $1
`

type LinkProviderToUserParams struct {
	ID             uuid.UUID   `json:"id"`
	AuthProvider   pgtype.Text `json:"auth_provider"`
	ProviderUserID pgtype.Text `json:"provider_user_id"`
}

func (q *Queries) LinkProviderToUser(ctx context.Context, arg LinkProviderToUserParams) error {
	_, err := q.db.Exec(ctx, linkProviderToUser, arg.ID, arg.AuthProvider, arg.ProviderUserID)
	return err
}

const listActiveRefreshTokens = `-- name: ListActiveRefreshTokens :many
SELECT
    rt.id,
    rt.user_id,
    rt.expires_at,
    rt.created_at,
    u.username,
    u.email
FROM refresh_tokens rt
JOIN users u ON rt.user_id = u.id
WHERE rt.revoked_at IS NULL AND rt.expires_at > NOW()
ORDER BY rt.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveRefreshTokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActiveRefreshTokensRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
}

func (q *Queries) ListActiveRefreshTokens(ctx context.Context, arg ListActiveRefreshTokensParams) ([]ListActiveRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRefreshTokensRow{}
	for rows.Next() {
		var i ListActiveRefreshTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, username, email, first_name, last_name, user_type, is_active, created_at, updated_at
FROM users
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersPaginatedRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	UserType  string             `json:"user_type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersPaginatedRow{}
	for rows.Next() {
		var i ListUsersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const searchUsersPaginated = `-- name: SearchUsersPaginated :many
SELECT id, username, email, first_name, last_name, user_type, is_active, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
  AND (
    username ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
    OR (first_name || ' ' || last_name) ILIKE '%' || $1 || '%'
  )
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type SearchUsersPaginatedParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchUsersPaginatedRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	UserType  string             `json:"user_type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]SearchUsersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, searchUsersPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersPaginatedRow{}
	for rows.Next() {
		var i SearchUsersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = FALSE, deactivated_at = NOW(), deactivated_by = $1, updated_at = NOW()
WHERE id = $2
`

type DeactivateUserParams struct {
	DeactivatedBy pgtype.UUID `json:"deactivated_by"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.DeactivatedBy, arg.ID)
	return err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users
SET is_active = TRUE, deactivated_at = NULL, deactivated_by = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(), deleted_by = $1, is_active = FALSE, updated_at = NOW()
WHERE id = $2
`

type SoftDeleteUserParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.DeletedBy, arg.ID)
	return err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL, deleted_by = NULL, is_active = TRUE, deactivated_at = NULL, deactivated_by = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const countUsersByState = `-- name: CountUsersByState :one
SELECT
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND is_active)     AS active,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND NOT is_active) AS deactivated,
    COUNT(*) FILTER (WHERE deleted_at IS NOT NULL)               AS deleted
FROM users
`

type CountUsersByStateRow struct {
	Active      int64 `json:"active"`
	Deactivated int64 `json:"deactivated"`
	Deleted     int64 `json:"deleted"`
}

func (q *Queries) CountUsersByState(ctx context.Context) (CountUsersByStateRow, error) {
	row := q.db.QueryRow(ctx, countUsersByState)
	var i CountUsersByStateRow
	err := row.Scan(&i.Active, &i.Deactivated, &i.Deleted)
	return i, err
}

const countUsersByStateSearch = `-- name: CountUsersByStateSearch :one
SELECT COUNT(*)
FROM users
WHERE (
        ($1::text = 'active'      AND deleted_at IS NULL AND is_active)
     OR ($1::text = 'deactivated' AND deleted_at IS NULL AND NOT is_active)
     OR ($1::text = 'deleted'     AND deleted_at IS NOT NULL)
      )
  AND (
        $2::text = ''
     OR username ILIKE '%' || $2 || '%'
     OR email ILIKE '%' || $2 || '%'
     OR first_name ILIKE '%' || $2 || '%'
     OR last_name ILIKE '%' || $2 || '%'
     OR (first_name || ' ' || last_name) ILIKE '%' || $2 || '%'
      )
`

type CountUsersByStateSearchParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
}

func (q *Queries) CountUsersByStateSearch(ctx context.Context, arg CountUsersByStateSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStateSearch, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsersByState = `-- name: ListUsersByState :many
SELECT u.id, u.username, u.email, u.first_name, u.last_name, u.user_type, u.is_active,
       u.deactivated_at, u.deleted_at, u.created_at, u.updated_at,
       COALESCE(da.first_name || ' ' || da.last_name, '')::text AS deactivated_by_name,
       COALESCE(dl.first_name || ' ' || dl.last_name, '')::text AS deleted_by_name
FROM users u
LEFT JOIN users da ON u.deactivated_by = da.id
LEFT JOIN users dl ON u.deleted_by = dl.id
WHERE (
        ($1::text = 'active'      AND u.deleted_at IS NULL AND u.is_active)
     OR ($1::text = 'deactivated' AND u.deleted_at IS NULL AND NOT u.is_active)
     OR ($1::text = 'deleted'     AND u.deleted_at IS NOT NULL)
      )
  AND (
        $2::text = ''
     OR u.username ILIKE '%' || $2 || '%'
     OR u.email ILIKE '%' || $2 || '%'
     OR u.first_name ILIKE '%' || $2 || '%'
     OR u.last_name ILIKE '%' || $2 || '%'
     OR (u.first_name || ' ' || u.last_name) ILIKE '%' || $2 || '%'
      )
ORDER BY u.created_at ASC
LIMIT $3 OFFSET $4
`

type ListUsersByStateParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
	Lim    int32  `json:"lim"`
	Off    int32  `json:"off"`
}

type ListUsersByStateRow struct {
	ID                uuid.UUID          `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	UserType          string             `json:"user_type"`
	IsActive          bool               `json:"is_active"`
	DeactivatedAt     pgtype.Timestamptz `json:"deactivated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeactivatedByName string             `json:"deactivated_by_name"`
	DeletedByName     string             `json:"deleted_by_name"`
}

func (q *Queries) ListUsersByState(ctx context.Context, arg ListUsersByStateParams) ([]ListUsersByStateRow, error) {
	rows, err := q.db.Query(ctx, listUsersByState,
		arg.Status,
		arg.Search,
		arg.Lim,
		arg.Off,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByStateRow{}
	for rows.Next() {
		var i ListUsersByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.IsActive,
			&i.DeactivatedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedByName,
			&i.DeletedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatarURL = `-- name: UpdateUserAvatarURL :exec
UPDATE users
SET avatar_url = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserAvatarURLParams struct {
	ID        uuid.UUID   `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarURL, arg.ID, arg.AvatarUrl)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserType = `-- name: UpdateUserType :exec
UPDATE users
SET user_type = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTypeParams struct {
	ID       uuid.UUID `json:"id"`
	UserType string    `json:"user_type"`
}

func (q *Queries) UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error {
	_, err := q.db.Exec(ctx, updateUserType, arg.ID, arg.UserType)
	return err
}

const userExistsByEmailOrUsername = `-- name: UserExistsByEmailOrUsername :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE email = $1 OR username = $2
) AS exists
`

type UserExistsByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) UserExistsByEmailOrUsername(ctx context.Context, arg UserExistsByEmailOrUsernameParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmailOrUsername, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserStatusByEmailOrUsername = `-- name: GetUserStatusByEmailOrUsername :one
SELECT is_active, deleted_at
FROM users
WHERE email = $1 OR username = $2
LIMIT 1
`

type GetUserStatusByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type GetUserStatusByEmailOrUsernameRow struct {
	IsActive  bool               `json:"is_active"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserStatusByEmailOrUsername(ctx context.Context, arg GetUserStatusByEmailOrUsernameParams) (GetUserStatusByEmailOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserStatusByEmailOrUsername, arg.Email, arg.Username)
	var i GetUserStatusByEmailOrUsernameRow
	err := row.Scan(&i.IsActive, &i.DeletedAt)
	return i, err
}
