// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycles.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTasksToCycle = `-- name: AddTasksToCycle :exec

INSERT INTO cycle_tasks (cycle_id, task_id, added_by)
SELECT $1::uuid, tid, $2::uuid
FROM unnest($3::uuid[]) AS tid
ON CONFLICT DO NOTHING
`

type AddTasksToCycleParams struct {
	CycleID uuid.UUID   `json:"cycle_id"`
	AddedBy uuid.UUID   `json:"added_by"`
	TaskIds []uuid.UUID `json:"task_ids"`
}

// ==================== CYCLE TASKS ====================
func (q *Queries) AddTasksToCycle(ctx context.Context, arg AddTasksToCycleParams) error {
	_, err := q.db.Exec(ctx, addTasksToCycle, arg.CycleID, arg.AddedBy, arg.TaskIds)
	return err
}

const checkCycleOverlap = `-- name: CheckCycleOverlap :one
SELECT COUNT(*)::int AS overlap_count
FROM cycles
WHERE project_id = $1
  AND deleted_at IS NULL
  AND NOT (end_date < $2::date OR start_date > $3::date)
  AND ($4::uuid IS NULL OR id <> $4::uuid)
`

type CheckCycleOverlapParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) CheckCycleOverlap(ctx context.Context, arg CheckCycleOverlapParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkCycleOverlap,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.ExcludeID,
	)
	var overlap_count int32
	err := row.Scan(&overlap_count)
	return overlap_count, err
}

const countProjectCycles = `-- name: CountProjectCycles :one
SELECT COUNT(*)
FROM cycles
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectCycles(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectCycles, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCycle = `-- name: CreateCycle :one

INSERT INTO cycles (project_id, title, description, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, title, description, start_date, end_date, created_by, created_at, updated_at, deleted_at
`

type CreateCycleParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

// ==================== CYCLES ====================
func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, createCycle,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCycleByID = `-- name: GetCycleByID :one
SELECT c.id, c.project_id, c.title, c.description, c.start_date, c.end_date,
       c.created_by, c.created_at, c.updated_at, c.deleted_at,
       p.project_key, p.name AS project_name
FROM cycles c
JOIN projects p ON c.project_id = p.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCycleByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) GetCycleByID(ctx context.Context, id uuid.UUID) (GetCycleByIDRow, error) {
	row := q.db.QueryRow(ctx, getCycleByID, id)
	var i GetCycleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.ProjectName,
	)
	return i, err
}

const getCycleMetrics = `-- name: GetCycleMetrics :one
SELECT
    COUNT(*)::int                                                         AS total,
    COUNT(*) FILTER (WHERE ps.state_type = 'completed')::int             AS completed,
    COUNT(*) FILTER (WHERE ps.state_type = 'started')::int               AS in_progress,
    COUNT(*) FILTER (WHERE ps.state_type IN ('backlog', 'unstarted'))::int AS todo,
    COUNT(*) FILTER (WHERE ps.state_type = 'cancelled')::int             AS cancelled
FROM cycle_tasks ct
JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN project_states ps ON t.state_id = ps.id
WHERE ct.cycle_id = $1
`

type GetCycleMetricsRow struct {
	Total      int32 `json:"total"`
	Completed  int32 `json:"completed"`
	InProgress int32 `json:"in_progress"`
	Todo       int32 `json:"todo"`
	Cancelled  int32 `json:"cancelled"`
}

func (q *Queries) GetCycleMetrics(ctx context.Context, cycleID uuid.UUID) (GetCycleMetricsRow, error) {
	row := q.db.QueryRow(ctx, getCycleMetrics, cycleID)
	var i GetCycleMetricsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.InProgress,
		&i.Todo,
		&i.Cancelled,
	)
	return i, err
}

const getCycleStateBreakdown = `-- name: GetCycleStateBreakdown :many
SELECT ps.id AS state_id, ps.name AS state_name, ps.color AS state_color,
       ps.state_type, ps.position,
       COUNT(t.id)::int AS task_count
FROM cycle_tasks ct
JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN project_states ps ON t.state_id = ps.id
WHERE ct.cycle_id = $1
GROUP BY ps.id, ps.name, ps.color, ps.state_type, ps.position
ORDER BY ps.position ASC
`

type GetCycleStateBreakdownRow struct {
	StateID    uuid.UUID   `json:"state_id"`
	StateName  string      `json:"state_name"`
	StateColor pgtype.Text `json:"state_color"`
	StateType  string      `json:"state_type"`
	Position   int32       `json:"position"`
	TaskCount  int32       `json:"task_count"`
}

func (q *Queries) GetCycleStateBreakdown(ctx context.Context, cycleID uuid.UUID) ([]GetCycleStateBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCycleStateBreakdown, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCycleStateBreakdownRow{}
	for rows.Next() {
		var i GetCycleStateBreakdownRow
		if err := rows.Scan(
			&i.StateID,
			&i.StateName,
			&i.StateColor,
			&i.StateType,
			&i.Position,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCycleID = `-- name: GetTaskCycleID :one
SELECT cycle_id FROM cycle_tasks WHERE task_id = $1
`

func (q *Queries) GetTaskCycleID(ctx context.Context, taskID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskCycleID, taskID)
	var cycle_id uuid.UUID
	err := row.Scan(&cycle_id)
	return cycle_id, err
}

const listActiveCyclesForUser = `-- name: ListActiveCyclesForUser :many
SELECT c.id, c.project_id, c.title, c.description, c.start_date, c.end_date,
       c.created_by, c.created_at, c.updated_at,
       p.project_key, p.name AS project_name,
       COALESCE(stats.total_tasks, 0)::int     AS total_tasks,
       COALESCE(stats.completed_tasks, 0)::int AS completed_tasks
FROM cycles c
JOIN projects p ON c.project_id = p.id AND p.deleted_at IS NULL
JOIN project_members pm ON p.id = pm.project_id AND pm.user_id = $1
LEFT JOIN LATERAL (
    SELECT COUNT(*)                                                          AS total_tasks,
           COUNT(*) FILTER (WHERE ps.state_type = 'completed')              AS completed_tasks
    FROM cycle_tasks ct
    JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
    JOIN project_states ps ON t.state_id = ps.id
    WHERE ct.cycle_id = c.id
) stats ON TRUE
WHERE c.deleted_at IS NULL
  AND CURRENT_DATE BETWEEN c.start_date AND c.end_date
ORDER BY c.end_date ASC, p.name ASC
`

type ListActiveCyclesForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	TotalTasks     int32              `json:"total_tasks"`
	CompletedTasks int32              `json:"completed_tasks"`
}

func (q *Queries) ListActiveCyclesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveCyclesForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveCyclesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCyclesForUserRow{}
	for rows.Next() {
		var i ListActiveCyclesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.TotalTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCycleAssignees = `-- name: ListCycleAssignees :many
SELECT u.id AS user_id, u.username, u.first_name, u.last_name, u.avatar_url,
       COUNT(DISTINCT t.id)::int AS task_count
FROM cycle_tasks ct
JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN task_assignees ta ON t.id = ta.task_id
JOIN users u ON ta.user_id = u.id
WHERE ct.cycle_id = $1
GROUP BY u.id, u.username, u.first_name, u.last_name, u.avatar_url
ORDER BY task_count DESC, u.first_name ASC
`

type ListCycleAssigneesRow struct {
	UserID    uuid.UUID   `json:"user_id"`
	Username  string      `json:"username"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	TaskCount int32       `json:"task_count"`
}

func (q *Queries) ListCycleAssignees(ctx context.Context, cycleID uuid.UUID) ([]ListCycleAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listCycleAssignees, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCycleAssigneesRow{}
	for rows.Next() {
		var i ListCycleAssigneesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCycleTasks = `-- name: ListCycleTasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority,
       t.start_date, t.due_date, t.created_by, t.created_at, t.updated_at,
       p.project_key,
       ps.name AS state_name, ps.state_type, ps.color AS state_color
FROM cycle_tasks ct
JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE ct.cycle_id = $1
  AND ($2::uuid IS NULL OR EXISTS (
      SELECT 1 FROM task_assignees ta
      WHERE ta.task_id = t.id AND ta.user_id = $2::uuid
  ))
ORDER BY ps.position ASC, t.created_at DESC
`

type ListCycleTasksParams struct {
	CycleID    uuid.UUID   `json:"cycle_id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

type ListCycleTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	TaskNumber  int32              `json:"task_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StateID     uuid.UUID          `json:"state_id"`
	Priority    int32              `json:"priority"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectKey  string             `json:"project_key"`
	StateName   string             `json:"state_name"`
	StateType   string             `json:"state_type"`
	StateColor  pgtype.Text        `json:"state_color"`
}

func (q *Queries) ListCycleTasks(ctx context.Context, arg ListCycleTasksParams) ([]ListCycleTasksRow, error) {
	rows, err := q.db.Query(ctx, listCycleTasks, arg.CycleID, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCycleTasksRow{}
	for rows.Next() {
		var i ListCycleTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.Priority,
			&i.StartDate,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCycles = `-- name: ListProjectCycles :many
SELECT c.id, c.project_id, c.title, c.description, c.start_date, c.end_date,
       c.created_by, c.created_at, c.updated_at,
       COALESCE(stats.total_tasks, 0)::int     AS total_tasks,
       COALESCE(stats.completed_tasks, 0)::int AS completed_tasks
FROM cycles c
LEFT JOIN LATERAL (
    SELECT COUNT(*)                                                          AS total_tasks,
           COUNT(*) FILTER (WHERE ps.state_type = 'completed')              AS completed_tasks
    FROM cycle_tasks ct
    JOIN tasks t ON ct.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
    JOIN project_states ps ON t.state_id = ps.id
    WHERE ct.cycle_id = c.id
) stats ON TRUE
WHERE c.project_id = $1 AND c.deleted_at IS NULL
ORDER BY c.start_date DESC, c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectCyclesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListProjectCyclesRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TotalTasks     int32              `json:"total_tasks"`
	CompletedTasks int32              `json:"completed_tasks"`
}

func (q *Queries) ListProjectCycles(ctx context.Context, arg ListProjectCyclesParams) ([]ListProjectCyclesRow, error) {
	rows, err := q.db.Query(ctx, listProjectCycles, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectCyclesRow{}
	for rows.Next() {
		var i ListProjectCyclesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCyclesAll = `-- name: ListProjectCyclesAll :many
SELECT c.id, c.title, c.start_date, c.end_date
FROM cycles c
WHERE c.project_id = $1 AND c.deleted_at IS NULL
ORDER BY c.start_date DESC
`

type ListProjectCyclesAllRow struct {
	ID        uuid.UUID   `json:"id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListProjectCyclesAll(ctx context.Context, projectID uuid.UUID) ([]ListProjectCyclesAllRow, error) {
	rows, err := q.db.Query(ctx, listProjectCyclesAll, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectCyclesAllRow{}
	for rows.Next() {
		var i ListProjectCyclesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedProjectTasks = `-- name: ListUnassignedProjectTasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       p.project_key, ps.name AS state_name, ps.state_type, ps.color AS state_color
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE t.project_id = $1 AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM cycle_tasks ct WHERE ct.task_id = t.id)
  AND ($3::text IS NULL
       OR t.title ILIKE '%' || $3 || '%')
ORDER BY t.created_at DESC
LIMIT $2
`

type ListUnassignedProjectTasksParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Limit     int32       `json:"limit"`
	Search    pgtype.Text `json:"search"`
}

type ListUnassignedProjectTasksRow struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	TaskNumber int32       `json:"task_number"`
	Title      string      `json:"title"`
	StateID    uuid.UUID   `json:"state_id"`
	Priority   int32       `json:"priority"`
	ProjectKey string      `json:"project_key"`
	StateName  string      `json:"state_name"`
	StateType  string      `json:"state_type"`
	StateColor pgtype.Text `json:"state_color"`
}

func (q *Queries) ListUnassignedProjectTasks(ctx context.Context, arg ListUnassignedProjectTasksParams) ([]ListUnassignedProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listUnassignedProjectTasks, arg.ProjectID, arg.Limit, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnassignedProjectTasksRow{}
	for rows.Next() {
		var i ListUnassignedProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskFromCycle = `-- name: RemoveTaskFromCycle :exec
DELETE FROM cycle_tasks
WHERE cycle_id = $1 AND task_id = $2
`

type RemoveTaskFromCycleParams struct {
	CycleID uuid.UUID `json:"cycle_id"`
	TaskID  uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveTaskFromCycle(ctx context.Context, arg RemoveTaskFromCycleParams) error {
	_, err := q.db.Exec(ctx, removeTaskFromCycle, arg.CycleID, arg.TaskID)
	return err
}

const searchAllCycles = `-- name: SearchAllCycles :many
SELECT c.id, c.title, c.start_date, c.end_date,
       p.id AS project_id, p.project_key, p.name AS project_name
FROM cycles c
JOIN projects p ON c.project_id = p.id
WHERE c.deleted_at IS NULL AND p.deleted_at IS NULL
  AND c.title ILIKE '%' || $1::text || '%'
ORDER BY
  CASE WHEN c.title ILIKE $1::text || '%' THEN 0 ELSE 1 END,
  c.start_date DESC
LIMIT $2
`

type SearchAllCyclesParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

type SearchAllCyclesRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ProjectID   uuid.UUID   `json:"project_id"`
	ProjectKey  string      `json:"project_key"`
	ProjectName string      `json:"project_name"`
}

// Admin variant: matches across all projects.
func (q *Queries) SearchAllCycles(ctx context.Context, arg SearchAllCyclesParams) ([]SearchAllCyclesRow, error) {
	rows, err := q.db.Query(ctx, searchAllCycles, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAllCyclesRow{}
	for rows.Next() {
		var i SearchAllCyclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserCycles = `-- name: SearchUserCycles :many

SELECT c.id, c.title, c.start_date, c.end_date,
       p.id AS project_id, p.project_key, p.name AS project_name
FROM cycles c
JOIN projects p ON c.project_id = p.id
WHERE EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id = p.id AND pm.user_id = $1)
  AND c.deleted_at IS NULL AND p.deleted_at IS NULL
  AND c.title ILIKE '%' || $2::text || '%'
ORDER BY
  CASE WHEN c.title ILIKE $2::text || '%' THEN 0 ELSE 1 END,
  c.start_date DESC
LIMIT $3
`

type SearchUserCyclesParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Query      string    `json:"query"`
	LimitCount int32     `json:"limit_count"`
}

type SearchUserCyclesRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ProjectID   uuid.UUID   `json:"project_id"`
	ProjectKey  string      `json:"project_key"`
	ProjectName string      `json:"project_name"`
}

// ==================== GLOBAL SEARCH ====================
// Matches cycles by title across projects the user is a member of.
func (q *Queries) SearchUserCycles(ctx context.Context, arg SearchUserCyclesParams) ([]SearchUserCyclesRow, error) {
	rows, err := q.db.Query(ctx, searchUserCycles, arg.UserID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUserCyclesRow{}
	for rows.Next() {
		var i SearchUserCyclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCycle = `-- name: SoftDeleteCycle :exec
UPDATE cycles
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCycle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCycle, id)
	return err
}

const updateCycle = `-- name: UpdateCycle :one
UPDATE cycles
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    start_date  = COALESCE($4, start_date),
    end_date    = COALESCE($5, end_date),
    updated_at  = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, title, description, start_date, end_date, created_by, created_at, updated_at, deleted_at
`

type UpdateCycleParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, updateCycle,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
	)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
