// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merge_users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const mergeCopyModuleMembers = `-- name: MergeCopyModuleMembers :execrows
INSERT INTO module_members (module_id, user_id, added_by)
SELECT module_id, $1::uuid, added_by
FROM module_members
WHERE user_id = $2::uuid
ON CONFLICT (module_id, user_id) DO NOTHING
`

type MergeCopyModuleMembersParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) MergeCopyModuleMembers(ctx context.Context, arg MergeCopyModuleMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCopyModuleMembers, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeCopyPrivateViews = `-- name: MergeCopyPrivateViews :execrows
INSERT INTO project_views (
    project_id, slug, name, description, visibility, owner_id,
    filter_tree, group_by, sort_by, sort_dir, default_tab, position
)
SELECT project_id,
       LEFT(slug, 55) || '-' || LEFT(REPLACE(uuid_generate_v4()::text, '-', ''), 8),
       name, description, visibility, $1::uuid,
       filter_tree, group_by, sort_by, sort_dir, default_tab, position
FROM project_views
WHERE owner_id = $2::uuid
  AND visibility = 'private'
  AND deleted_at IS NULL
`

type MergeCopyPrivateViewsParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) MergeCopyPrivateViews(ctx context.Context, arg MergeCopyPrivateViewsParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCopyPrivateViews, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeCopyProjectMembers = `-- name: MergeCopyProjectMembers :execrows
INSERT INTO project_members (project_id, user_id, role)
SELECT project_id, $1::uuid, role
FROM project_members
WHERE user_id = $2::uuid
ON CONFLICT (project_id, user_id) DO UPDATE
SET role = EXCLUDED.role
WHERE project_members.role < EXCLUDED.role
`

type MergeCopyProjectMembersParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) MergeCopyProjectMembers(ctx context.Context, arg MergeCopyProjectMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCopyProjectMembers, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeCopyTaskAssignees = `-- name: MergeCopyTaskAssignees :execrows
INSERT INTO task_assignees (task_id, user_id, assigned_by)
SELECT task_id, $1::uuid, assigned_by
FROM task_assignees
WHERE user_id = $2::uuid
ON CONFLICT (task_id, user_id) DO NOTHING
`

type MergeCopyTaskAssigneesParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

func (q *Queries) MergeCopyTaskAssignees(ctx context.Context, arg MergeCopyTaskAssigneesParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCopyTaskAssignees, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeCopyWorkspaceMembers = `-- name: MergeCopyWorkspaceMembers :execrows

INSERT INTO workspace_members (workspace_id, user_id)
SELECT workspace_id, $1::uuid
FROM workspace_members
WHERE user_id = $2::uuid
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type MergeCopyWorkspaceMembersParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

// Admin "merge user": additively grants the target everything the source has.
// The source user is never modified and activity_log is never touched.
func (q *Queries) MergeCopyWorkspaceMembers(ctx context.Context, arg MergeCopyWorkspaceMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCopyWorkspaceMembers, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeWatchSourceTasks = `-- name: MergeWatchSourceTasks :execrows
INSERT INTO task_watchers (task_id, user_id, added_by)
SELECT task_id, $1::uuid, $1::uuid FROM (
  SELECT id AS task_id FROM tasks
  WHERE created_by = $2::uuid AND deleted_at IS NULL
  UNION
  SELECT task_id FROM task_watchers
  WHERE user_id = $2::uuid
  UNION
  SELECT task_id FROM comments
  WHERE created_by = $2::uuid AND deleted_at IS NULL
) src
ON CONFLICT (task_id, user_id) DO NOTHING
`

type MergeWatchSourceTasksParams struct {
	TargetID uuid.UUID `json:"target_id"`
	SourceID uuid.UUID `json:"source_id"`
}

// The target starts watching every task the source created, watched or
// commented on, so the merged account keeps receiving those updates.
func (q *Queries) MergeWatchSourceTasks(ctx context.Context, arg MergeWatchSourceTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeWatchSourceTasks, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
