// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType string

const (
	ActivityTypeTaskCreated     ActivityType = "task_created"
	ActivityTypeTaskUpdated     ActivityType = "task_updated"
	ActivityTypeTaskDeleted     ActivityType = "task_deleted"
	ActivityTypeAssigneeAdded   ActivityType = "assignee_added"
	ActivityTypeAssigneeRemoved ActivityType = "assignee_removed"
	ActivityTypeLabelAdded      ActivityType = "label_added"
	ActivityTypeLabelRemoved    ActivityType = "label_removed"
	ActivityTypeStateChanged    ActivityType = "state_changed"
	ActivityTypeCommentCreated  ActivityType = "comment_created"
	ActivityTypeCommentUpdated  ActivityType = "comment_updated"
	ActivityTypeCommentDeleted  ActivityType = "comment_deleted"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activity_type"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type ModuleStatus string

const (
	ModuleStatusBacklog    ModuleStatus = "backlog"
	ModuleStatusPlanned    ModuleStatus = "planned"
	ModuleStatusInProgress ModuleStatus = "in_progress"
	ModuleStatusPaused     ModuleStatus = "paused"
	ModuleStatusCompleted  ModuleStatus = "completed"
	ModuleStatusCancelled  ModuleStatus = "cancelled"
)

func (e *ModuleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModuleStatus(s)
	case string:
		*e = ModuleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ModuleStatus: %T", src)
	}
	return nil
}

type NullModuleStatus struct {
	ModuleStatus ModuleStatus `json:"module_status"`
	Valid        bool         `json:"valid"` // Valid is true if ModuleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModuleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ModuleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModuleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModuleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModuleStatus), nil
}

type ProjectRole string

const (
	ProjectRoleGuest  ProjectRole = "guest"
	ProjectRoleMember ProjectRole = "member"
	ProjectRoleAdmin  ProjectRole = "admin"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"project_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type StateType string

const (
	StateTypeBacklog   StateType = "backlog"
	StateTypeUnstarted StateType = "unstarted"
	StateTypeStarted   StateType = "started"
	StateTypeCompleted StateType = "completed"
	StateTypeCancelled StateType = "cancelled"
)

func (e *StateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StateType(s)
	case string:
		*e = StateType(s)
	default:
		return fmt.Errorf("unsupported scan type for StateType: %T", src)
	}
	return nil
}

type NullStateType struct {
	StateType StateType `json:"state_type"`
	Valid     bool      `json:"valid"` // Valid is true if StateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStateType) Scan(value interface{}) error {
	if value == nil {
		ns.StateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StateType), nil
}

type UserType string

const (
	UserTypeAdmin UserType = "admin"
	UserTypeUser  UserType = "user"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType `json:"user_type"`
	Valid    bool     `json:"valid"` // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

type ViewVisibility string

const (
	ViewVisibilityPrivate ViewVisibility = "private"
	ViewVisibilityShared  ViewVisibility = "shared"
)

func (e *ViewVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViewVisibility(s)
	case string:
		*e = ViewVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ViewVisibility: %T", src)
	}
	return nil
}

type NullViewVisibility struct {
	ViewVisibility ViewVisibility `json:"view_visibility"`
	Valid          bool           `json:"valid"` // Valid is true if ViewVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViewVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ViewVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViewVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViewVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViewVisibility), nil
}

type ActivityLog struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Checksum     string             `json:"checksum"`
}

type Attachment struct {
	ID         uuid.UUID          `json:"id"`
	UploadID   uuid.UUID          `json:"upload_id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Cycle struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type CycleTask struct {
	CycleID uuid.UUID          `json:"cycle_id"`
	TaskID  uuid.UUID          `json:"task_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	AddedBy uuid.UUID          `json:"added_by"`
}

type Feedback struct {
	ID           uuid.UUID          `json:"id"`
	Message      string             `json:"message"`
	SourceOrigin pgtype.Text        `json:"source_origin"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Module struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	LeadID      pgtype.UUID        `json:"lead_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ModuleMember struct {
	ModuleID uuid.UUID          `json:"module_id"`
	UserID   uuid.UUID          `json:"user_id"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
	AddedBy  uuid.UUID          `json:"added_by"`
}

type ModuleTask struct {
	ModuleID uuid.UUID          `json:"module_id"`
	TaskID   uuid.UUID          `json:"task_id"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
	AddedBy  uuid.UUID          `json:"added_by"`
}

type Notification struct {
	ID           uuid.UUID          `json:"id"`
	RecipientID  uuid.UUID          `json:"recipient_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CommentID    pgtype.UUID        `json:"comment_id"`
}

type Page struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	PageNumber int32              `json:"page_number"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type PersonalAccessToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Scope      string             `json:"scope"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Disabled    bool               `json:"disabled"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
}

type ProjectLabel struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectMember struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type ProjectState struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	StateType string             `json:"state_type"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	Position  int32              `json:"position"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectView struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DefaultTab  string             `json:"default_tab"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	TaskNumber   int32              `json:"task_number"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StateID      uuid.UUID          `json:"state_id"`
	Priority     int32              `json:"priority"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
}

type TaskAssignee struct {
	ID         uuid.UUID          `json:"id"`
	TaskID     uuid.UUID          `json:"task_id"`
	UserID     uuid.UUID          `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy uuid.UUID          `json:"assigned_by"`
}

type TaskLabel struct {
	TaskID  uuid.UUID          `json:"task_id"`
	LabelID uuid.UUID          `json:"label_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	AddedBy uuid.UUID          `json:"added_by"`
}

type TaskTemplate struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Upload struct {
	ID         uuid.UUID          `json:"id"`
	Filename   string             `json:"filename"`
	StoredName string             `json:"stored_name"`
	MimeType   string             `json:"mime_type"`
	SizeBytes  int64              `json:"size_bytes"`
	UploadedBy uuid.UUID          `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	UserType       string             `json:"user_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthProvider   pgtype.Text        `json:"auth_provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
}

type Workspace struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceKey string             `json:"workspace_key"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
