// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addModuleMember = `-- name: AddModuleMember :exec

INSERT INTO module_members (module_id, user_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddModuleMemberParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	UserID   uuid.UUID `json:"user_id"`
	AddedBy  uuid.UUID `json:"added_by"`
}

// ==================== MODULE MEMBERS ====================
func (q *Queries) AddModuleMember(ctx context.Context, arg AddModuleMemberParams) error {
	_, err := q.db.Exec(ctx, addModuleMember, arg.ModuleID, arg.UserID, arg.AddedBy)
	return err
}

const addModuleMembersBulk = `-- name: AddModuleMembersBulk :exec
INSERT INTO module_members (module_id, user_id, added_by)
SELECT $1::uuid, uid, $2::uuid
FROM unnest($3::uuid[]) AS uid
ON CONFLICT DO NOTHING
`

type AddModuleMembersBulkParams struct {
	ModuleID uuid.UUID   `json:"module_id"`
	AddedBy  uuid.UUID   `json:"added_by"`
	UserIds  []uuid.UUID `json:"user_ids"`
}

func (q *Queries) AddModuleMembersBulk(ctx context.Context, arg AddModuleMembersBulkParams) error {
	_, err := q.db.Exec(ctx, addModuleMembersBulk, arg.ModuleID, arg.AddedBy, arg.UserIds)
	return err
}

const addModuleTasksBulk = `-- name: AddModuleTasksBulk :exec

INSERT INTO module_tasks (module_id, task_id, added_by)
SELECT $1::uuid, tid, $2::uuid
FROM unnest($3::uuid[]) AS tid
ON CONFLICT DO NOTHING
`

type AddModuleTasksBulkParams struct {
	ModuleID uuid.UUID   `json:"module_id"`
	AddedBy  uuid.UUID   `json:"added_by"`
	TaskIds  []uuid.UUID `json:"task_ids"`
}

// ==================== MODULE TASKS ====================
func (q *Queries) AddModuleTasksBulk(ctx context.Context, arg AddModuleTasksBulkParams) error {
	_, err := q.db.Exec(ctx, addModuleTasksBulk, arg.ModuleID, arg.AddedBy, arg.TaskIds)
	return err
}

const countProjectModules = `-- name: CountProjectModules :one
SELECT COUNT(*)
FROM modules m
WHERE m.project_id = $1 AND m.deleted_at IS NULL
  AND ($2::text     = ''     OR m.status = $2::module_status)
  AND ($3::uuid   IS NULL  OR m.lead_id = $3::uuid)
  AND ($4::date IS NULL OR m.start_date >= $4::date)
  AND ($5::date  IS NULL OR m.end_date   <= $5::date)
`

type CountProjectModulesParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Status     string      `json:"status"`
	LeadID     pgtype.UUID `json:"lead_id"`
	StartAfter pgtype.Date `json:"start_after"`
	EndBefore  pgtype.Date `json:"end_before"`
}

func (q *Queries) CountProjectModules(ctx context.Context, arg CountProjectModulesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectModules,
		arg.ProjectID,
		arg.Status,
		arg.LeadID,
		arg.StartAfter,
		arg.EndBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModule = `-- name: CreateModule :one

INSERT INTO modules (project_id, title, description, status, start_date, end_date, lead_id, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4::module_status,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, project_id, title, description, status, start_date, end_date,
          lead_id, created_by, created_at, updated_at, deleted_at
`

type CreateModuleParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	LeadID      pgtype.UUID `json:"lead_id"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

// ==================== MODULES ====================
// The handler is responsible for defaulting `status` to 'backlog' when the
// caller doesn't supply one, so the SQL can keep the arg non-nullable. This
// sidesteps sqlc's handling of nullable enum args under a string override.
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.LeadID,
		arg.CreatedBy,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.LeadID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModuleByID = `-- name: GetModuleByID :one
SELECT m.id, m.project_id, m.title, m.description, m.status,
       m.start_date, m.end_date, m.lead_id,
       m.created_by, m.created_at, m.updated_at, m.deleted_at,
       p.project_key, p.name AS project_name,
       COALESCE(stats.total_tasks, 0)::int     AS total_tasks,
       COALESCE(stats.completed_tasks, 0)::int AS completed_tasks,
       COALESCE(lu.username,   '')::text AS lead_username,
       COALESCE(lu.first_name, '')::text AS lead_first_name,
       COALESCE(lu.last_name,  '')::text AS lead_last_name,
       lu.avatar_url                     AS lead_avatar_url,
       COALESCE(lu.email,      '')::text AS lead_email
FROM modules m
JOIN projects p ON m.project_id = p.id
LEFT JOIN users lu ON m.lead_id = lu.id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int                                         AS total_tasks,
           COUNT(*) FILTER (WHERE ps.state_type = 'completed')::int AS completed_tasks
    FROM module_tasks mt
    JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
    JOIN project_states ps ON t.state_id = ps.id
    WHERE mt.module_id = m.id
) stats ON TRUE
WHERE m.id = $1 AND m.deleted_at IS NULL
`

type GetModuleByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	TotalTasks     int32              `json:"total_tasks"`
	CompletedTasks int32              `json:"completed_tasks"`
	LeadUsername   string             `json:"lead_username"`
	LeadFirstName  string             `json:"lead_first_name"`
	LeadLastName   string             `json:"lead_last_name"`
	LeadAvatarUrl  pgtype.Text        `json:"lead_avatar_url"`
	LeadEmail      string             `json:"lead_email"`
}

// COALESCE the joined user fields because LEFT JOIN on nullable lead_id would
// otherwise trip sqlc's (column-nullability-based) assumption that the fields
// are non-null.
func (q *Queries) GetModuleByID(ctx context.Context, id uuid.UUID) (GetModuleByIDRow, error) {
	row := q.db.QueryRow(ctx, getModuleByID, id)
	var i GetModuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.LeadID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.LeadUsername,
		&i.LeadFirstName,
		&i.LeadLastName,
		&i.LeadAvatarUrl,
		&i.LeadEmail,
	)
	return i, err
}

const getModuleMetrics = `-- name: GetModuleMetrics :one
SELECT
    COUNT(*)::int                                                         AS total,
    COUNT(*) FILTER (WHERE ps.state_type = 'completed')::int             AS completed,
    COUNT(*) FILTER (WHERE ps.state_type = 'started')::int               AS in_progress,
    COUNT(*) FILTER (WHERE ps.state_type IN ('backlog', 'unstarted'))::int AS todo,
    COUNT(*) FILTER (WHERE ps.state_type = 'cancelled')::int             AS cancelled
FROM module_tasks mt
JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN project_states ps ON t.state_id = ps.id
WHERE mt.module_id = $1
`

type GetModuleMetricsRow struct {
	Total      int32 `json:"total"`
	Completed  int32 `json:"completed"`
	InProgress int32 `json:"in_progress"`
	Todo       int32 `json:"todo"`
	Cancelled  int32 `json:"cancelled"`
}

func (q *Queries) GetModuleMetrics(ctx context.Context, moduleID uuid.UUID) (GetModuleMetricsRow, error) {
	row := q.db.QueryRow(ctx, getModuleMetrics, moduleID)
	var i GetModuleMetricsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.InProgress,
		&i.Todo,
		&i.Cancelled,
	)
	return i, err
}

const getModuleStateBreakdown = `-- name: GetModuleStateBreakdown :many
SELECT ps.id AS state_id, ps.name AS state_name, ps.color AS state_color,
       ps.state_type, ps.position,
       COUNT(t.id)::int AS task_count
FROM module_tasks mt
JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN project_states ps ON t.state_id = ps.id
WHERE mt.module_id = $1
GROUP BY ps.id, ps.name, ps.color, ps.state_type, ps.position
ORDER BY ps.position ASC
`

type GetModuleStateBreakdownRow struct {
	StateID    uuid.UUID   `json:"state_id"`
	StateName  string      `json:"state_name"`
	StateColor pgtype.Text `json:"state_color"`
	StateType  string      `json:"state_type"`
	Position   int32       `json:"position"`
	TaskCount  int32       `json:"task_count"`
}

func (q *Queries) GetModuleStateBreakdown(ctx context.Context, moduleID uuid.UUID) ([]GetModuleStateBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getModuleStateBreakdown, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModuleStateBreakdownRow{}
	for rows.Next() {
		var i GetModuleStateBreakdownRow
		if err := rows.Scan(
			&i.StateID,
			&i.StateName,
			&i.StateColor,
			&i.StateType,
			&i.Position,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAssigneesForSeeding = `-- name: GetTaskAssigneesForSeeding :many
SELECT DISTINCT ta.user_id
FROM task_assignees ta
WHERE ta.task_id = ANY($1::uuid[])
`

// Given a set of task IDs, return the distinct user IDs of their assignees.
// Used to auto-seed module members when tasks are linked to a module.
func (q *Queries) GetTaskAssigneesForSeeding(ctx context.Context, taskIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskAssigneesForSeeding, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveModulesForUser = `-- name: ListActiveModulesForUser :many
SELECT m.id, m.project_id, m.title, m.description, m.status,
       m.start_date, m.end_date, m.lead_id,
       m.created_by, m.created_at, m.updated_at,
       p.project_key, p.name AS project_name,
       COALESCE(stats.total_tasks, 0)::int     AS total_tasks,
       COALESCE(stats.completed_tasks, 0)::int AS completed_tasks,
       COALESCE(lu.username,   '')::text AS lead_username,
       COALESCE(lu.first_name, '')::text AS lead_first_name,
       COALESCE(lu.last_name,  '')::text AS lead_last_name,
       lu.avatar_url                     AS lead_avatar_url,
       COALESCE(lu.email,      '')::text AS lead_email
FROM modules m
JOIN projects p ON m.project_id = p.id AND p.deleted_at IS NULL
JOIN project_members pm ON p.id = pm.project_id AND pm.user_id = $1
LEFT JOIN users lu ON m.lead_id = lu.id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int                                         AS total_tasks,
           COUNT(*) FILTER (WHERE ps.state_type = 'completed')::int AS completed_tasks
    FROM module_tasks mt
    JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
    JOIN project_states ps ON t.state_id = ps.id
    WHERE mt.module_id = m.id
) stats ON TRUE
WHERE m.deleted_at IS NULL AND m.status = 'in_progress'
ORDER BY COALESCE(m.end_date, '9999-12-31'::date) ASC, p.name ASC
`

type ListActiveModulesForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	TotalTasks     int32              `json:"total_tasks"`
	CompletedTasks int32              `json:"completed_tasks"`
	LeadUsername   string             `json:"lead_username"`
	LeadFirstName  string             `json:"lead_first_name"`
	LeadLastName   string             `json:"lead_last_name"`
	LeadAvatarUrl  pgtype.Text        `json:"lead_avatar_url"`
	LeadEmail      string             `json:"lead_email"`
}

// "Active" modules across all projects the user is a member of. Uses the
// explicit status enum (modules don't derive status from dates the way cycles
// do). in_progress is the natural "currently being worked on" state.
func (q *Queries) ListActiveModulesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveModulesForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveModulesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveModulesForUserRow{}
	for rows.Next() {
		var i ListActiveModulesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.LeadID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.TotalTasks,
			&i.CompletedTasks,
			&i.LeadUsername,
			&i.LeadFirstName,
			&i.LeadLastName,
			&i.LeadAvatarUrl,
			&i.LeadEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleMembers = `-- name: ListModuleMembers :many
SELECT mm.user_id, mm.added_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM module_members mm
JOIN users u ON mm.user_id = u.id
WHERE mm.module_id = $1
ORDER BY mm.added_at ASC
`

type ListModuleMembersRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListModuleMembers(ctx context.Context, moduleID uuid.UUID) ([]ListModuleMembersRow, error) {
	rows, err := q.db.Query(ctx, listModuleMembers, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModuleMembersRow{}
	for rows.Next() {
		var i ListModuleMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.AddedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleMembersForModules = `-- name: ListModuleMembersForModules :many
SELECT mm.module_id, mm.user_id,
       u.username, u.first_name, u.last_name, u.avatar_url
FROM module_members mm
JOIN users u ON mm.user_id = u.id
WHERE mm.module_id = ANY($1::uuid[])
ORDER BY mm.module_id, mm.added_at ASC
`

type ListModuleMembersForModulesRow struct {
	ModuleID  uuid.UUID   `json:"module_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Username  string      `json:"username"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// Used for hydrating the list view with member avatars. Returns up to 4 members
// per module so the card can show 3 + "+N more".
func (q *Queries) ListModuleMembersForModules(ctx context.Context, moduleIds []uuid.UUID) ([]ListModuleMembersForModulesRow, error) {
	rows, err := q.db.Query(ctx, listModuleMembersForModules, moduleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModuleMembersForModulesRow{}
	for rows.Next() {
		var i ListModuleMembersForModulesRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.UserID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleTaskIDs = `-- name: ListModuleTaskIDs :many
SELECT task_id FROM module_tasks WHERE module_id = $1
`

// Used by the duplicate dialog to pre-populate the issues checklist.
func (q *Queries) ListModuleTaskIDs(ctx context.Context, moduleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listModuleTaskIDs, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleTasks = `-- name: ListModuleTasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority,
       t.start_date, t.due_date, t.created_by, t.created_at, t.updated_at,
       p.project_key,
       ps.name AS state_name, ps.state_type, ps.color AS state_color
FROM module_tasks mt
JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE mt.module_id = $1
  AND ($2::uuid IS NULL OR EXISTS (
      SELECT 1 FROM task_assignees ta
      WHERE ta.task_id = t.id AND ta.user_id = $2::uuid
  ))
ORDER BY ps.position ASC, t.created_at DESC
`

type ListModuleTasksParams struct {
	ModuleID   uuid.UUID   `json:"module_id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

type ListModuleTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	TaskNumber  int32              `json:"task_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	StateID     uuid.UUID          `json:"state_id"`
	Priority    int32              `json:"priority"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectKey  string             `json:"project_key"`
	StateName   string             `json:"state_name"`
	StateType   string             `json:"state_type"`
	StateColor  pgtype.Text        `json:"state_color"`
}

func (q *Queries) ListModuleTasks(ctx context.Context, arg ListModuleTasksParams) ([]ListModuleTasksRow, error) {
	rows, err := q.db.Query(ctx, listModuleTasks, arg.ModuleID, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModuleTasksRow{}
	for rows.Next() {
		var i ListModuleTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.Priority,
			&i.StartDate,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectModules = `-- name: ListProjectModules :many
SELECT m.id, m.project_id, m.title, m.description, m.status,
       m.start_date, m.end_date, m.lead_id,
       m.created_by, m.created_at, m.updated_at,
       COALESCE(stats.total_tasks, 0)::int     AS total_tasks,
       COALESCE(stats.completed_tasks, 0)::int AS completed_tasks,
       COALESCE(lu.username,   '')::text AS lead_username,
       COALESCE(lu.first_name, '')::text AS lead_first_name,
       COALESCE(lu.last_name,  '')::text AS lead_last_name,
       lu.avatar_url                     AS lead_avatar_url,
       COALESCE(lu.email,      '')::text AS lead_email
FROM modules m
LEFT JOIN users lu ON m.lead_id = lu.id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int                                         AS total_tasks,
           COUNT(*) FILTER (WHERE ps.state_type = 'completed')::int AS completed_tasks
    FROM module_tasks mt
    JOIN tasks t ON mt.task_id = t.id AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
    JOIN project_states ps ON t.state_id = ps.id
    WHERE mt.module_id = m.id
) stats ON TRUE
WHERE m.project_id = $1 AND m.deleted_at IS NULL
  AND ($4::text     = ''     OR m.status = $4::module_status)
  AND ($5::uuid   IS NULL  OR m.lead_id = $5::uuid)
  AND ($6::date IS NULL OR m.start_date >= $6::date)
  AND ($7::date  IS NULL OR m.end_date   <= $7::date)
ORDER BY
    CASE WHEN $8::text = 'end_date' AND $9::text = 'asc'
         THEN m.end_date END ASC NULLS LAST,
    CASE WHEN $8::text = 'end_date' AND $9::text = 'desc'
         THEN m.end_date END DESC NULLS LAST,
    CASE WHEN $8::text = 'progress' AND $9::text = 'asc'
         THEN CASE WHEN COALESCE(stats.total_tasks, 0) = 0 THEN 0
                   ELSE (COALESCE(stats.completed_tasks, 0)::float / stats.total_tasks::float)
              END END ASC NULLS LAST,
    CASE WHEN $8::text = 'progress' AND $9::text = 'desc'
         THEN CASE WHEN COALESCE(stats.total_tasks, 0) = 0 THEN 0
                   ELSE (COALESCE(stats.completed_tasks, 0)::float / stats.total_tasks::float)
              END END DESC NULLS LAST,
    m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectModulesParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     string      `json:"status"`
	LeadID     pgtype.UUID `json:"lead_id"`
	StartAfter pgtype.Date `json:"start_after"`
	EndBefore  pgtype.Date `json:"end_before"`
	SortBy     string      `json:"sort_by"`
	SortDir    string      `json:"sort_dir"`
}

type ListProjectModulesRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TotalTasks     int32              `json:"total_tasks"`
	CompletedTasks int32              `json:"completed_tasks"`
	LeadUsername   string             `json:"lead_username"`
	LeadFirstName  string             `json:"lead_first_name"`
	LeadLastName   string             `json:"lead_last_name"`
	LeadAvatarUrl  pgtype.Text        `json:"lead_avatar_url"`
	LeadEmail      string             `json:"lead_email"`
}

func (q *Queries) ListProjectModules(ctx context.Context, arg ListProjectModulesParams) ([]ListProjectModulesRow, error) {
	rows, err := q.db.Query(ctx, listProjectModules,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.LeadID,
		arg.StartAfter,
		arg.EndBefore,
		arg.SortBy,
		arg.SortDir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectModulesRow{}
	for rows.Next() {
		var i ListProjectModulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.LeadID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalTasks,
			&i.CompletedTasks,
			&i.LeadUsername,
			&i.LeadFirstName,
			&i.LeadLastName,
			&i.LeadAvatarUrl,
			&i.LeadEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksNotInModule = `-- name: ListProjectTasksNotInModule :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       p.project_key, ps.name AS state_name, ps.state_type, ps.color AS state_color
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE t.project_id = $1 AND t.deleted_at IS NULL AND t.parent_task_id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM module_tasks mt
      WHERE mt.task_id = t.id AND mt.module_id = $3::uuid
  )
  AND ($4::text IS NULL
       OR t.title ILIKE '%' || $4 || '%')
ORDER BY t.created_at DESC
LIMIT $2
`

type ListProjectTasksNotInModuleParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Limit     int32       `json:"limit"`
	ModuleID  uuid.UUID   `json:"module_id"`
	Search    pgtype.Text `json:"search"`
}

type ListProjectTasksNotInModuleRow struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	TaskNumber int32       `json:"task_number"`
	Title      string      `json:"title"`
	StateID    uuid.UUID   `json:"state_id"`
	Priority   int32       `json:"priority"`
	ProjectKey string      `json:"project_key"`
	StateName  string      `json:"state_name"`
	StateType  string      `json:"state_type"`
	StateColor pgtype.Text `json:"state_color"`
}

// Picker source: project tasks that are NOT already in the given module. A task
// can belong to many modules, so we only exclude by the target module.
func (q *Queries) ListProjectTasksNotInModule(ctx context.Context, arg ListProjectTasksNotInModuleParams) ([]ListProjectTasksNotInModuleRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasksNotInModule,
		arg.ProjectID,
		arg.Limit,
		arg.ModuleID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTasksNotInModuleRow{}
	for rows.Next() {
		var i ListProjectTasksNotInModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeModuleMember = `-- name: RemoveModuleMember :exec
DELETE FROM module_members
WHERE module_id = $1 AND user_id = $2
`

type RemoveModuleMemberParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveModuleMember(ctx context.Context, arg RemoveModuleMemberParams) error {
	_, err := q.db.Exec(ctx, removeModuleMember, arg.ModuleID, arg.UserID)
	return err
}

const removeModuleTask = `-- name: RemoveModuleTask :exec
DELETE FROM module_tasks
WHERE module_id = $1 AND task_id = $2
`

type RemoveModuleTaskParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	TaskID   uuid.UUID `json:"task_id"`
}

func (q *Queries) RemoveModuleTask(ctx context.Context, arg RemoveModuleTaskParams) error {
	_, err := q.db.Exec(ctx, removeModuleTask, arg.ModuleID, arg.TaskID)
	return err
}

const softDeleteModule = `-- name: SoftDeleteModule :exec
UPDATE modules
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteModule, id)
	return err
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET title       = COALESCE($2,       title),
    description = COALESCE($3, description),
    status      = CASE
                    WHEN $4::text = '' THEN status
                    ELSE $4::module_status
                  END,
    start_date  = CASE
                    WHEN $5::bool THEN NULL
                    ELSE COALESCE($6, start_date)
                  END,
    end_date    = CASE
                    WHEN $7::bool THEN NULL
                    ELSE COALESCE($8, end_date)
                  END,
    lead_id     = CASE
                    WHEN $9::bool THEN NULL
                    ELSE COALESCE($10, lead_id)
                  END,
    updated_at  = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, title, description, status, start_date, end_date,
          lead_id, created_by, created_at, updated_at, deleted_at
`

type UpdateModuleParams struct {
	ID             uuid.UUID   `json:"id"`
	Title          pgtype.Text `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	ClearStartDate bool        `json:"clear_start_date"`
	StartDate      pgtype.Date `json:"start_date"`
	ClearEndDate   bool        `json:"clear_end_date"`
	EndDate        pgtype.Date `json:"end_date"`
	ClearLead      bool        `json:"clear_lead"`
	LeadID         pgtype.UUID `json:"lead_id"`
}

// `status` is passed as plain text; when empty string, no change. Avoids narg
// around the enum type under the string override.
func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ClearStartDate,
		arg.StartDate,
		arg.ClearEndDate,
		arg.EndDate,
		arg.ClearLead,
		arg.LeadID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.LeadID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
