// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimEmailNotifications = `-- name: ClaimEmailNotifications :many

UPDATE notifications n
SET emailed_at = NOW()
FROM users r, users a, tasks t, projects p, project_states s
WHERE n.emailed_at IS NULL
  AND n.created_at <= $1
  AND n.read_at IS NULL
  AND r.id = n.recipient_id
  AND r.email_notifications
  AND a.id = n.actor_id
  AND t.id = n.task_id
  AND t.deleted_at IS NULL
  AND p.id = t.project_id
  AND s.id = t.state_id
RETURNING n.id, n.task_id, n.recipient_id, n.activity_type, n.comment_id, n.event_count, n.created_at, n.updated_at,
          r.email AS recipient_email,
          a.first_name AS actor_first_name, a.last_name AS actor_last_name,
          t.task_number, t.title AS task_title,
          p.project_key, p.name AS project_name,
          s.name AS state_name, s.color AS state_color
`

type ClaimEmailNotificationsRow struct {
	ID             uuid.UUID          `json:"id"`
	TaskID         uuid.UUID          `json:"task_id"`
	RecipientID    uuid.UUID          `json:"recipient_id"`
	ActivityType   string             `json:"activity_type"`
	CommentID      pgtype.UUID        `json:"comment_id"`
	EventCount     int32              `json:"event_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RecipientEmail string             `json:"recipient_email"`
	ActorFirstName string             `json:"actor_first_name"`
	ActorLastName  string             `json:"actor_last_name"`
	TaskNumber     int32              `json:"task_number"`
	TaskTitle      string             `json:"task_title"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	StateName      string             `json:"state_name"`
	StateColor     pgtype.Text        `json:"state_color"`
}

// ==================== EMAIL DIGEST ====================
// Claim unread notifications whose coalescing window has closed, for opted-in
// recipients, marking them emailed. Atomic, so concurrent workers never double-send.
func (q *Queries) ClaimEmailNotifications(ctx context.Context, cutoff pgtype.Timestamptz) ([]ClaimEmailNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimEmailNotifications, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimEmailNotificationsRow{}
	for rows.Next() {
		var i ClaimEmailNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RecipientID,
			&i.ActivityType,
			&i.CommentID,
			&i.EventCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientEmail,
			&i.ActorFirstName,
			&i.ActorLastName,
			&i.TaskNumber,
			&i.TaskTitle,
			&i.ProjectKey,
			&i.ProjectName,
			&i.StateName,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coalesceNotification = `-- name: CoalesceNotification :exec
UPDATE notifications
SET event_count   = event_count + 1,
    activity_type = $1,
    actor_id      = $2,
    comment_id    = $3,
    read_at       = NULL,
    updated_at    = NOW()
WHERE id = $4
`

type CoalesceNotificationParams struct {
	ActivityType string      `json:"activity_type"`
	ActorID      uuid.UUID   `json:"actor_id"`
	CommentID    pgtype.UUID `json:"comment_id"`
	ID           uuid.UUID   `json:"id"`
}

// Merge a new activity into an existing open notification: bump the count,
// update the latest actor/type/comment, and re-surface as unread.
func (q *Queries) CoalesceNotification(ctx context.Context, arg CoalesceNotificationParams) error {
	_, err := q.db.Exec(ctx, coalesceNotification,
		arg.ActivityType,
		arg.ActorID,
		arg.CommentID,
		arg.ID,
	)
	return err
}

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)
FROM notifications n
JOIN tasks t ON n.task_id = t.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
`

func (q *Queries) CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)
FROM notifications n
JOIN tasks t ON n.task_id = t.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
  AND n.read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (recipient_id, task_id, activity_type, actor_id, comment_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipient_id, task_id, activity_type, actor_id, event_count, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	RecipientID  uuid.UUID   `json:"recipient_id"`
	TaskID       uuid.UUID   `json:"task_id"`
	ActivityType string      `json:"activity_type"`
	ActorID      uuid.UUID   `json:"actor_id"`
	CommentID    pgtype.UUID `json:"comment_id"`
}

type CreateNotificationRow struct {
	ID           uuid.UUID          `json:"id"`
	RecipientID  uuid.UUID          `json:"recipient_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.TaskID,
		arg.ActivityType,
		arg.ActorID,
		arg.CommentID,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.EventCount,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM notifications
WHERE recipient_id = $1
`

func (q *Queries) DeleteAllNotifications(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications, recipientID)
	return err
}

const getOpenNotification = `-- name: GetOpenNotification :one

SELECT id, recipient_id, task_id, activity_type, actor_id, event_count, read_at, created_at, updated_at
FROM notifications
WHERE recipient_id = $1
  AND task_id = $2
  AND created_at > $3
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenNotificationParams struct {
	RecipientID uuid.UUID          `json:"recipient_id"`
	TaskID      uuid.UUID          `json:"task_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
}

type GetOpenNotificationRow struct {
	ID           uuid.UUID          `json:"id"`
	RecipientID  uuid.UUID          `json:"recipient_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// ==================== NOTIFICATIONS ====================
// Most recent notification for a (recipient, task) pair still within the
// coalescing window. Used to merge new activity into an existing notification
// instead of creating a new one (max 1 notification per task per window).
func (q *Queries) GetOpenNotification(ctx context.Context, arg GetOpenNotificationParams) (GetOpenNotificationRow, error) {
	row := q.db.QueryRow(ctx, getOpenNotification, arg.RecipientID, arg.TaskID, arg.Cutoff)
	var i GetOpenNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.EventCount,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEmailNotifications = `-- name: GetUserEmailNotifications :one
SELECT email_notifications FROM users WHERE id = $1
`

func (q *Queries) GetUserEmailNotifications(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getUserEmailNotifications, id)
	var email_notifications bool
	err := row.Scan(&email_notifications)
	return email_notifications, err
}

const listEmailActivity = `-- name: ListEmailActivity :many
SELECT al.activity_type, al.field_name, al.old_value, al.new_value, u.first_name, u.last_name
FROM activity_log al
JOIN users u ON u.id = al.actor_id
WHERE al.task_id = $1
  AND al.actor_id <> $2
  AND al.created_at >= $3
  AND al.created_at <= $4
ORDER BY al.created_at ASC
LIMIT 20
`

type ListEmailActivityParams struct {
	TaskID      uuid.UUID          `json:"task_id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListEmailActivityRow struct {
	ActivityType string      `json:"activity_type"`
	FieldName    pgtype.Text `json:"field_name"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
}

// The activity batched into one notification: other users' changes to the task
// within the notification's lifetime, oldest first.
func (q *Queries) ListEmailActivity(ctx context.Context, arg ListEmailActivityParams) ([]ListEmailActivityRow, error) {
	rows, err := q.db.Query(ctx, listEmailActivity,
		arg.TaskID,
		arg.RecipientID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailActivityRow{}
	for rows.Next() {
		var i ListEmailActivityRow
		if err := rows.Scan(
			&i.ActivityType,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.task_id, n.activity_type, n.actor_id, n.comment_id, n.event_count, n.read_at, n.created_at, n.updated_at,
       u.username, u.first_name, u.last_name, u.avatar_url,
       t.task_number, t.title AS task_title, p.project_key
FROM notifications n
JOIN users u ON n.actor_id = u.id
JOIN tasks t ON n.task_id = t.id
JOIN projects p ON t.project_id = p.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
ORDER BY n.created_at DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Offset      int32     `json:"offset"`
	Limit       int32     `json:"limit"`
}

type ListNotificationsRow struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	CommentID    pgtype.UUID        `json:"comment_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	TaskNumber   int32              `json:"task_number"`
	TaskTitle    string             `json:"task_title"`
	ProjectKey   string             `json:"project_key"`
}

// A recipient's notifications, newest first, with task/project/actor display fields.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.CommentID,
			&i.EventCount,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.TaskNumber,
			&i.TaskTitle,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE id = $1
  AND recipient_id = $2
  AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	return err
}

const skipEmailNotifications = `-- name: SkipEmailNotifications :exec
UPDATE notifications
SET emailed_at = NOW()
WHERE emailed_at IS NULL
  AND created_at <= $1
`

// Mark the remaining closed-window rows processed so they are never emailed later.
func (q *Queries) SkipEmailNotifications(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, skipEmailNotifications, cutoff)
	return err
}

const updateUserEmailNotifications = `-- name: UpdateUserEmailNotifications :exec
UPDATE users
SET email_notifications = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailNotificationsParams struct {
	ID                 uuid.UUID `json:"id"`
	EmailNotifications bool      `json:"email_notifications"`
}

func (q *Queries) UpdateUserEmailNotifications(ctx context.Context, arg UpdateUserEmailNotificationsParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailNotifications, arg.ID, arg.EmailNotifications)
	return err
}
