// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const coalesceNotification = `-- name: CoalesceNotification :exec
UPDATE notifications
SET event_count   = event_count + 1,
    activity_type = $1,
    actor_id      = $2,
    comment_id    = $3,
    read_at       = NULL,
    updated_at    = NOW()
WHERE id = $4
`

type CoalesceNotificationParams struct {
	ActivityType string      `json:"activity_type"`
	ActorID      uuid.UUID   `json:"actor_id"`
	CommentID    pgtype.UUID `json:"comment_id"`
	ID           uuid.UUID   `json:"id"`
}

// Merge a new activity into an existing open notification: bump the count,
// update the latest actor/type/comment, and re-surface as unread.
func (q *Queries) CoalesceNotification(ctx context.Context, arg CoalesceNotificationParams) error {
	_, err := q.db.Exec(ctx, coalesceNotification,
		arg.ActivityType,
		arg.ActorID,
		arg.CommentID,
		arg.ID,
	)
	return err
}

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)
FROM notifications n
JOIN tasks t ON n.task_id = t.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
`

func (q *Queries) CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)
FROM notifications n
JOIN tasks t ON n.task_id = t.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
  AND n.read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (recipient_id, task_id, activity_type, actor_id, comment_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipient_id, task_id, activity_type, actor_id, event_count, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	RecipientID  uuid.UUID   `json:"recipient_id"`
	TaskID       uuid.UUID   `json:"task_id"`
	ActivityType string      `json:"activity_type"`
	ActorID      uuid.UUID   `json:"actor_id"`
	CommentID    pgtype.UUID `json:"comment_id"`
}

type CreateNotificationRow struct {
	ID           uuid.UUID          `json:"id"`
	RecipientID  uuid.UUID          `json:"recipient_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.TaskID,
		arg.ActivityType,
		arg.ActorID,
		arg.CommentID,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.EventCount,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM notifications
WHERE recipient_id = $1
`

func (q *Queries) DeleteAllNotifications(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications, recipientID)
	return err
}

const getOpenNotification = `-- name: GetOpenNotification :one

SELECT id, recipient_id, task_id, activity_type, actor_id, event_count, read_at, created_at, updated_at
FROM notifications
WHERE recipient_id = $1
  AND task_id = $2
  AND created_at > $3
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenNotificationParams struct {
	RecipientID uuid.UUID          `json:"recipient_id"`
	TaskID      uuid.UUID          `json:"task_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
}

type GetOpenNotificationRow struct {
	ID           uuid.UUID          `json:"id"`
	RecipientID  uuid.UUID          `json:"recipient_id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// ==================== NOTIFICATIONS ====================
// Most recent notification for a (recipient, task) pair still within the
// coalescing window. Used to merge new activity into an existing notification
// instead of creating a new one (max 1 notification per task per window).
func (q *Queries) GetOpenNotification(ctx context.Context, arg GetOpenNotificationParams) (GetOpenNotificationRow, error) {
	row := q.db.QueryRow(ctx, getOpenNotification, arg.RecipientID, arg.TaskID, arg.Cutoff)
	var i GetOpenNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.EventCount,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.task_id, n.activity_type, n.actor_id, n.comment_id, n.event_count, n.read_at, n.created_at, n.updated_at,
       u.username, u.first_name, u.last_name, u.avatar_url,
       t.task_number, t.title AS task_title, p.project_key
FROM notifications n
JOIN users u ON n.actor_id = u.id
JOIN tasks t ON n.task_id = t.id
JOIN projects p ON t.project_id = p.id
WHERE n.recipient_id = $1
  AND t.deleted_at IS NULL
ORDER BY n.created_at DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Offset      int32     `json:"offset"`
	Limit       int32     `json:"limit"`
}

type ListNotificationsRow struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	CommentID    pgtype.UUID        `json:"comment_id"`
	EventCount   int32              `json:"event_count"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	TaskNumber   int32              `json:"task_number"`
	TaskTitle    string             `json:"task_title"`
	ProjectKey   string             `json:"project_key"`
}

// A recipient's notifications, newest first, with task/project/actor display fields.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.CommentID,
			&i.EventCount,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.TaskNumber,
			&i.TaskTitle,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE recipient_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE id = $1
  AND recipient_id = $2
  AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	return err
}
