// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (project_id, page_number, title, content, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, page_number, title, content, created_by, created_at, updated_at, deleted_at
`

type CreatePageParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	PageNumber int32     `json:"page_number"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedBy  uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.ProjectID,
		arg.PageNumber,
		arg.Title,
		arg.Content,
		arg.CreatedBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PageNumber,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNextPageNumber = `-- name: GetNextPageNumber :one
SELECT COALESCE(MAX(page_number), 0) + 1 AS next_number
FROM pages
WHERE project_id = $1
`

func (q *Queries) GetNextPageNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPageNumber, projectID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getPageByProjectAndNumber = `-- name: GetPageByProjectAndNumber :one
SELECT p.id, p.project_id, p.page_number, p.title, p.content, p.created_by, p.created_at, p.updated_at, p.deleted_at,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name, u.avatar_url as creator_avatar_url
FROM pages p
JOIN users u ON p.created_by = u.id
WHERE p.project_id = $1 AND p.page_number = $2 AND p.deleted_at IS NULL
`

type GetPageByProjectAndNumberParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	PageNumber int32     `json:"page_number"`
}

type GetPageByProjectAndNumberRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	PageNumber       int32              `json:"page_number"`
	Title            string             `json:"title"`
	Content          string             `json:"content"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
}

func (q *Queries) GetPageByProjectAndNumber(ctx context.Context, arg GetPageByProjectAndNumberParams) (GetPageByProjectAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getPageByProjectAndNumber, arg.ProjectID, arg.PageNumber)
	var i GetPageByProjectAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PageNumber,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatorUsername,
		&i.CreatorFirstName,
		&i.CreatorLastName,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const listProjectPages = `-- name: ListProjectPages :many
SELECT p.id, p.project_id, p.page_number, p.title, p.created_by, p.created_at, p.updated_at,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name, u.avatar_url as creator_avatar_url
FROM pages p
JOIN users u ON p.created_by = u.id
WHERE p.project_id = $1 AND p.deleted_at IS NULL
ORDER BY p.updated_at DESC
`

type ListProjectPagesRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	PageNumber       int32              `json:"page_number"`
	Title            string             `json:"title"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
}

func (q *Queries) ListProjectPages(ctx context.Context, projectID uuid.UUID) ([]ListProjectPagesRow, error) {
	rows, err := q.db.Query(ctx, listProjectPages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPagesRow{}
	for rows.Next() {
		var i ListProjectPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PageNumber,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorUsername,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePage = `-- name: SoftDeletePage :exec
UPDATE pages
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePage, id)
	return err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, page_number, title, content, created_by, created_at, updated_at, deleted_at
`

type UpdatePageParams struct {
	ID      uuid.UUID   `json:"id"`
	Title   pgtype.Text `json:"title"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage, arg.ID, arg.Title, arg.Content)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PageNumber,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
