// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGlobalPreference = `-- name: DeleteGlobalPreference :exec
DELETE FROM user_preferences
WHERE user_id = $1 AND preference_key = $2
  AND workspace_id IS NULL AND project_id IS NULL
`

type DeleteGlobalPreferenceParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PreferenceKey string    `json:"preference_key"`
}

func (q *Queries) DeleteGlobalPreference(ctx context.Context, arg DeleteGlobalPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteGlobalPreference, arg.UserID, arg.PreferenceKey)
	return err
}

const deleteProjectPreference = `-- name: DeleteProjectPreference :exec
DELETE FROM user_preferences
WHERE user_id = $1 AND preference_key = $2 AND project_id = $3
`

type DeleteProjectPreferenceParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	PreferenceKey string      `json:"preference_key"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteProjectPreference(ctx context.Context, arg DeleteProjectPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteProjectPreference, arg.UserID, arg.PreferenceKey, arg.ProjectID)
	return err
}

const listGlobalPreferences = `-- name: ListGlobalPreferences :many

SELECT preference_key, value, value_version, revision, updated_at
FROM user_preferences
WHERE user_id = $1
  AND workspace_id IS NULL
  AND project_id IS NULL
`

type ListGlobalPreferencesRow struct {
	PreferenceKey string             `json:"preference_key"`
	Value         []byte             `json:"value"`
	ValueVersion  int32              `json:"value_version"`
	Revision      int64              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// ==================== USER PREFERENCES ====================
//
// Rows hold only user overrides; a missing row means "use the registry
// default". Reads return the whole set for a scope so the API can fold in
// defaults. Writes are revision-aware (optimistic concurrency): the caller
// passes the revision it last saw, and the update only applies when the stored
// revision still matches. A brand-new row is created at revision 1 regardless.
func (q *Queries) ListGlobalPreferences(ctx context.Context, userID uuid.UUID) ([]ListGlobalPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listGlobalPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalPreferencesRow{}
	for rows.Next() {
		var i ListGlobalPreferencesRow
		if err := rows.Scan(
			&i.PreferenceKey,
			&i.Value,
			&i.ValueVersion,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPreferences = `-- name: ListProjectPreferences :many
SELECT preference_key, value, value_version, revision, updated_at
FROM user_preferences
WHERE user_id = $1
  AND project_id = $2
`

type ListProjectPreferencesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type ListProjectPreferencesRow struct {
	PreferenceKey string             `json:"preference_key"`
	Value         []byte             `json:"value"`
	ValueVersion  int32              `json:"value_version"`
	Revision      int64              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProjectPreferences(ctx context.Context, arg ListProjectPreferencesParams) ([]ListProjectPreferencesRow, error) {
	rows, err := q.db.Query(ctx, listProjectPreferences, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPreferencesRow{}
	for rows.Next() {
		var i ListProjectPreferencesRow
		if err := rows.Scan(
			&i.PreferenceKey,
			&i.Value,
			&i.ValueVersion,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalPreference = `-- name: UpsertGlobalPreference :one
INSERT INTO user_preferences (user_id, preference_key, value, value_version, revision)
VALUES ($1, $2, $3, $4, 1)
ON CONFLICT (user_id, preference_key) WHERE workspace_id IS NULL AND project_id IS NULL
DO UPDATE SET
    value = EXCLUDED.value,
    value_version = EXCLUDED.value_version,
    revision = user_preferences.revision + 1,
    updated_at = NOW()
WHERE user_preferences.revision = $5
RETURNING preference_key, value, value_version, revision, updated_at
`

type UpsertGlobalPreferenceParams struct {
	UserID           uuid.UUID `json:"user_id"`
	PreferenceKey    string    `json:"preference_key"`
	Value            []byte    `json:"value"`
	ValueVersion     int32     `json:"value_version"`
	ExpectedRevision int64     `json:"expected_revision"`
}

type UpsertGlobalPreferenceRow struct {
	PreferenceKey string             `json:"preference_key"`
	Value         []byte             `json:"value"`
	ValueVersion  int32              `json:"value_version"`
	Revision      int64              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// On a matching revision the row is bumped; on a stale revision no row is
// returned (the handler maps that to 409). A first write (no existing row)
// inserts at revision 1.
func (q *Queries) UpsertGlobalPreference(ctx context.Context, arg UpsertGlobalPreferenceParams) (UpsertGlobalPreferenceRow, error) {
	row := q.db.QueryRow(ctx, upsertGlobalPreference,
		arg.UserID,
		arg.PreferenceKey,
		arg.Value,
		arg.ValueVersion,
		arg.ExpectedRevision,
	)
	var i UpsertGlobalPreferenceRow
	err := row.Scan(
		&i.PreferenceKey,
		&i.Value,
		&i.ValueVersion,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectPreference = `-- name: UpsertProjectPreference :one
INSERT INTO user_preferences (user_id, preference_key, project_id, value, value_version, revision)
VALUES ($1, $2, $3, $4, $5, 1)
ON CONFLICT (user_id, preference_key, project_id) WHERE project_id IS NOT NULL
DO UPDATE SET
    value = EXCLUDED.value,
    value_version = EXCLUDED.value_version,
    revision = user_preferences.revision + 1,
    updated_at = NOW()
WHERE user_preferences.revision = $6
RETURNING preference_key, value, value_version, revision, updated_at
`

type UpsertProjectPreferenceParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	PreferenceKey    string      `json:"preference_key"`
	ProjectID        pgtype.UUID `json:"project_id"`
	Value            []byte      `json:"value"`
	ValueVersion     int32       `json:"value_version"`
	ExpectedRevision int64       `json:"expected_revision"`
}

type UpsertProjectPreferenceRow struct {
	PreferenceKey string             `json:"preference_key"`
	Value         []byte             `json:"value"`
	ValueVersion  int32              `json:"value_version"`
	Revision      int64              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProjectPreference(ctx context.Context, arg UpsertProjectPreferenceParams) (UpsertProjectPreferenceRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectPreference,
		arg.UserID,
		arg.PreferenceKey,
		arg.ProjectID,
		arg.Value,
		arg.ValueVersion,
		arg.ExpectedRevision,
	)
	var i UpsertProjectPreferenceRow
	err := row.Scan(
		&i.PreferenceKey,
		&i.Value,
		&i.ValueVersion,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}
