// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one

INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, role, joined_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

// ==================== PROJECT MEMBERS ====================
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const addProjectMembersToWorkspace = `-- name: AddProjectMembersToWorkspace :exec
INSERT INTO workspace_members (workspace_id, user_id)
SELECT $1, pm.user_id
FROM project_members pm
WHERE pm.project_id = $2
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type AddProjectMembersToWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
}

// Adds every member of the project as a member of the workspace, skipping any
// who are already members. Used when moving a project to keep members' access.
func (q *Queries) AddProjectMembersToWorkspace(ctx context.Context, arg AddProjectMembersToWorkspaceParams) error {
	_, err := q.db.Exec(ctx, addProjectMembersToWorkspace, arg.WorkspaceID, arg.ProjectID)
	return err
}

const addTaskAssignee = `-- name: AddTaskAssignee :one

INSERT INTO task_assignees (task_id, user_id, assigned_by)
VALUES ($1, $2, $3)
RETURNING id, task_id, user_id, assigned_at, assigned_by
`

type AddTaskAssigneeParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

// ==================== TASK ASSIGNEES ====================
func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error) {
	row := q.db.QueryRow(ctx, addTaskAssignee, arg.TaskID, arg.UserID, arg.AssignedBy)
	var i TaskAssignee
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.AssignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const addTaskLabel = `-- name: AddTaskLabel :exec

INSERT INTO task_labels (task_id, label_id, added_by)
VALUES ($1, $2, $3)
`

type AddTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
	AddedBy uuid.UUID `json:"added_by"`
}

// ==================== TASK LABELS ====================
func (q *Queries) AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error {
	_, err := q.db.Exec(ctx, addTaskLabel, arg.TaskID, arg.LabelID, arg.AddedBy)
	return err
}

const cascadeSoftDeleteSubtasks = `-- name: CascadeSoftDeleteSubtasks :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE parent_task_id = $1::uuid AND deleted_at IS NULL
`

// Soft-delete all children of a task (cascade-together on parent delete).
func (q *Queries) CascadeSoftDeleteSubtasks(ctx context.Context, parentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cascadeSoftDeleteSubtasks, parentID)
	return err
}

const countAllProjects = `-- name: CountAllProjects :one
SELECT COUNT(*)
FROM projects p
WHERE p.deleted_at IS NULL
`

func (q *Queries) CountAllProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProjectsFiltered = `-- name: CountAllProjectsFiltered :one
SELECT COUNT(*)
FROM projects p
WHERE p.deleted_at IS NULL
  AND ($1::uuid IS NULL OR p.workspace_id = $1)
  AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.project_key ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
`

type CountAllProjectsFilteredParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Search      pgtype.Text `json:"search"`
}

func (q *Queries) CountAllProjectsFiltered(ctx context.Context, arg CountAllProjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProjectsFiltered, arg.WorkspaceID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT COUNT(*) FROM project_members WHERE project_id = $1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectTasks = `-- name: CountProjectTasks :one
SELECT COUNT(*)
FROM tasks
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTasks, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTaskComments = `-- name: CountTaskComments :one
SELECT COUNT(*) FROM comments WHERE task_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTaskComments(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskComments, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByAssignee = `-- name: CountTasksByAssignee :one
SELECT COUNT(*)
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN task_assignees ta ON t.id = ta.task_id
WHERE ta.user_id = $1 AND t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND ps.state_type NOT IN ('completed', 'cancelled')
  AND ($2::uuid IS NULL OR p.workspace_id = $2)
`

type CountTasksByAssigneeParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CountTasksByAssignee(ctx context.Context, arg CountTasksByAssigneeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByAssignee, arg.UserID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksInState = `-- name: CountTasksInState :one
SELECT COUNT(*) FROM tasks WHERE state_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksInState(ctx context.Context, stateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksInState, stateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserActivity = `-- name: CountUserActivity :one
SELECT (
  (SELECT COUNT(*) FROM activity_log al1 WHERE al1.actor_id = $1)
  +
  (SELECT COUNT(*) FROM tasks t
   WHERE t.created_by = $1 AND t.deleted_at IS NULL
   AND NOT EXISTS (
     SELECT 1 FROM activity_log al2
     WHERE al2.task_id = t.id AND al2.actor_id = $1 AND al2.activity_type = 'task_created'
   ))
)::bigint
`

func (q *Queries) CountUserActivity(ctx context.Context, actorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivity, actorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserProjects = `-- name: CountUserProjects :one
SELECT COUNT(*)
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) CountUserProjects(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProjects, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserProjectsFiltered = `-- name: CountUserProjectsFiltered :one
SELECT COUNT(*)
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR p.workspace_id = $2)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3 || '%' OR p.project_key ILIKE '%' || $3 || '%' OR p.description ILIKE '%' || $3 || '%')
`

type CountUserProjectsFilteredParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Search      pgtype.Text `json:"search"`
}

func (q *Queries) CountUserProjectsFiltered(ctx context.Context, arg CountUserProjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProjectsFiltered, arg.UserID, arg.WorkspaceID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one

INSERT INTO activity_log (task_id, activity_type, actor_id, field_name, old_value, new_value, checksum, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, activity_type, actor_id, field_name, old_value, new_value, created_at, checksum
`

type CreateActivityLogParams struct {
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	Checksum     string             `json:"checksum"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// ==================== ACTIVITY LOG ====================
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.TaskID,
		arg.ActivityType,
		arg.ActorID,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Checksum,
		arg.CreatedAt,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
		&i.Checksum,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (task_id, content, created_by)
VALUES ($1, $2, $3)
RETURNING id, task_id, content, version, created_by, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	TaskID    uuid.UUID `json:"task_id"`
	Content   string    `json:"content"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// ==================== COMMENTS ====================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.Content, arg.CreatedBy)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (project_key, name, description, icon_id, cover_id, created_by, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
`

type CreateProjectParams struct {
	ProjectKey  string      `json:"project_key"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
	CoverID     pgtype.UUID `json:"cover_id"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

// ==================== PROJECTS ====================
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectKey,
		arg.Name,
		arg.Description,
		arg.IconID,
		arg.CoverID,
		arg.CreatedBy,
		arg.WorkspaceID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const createProjectLabel = `-- name: CreateProjectLabel :one

INSERT INTO project_labels (project_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, color, created_at
`

type CreateProjectLabelParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
}

// ==================== PROJECT LABELS ====================
func (q *Queries) CreateProjectLabel(ctx context.Context, arg CreateProjectLabelParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, createProjectLabel, arg.ProjectID, arg.Name, arg.Color)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectState = `-- name: CreateProjectState :one

INSERT INTO project_states (project_id, state_type, name, color, position, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, state_type, name, color, position, is_default, created_at
`

type CreateProjectStateParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	StateType string      `json:"state_type"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	Position  int32       `json:"position"`
	IsDefault bool        `json:"is_default"`
}

// ==================== PROJECT STATES ====================
func (q *Queries) CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, createProjectState,
		arg.ProjectID,
		arg.StateType,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.IsDefault,
	)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (project_id, task_number, title, description, state_id, priority, created_by, start_date, due_date, parent_task_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, task_number, title, description, state_id, priority, created_by, start_date, due_date, parent_task_id, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProjectID    uuid.UUID          `json:"project_id"`
	TaskNumber   int32              `json:"task_number"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StateID      uuid.UUID          `json:"state_id"`
	Priority     int32              `json:"priority"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
}

type CreateTaskRow struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	TaskNumber   int32              `json:"task_number"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StateID      uuid.UUID          `json:"state_id"`
	Priority     int32              `json:"priority"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// ==================== TASKS ====================
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.TaskNumber,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.Priority,
		arg.CreatedBy,
		arg.StartDate,
		arg.DueDate,
		arg.ParentTaskID,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.StartDate,
		&i.DueDate,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskTemplate = `-- name: CreateTaskTemplate :one

INSERT INTO task_templates (project_id, name, title, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, title, description, created_by, created_at, updated_at
`

type CreateTaskTemplateParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

// ==================== TASK TEMPLATES ====================
func (q *Queries) CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, createTaskTemplate,
		arg.ProjectID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectLabel = `-- name: DeleteProjectLabel :exec
DELETE FROM project_labels WHERE id = $1
`

func (q *Queries) DeleteProjectLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectLabel, id)
	return err
}

const deleteProjectState = `-- name: DeleteProjectState :exec
DELETE FROM project_states WHERE id = $1
`

func (q *Queries) DeleteProjectState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectState, id)
	return err
}

const deleteTaskCycleLinks = `-- name: DeleteTaskCycleLinks :exec
DELETE FROM cycle_tasks WHERE task_id = $1
`

func (q *Queries) DeleteTaskCycleLinks(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskCycleLinks, taskID)
	return err
}

const deleteTaskModuleLinks = `-- name: DeleteTaskModuleLinks :exec
DELETE FROM module_tasks WHERE task_id = $1
`

func (q *Queries) DeleteTaskModuleLinks(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskModuleLinks, taskID)
	return err
}

const deleteTaskTemplate = `-- name: DeleteTaskTemplate :exec
DELETE FROM task_templates WHERE id = $1
`

func (q *Queries) DeleteTaskTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTemplate, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.task_id, c.content, c.version, c.created_by, c.created_at, c.updated_at, c.deleted_at,
       u.username, u.first_name, u.last_name, u.avatar_url
FROM comments c
JOIN users u ON c.created_by = u.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCommentByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  string             `json:"username"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
	)
	return i, err
}

const getDefaultProjectState = `-- name: GetDefaultProjectState :one
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultProjectState(ctx context.Context, projectID uuid.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getDefaultProjectState, projectID)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getLastActivityChecksum = `-- name: GetLastActivityChecksum :one
SELECT checksum
FROM activity_log
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastActivityChecksum(ctx context.Context, taskID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastActivityChecksum, taskID)
	var checksum string
	err := row.Scan(&checksum)
	return checksum, err
}

const getNextTaskNumber = `-- name: GetNextTaskNumber :one
SELECT COALESCE(MAX(task_number), 0) + 1 AS next_number
FROM tasks
WHERE project_id = $1
`

func (q *Queries) GetNextTaskNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextTaskNumber, projectID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
FROM projects
WHERE project_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByKey(ctx context.Context, projectKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, projectKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const getProjectLabelByID = `-- name: GetProjectLabelByID :one
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE id = $1
`

func (q *Queries) GetProjectLabelByID(ctx context.Context, id uuid.UUID) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, getProjectLabelByID, id)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectLabelByProjectAndName = `-- name: GetProjectLabelByProjectAndName :one
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetProjectLabelByProjectAndNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetProjectLabelByProjectAndName(ctx context.Context, arg GetProjectLabelByProjectAndNameParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, getProjectLabelByProjectAndName, arg.ProjectID, arg.Name)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.joined_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1 AND pm.user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetProjectMemberRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i GetProjectMemberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getProjectStateByID = `-- name: GetProjectStateByID :one
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE id = $1
`

func (q *Queries) GetProjectStateByID(ctx context.Context, id uuid.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByID, id)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectStateByProjectAndName = `-- name: GetProjectStateByProjectAndName :one

SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetProjectStateByProjectAndNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

// ==================== IMPORT HELPERS ====================
func (q *Queries) GetProjectStateByProjectAndName(ctx context.Context, arg GetProjectStateByProjectAndNameParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByProjectAndName, arg.ProjectID, arg.Name)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskAttachEligibility = `-- name: GetTaskAttachEligibility :one
SELECT t.id, t.project_id,
       (SELECT COUNT(*) FROM tasks c WHERE c.parent_task_id = t.id AND c.deleted_at IS NULL)::int AS subtask_count
FROM tasks t
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTaskAttachEligibilityRow struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	SubtaskCount int32     `json:"subtask_count"`
}

// Validates a candidate before attaching it as a subtask: its project and
// whether it already has children (which would break the one-level rule).
func (q *Queries) GetTaskAttachEligibility(ctx context.Context, id uuid.UUID) (GetTaskAttachEligibilityRow, error) {
	row := q.db.QueryRow(ctx, getTaskAttachEligibility, id)
	var i GetTaskAttachEligibilityRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.SubtaskCount)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.start_date, t.due_date, t.parent_task_id, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name, u.avatar_url as creator_avatar_url,
       pt.task_number as parent_task_number, pt.title as parent_task_title,
       (SELECT COUNT(*) FROM tasks st WHERE st.parent_task_id = t.id AND st.deleted_at IS NULL)::bigint as subtask_count
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
LEFT JOIN tasks pt ON t.parent_task_id = pt.id AND pt.deleted_at IS NULL
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTaskByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	TaskNumber       int32              `json:"task_number"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StateID          uuid.UUID          `json:"state_id"`
	Priority         int32              `json:"priority"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	ParentTaskID     pgtype.UUID        `json:"parent_task_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey       string             `json:"project_key"`
	StateName        string             `json:"state_name"`
	StateType        string             `json:"state_type"`
	StateColor       pgtype.Text        `json:"state_color"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
	ParentTaskNumber pgtype.Int4        `json:"parent_task_number"`
	ParentTaskTitle  pgtype.Text        `json:"parent_task_title"`
	SubtaskCount     int64              `json:"subtask_count"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.StartDate,
		&i.DueDate,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.StateName,
		&i.StateType,
		&i.StateColor,
		&i.CreatorUsername,
		&i.CreatorFirstName,
		&i.CreatorLastName,
		&i.CreatorAvatarUrl,
		&i.ParentTaskNumber,
		&i.ParentTaskTitle,
		&i.SubtaskCount,
	)
	return i, err
}

const getTaskByProjectAndNumber = `-- name: GetTaskByProjectAndNumber :one
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.start_date, t.due_date, t.parent_task_id, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name, u.avatar_url as creator_avatar_url,
       pt.task_number as parent_task_number, pt.title as parent_task_title,
       (SELECT COUNT(*) FROM tasks st WHERE st.parent_task_id = t.id AND st.deleted_at IS NULL)::bigint as subtask_count
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
LEFT JOIN tasks pt ON t.parent_task_id = pt.id AND pt.deleted_at IS NULL
WHERE t.project_id = $1 AND t.task_number = $2 AND t.deleted_at IS NULL
`

type GetTaskByProjectAndNumberParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	TaskNumber int32     `json:"task_number"`
}

type GetTaskByProjectAndNumberRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	TaskNumber       int32              `json:"task_number"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StateID          uuid.UUID          `json:"state_id"`
	Priority         int32              `json:"priority"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	ParentTaskID     pgtype.UUID        `json:"parent_task_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey       string             `json:"project_key"`
	StateName        string             `json:"state_name"`
	StateType        string             `json:"state_type"`
	StateColor       pgtype.Text        `json:"state_color"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	CreatorAvatarUrl pgtype.Text        `json:"creator_avatar_url"`
	ParentTaskNumber pgtype.Int4        `json:"parent_task_number"`
	ParentTaskTitle  pgtype.Text        `json:"parent_task_title"`
	SubtaskCount     int64              `json:"subtask_count"`
}

func (q *Queries) GetTaskByProjectAndNumber(ctx context.Context, arg GetTaskByProjectAndNumberParams) (GetTaskByProjectAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getTaskByProjectAndNumber, arg.ProjectID, arg.TaskNumber)
	var i GetTaskByProjectAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.StartDate,
		&i.DueDate,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.StateName,
		&i.StateType,
		&i.StateColor,
		&i.CreatorUsername,
		&i.CreatorFirstName,
		&i.CreatorLastName,
		&i.CreatorAvatarUrl,
		&i.ParentTaskNumber,
		&i.ParentTaskTitle,
		&i.SubtaskCount,
	)
	return i, err
}

const getTaskTemplateByID = `-- name: GetTaskTemplateByID :one
SELECT id, project_id, name, title, description, created_by, created_at, updated_at FROM task_templates WHERE id = $1
`

func (q *Queries) GetTaskTemplateByID(ctx context.Context, id uuid.UUID) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, getTaskTemplateByID, id)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasTaskLabel = `-- name: HasTaskLabel :one
SELECT EXISTS (
    SELECT 1 FROM task_labels
    WHERE task_id = $1 AND label_id = $2
) AS has_label
`

type HasTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasTaskLabel, arg.TaskID, arg.LabelID)
	var has_label bool
	err := row.Scan(&has_label)
	return has_label, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (
    SELECT 1 FROM project_members
    WHERE project_id = $1 AND user_id = $2
) AS is_member
`

type IsProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isTaskAssignee = `-- name: IsTaskAssignee :one
SELECT EXISTS (
    SELECT 1 FROM task_assignees
    WHERE task_id = $1 AND user_id = $2
) AS is_assignee
`

type IsTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTaskAssignee, arg.TaskID, arg.UserID)
	var is_assignee bool
	err := row.Scan(&is_assignee)
	return is_assignee, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.workspace_id, 'admin' AS role
FROM projects p
WHERE p.deleted_at IS NULL
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type ListAllProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllProjectsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Role        string             `json:"role"`
}

func (q *Queries) ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]ListAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAllProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsRow{}
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkspaceID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProjectsFiltered = `-- name: ListAllProjectsFiltered :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.workspace_id, 'admin' AS role
FROM projects p
WHERE p.deleted_at IS NULL
  AND ($3::uuid IS NULL OR p.workspace_id = $3)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%' OR p.project_key ILIKE '%' || $4 || '%' OR p.description ILIKE '%' || $4 || '%')
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type ListAllProjectsFilteredParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Search      pgtype.Text `json:"search"`
}

type ListAllProjectsFilteredRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Role        string             `json:"role"`
}

func (q *Queries) ListAllProjectsFiltered(ctx context.Context, arg ListAllProjectsFilteredParams) ([]ListAllProjectsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAllProjectsFiltered,
		arg.Limit,
		arg.Offset,
		arg.WorkspaceID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsFilteredRow{}
	for rows.Next() {
		var i ListAllProjectsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkspaceID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssigneesForTasks = `-- name: ListAssigneesForTasks :many

SELECT ta.task_id, ta.id, ta.user_id, ta.assigned_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM task_assignees ta
JOIN users u ON ta.user_id = u.id
WHERE ta.task_id = ANY($1::uuid[])
ORDER BY ta.assigned_at ASC
`

type ListAssigneesForTasksRow struct {
	TaskID     uuid.UUID          `json:"task_id"`
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	Username   string             `json:"username"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	AvatarUrl  pgtype.Text        `json:"avatar_url"`
}

// Filtered list and count are now built dynamically by internal/store/tasks_filter.go
// from a FilterTree. The projection here is documented for reference by that runner.
func (q *Queries) ListAssigneesForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesForTasksRow, error) {
	rows, err := q.db.Query(ctx, listAssigneesForTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssigneesForTasksRow{}
	for rows.Next() {
		var i ListAssigneesForTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.UserID,
			&i.AssignedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForTasks = `-- name: ListLabelsForTasks :many
SELECT tl.task_id, tl.label_id, tl.added_at,
       pl.name, pl.color
FROM task_labels tl
JOIN project_labels pl ON tl.label_id = pl.id
WHERE tl.task_id = ANY($1::uuid[])
ORDER BY pl.name ASC
`

type ListLabelsForTasksRow struct {
	TaskID  uuid.UUID          `json:"task_id"`
	LabelID uuid.UUID          `json:"label_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	Name    string             `json:"name"`
	Color   pgtype.Text        `json:"color"`
}

func (q *Queries) ListLabelsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListLabelsForTasksRow, error) {
	rows, err := q.db.Query(ctx, listLabelsForTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsForTasksRow{}
	for rows.Next() {
		var i ListLabelsForTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LabelID,
			&i.AddedAt,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLabels = `-- name: ListProjectLabels :many
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]ProjectLabel, error) {
	rows, err := q.db.Query(ctx, listProjectLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectLabel{}
	for rows.Next() {
		var i ProjectLabel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.joined_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
ORDER BY pm.joined_at ASC
`

type ListProjectMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembersMissingFromWorkspace = `-- name: ListProjectMembersMissingFromWorkspace :many
SELECT u.id, u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM workspace_members wm
    WHERE wm.workspace_id = $2 AND wm.user_id = pm.user_id
  )
ORDER BY u.first_name ASC, u.last_name ASC
`

type ListProjectMembersMissingFromWorkspaceParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type ListProjectMembersMissingFromWorkspaceRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// Project members who are NOT members of the given workspace. Used to preview
// who would lose visibility of the project when it moves to that workspace.
func (q *Queries) ListProjectMembersMissingFromWorkspace(ctx context.Context, arg ListProjectMembersMissingFromWorkspaceParams) ([]ListProjectMembersMissingFromWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembersMissingFromWorkspace, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersMissingFromWorkspaceRow{}
	for rows.Next() {
		var i ListProjectMembersMissingFromWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStates = `-- name: ListProjectStates :many
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListProjectStates(ctx context.Context, projectID uuid.UUID) ([]ProjectState, error) {
	rows, err := q.db.Query(ctx, listProjectStates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectState{}
	for rows.Next() {
		var i ProjectState
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StateType,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.project_id = $1 AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectTasksParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListProjectTasksRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TaskNumber      int32              `json:"task_number"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	StateID         uuid.UUID          `json:"state_id"`
	Priority        int32              `json:"priority"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey      string             `json:"project_key"`
	StateName       string             `json:"state_name"`
	StateType       string             `json:"state_type"`
	StateColor      pgtype.Text        `json:"state_color"`
	CreatorUsername string             `json:"creator_username"`
}

func (q *Queries) ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTasksRow{}
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.Priority,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.CreatorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtaskCandidates = `-- name: ListSubtaskCandidates :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       p.project_key, ps.name as state_name, ps.state_type, ps.color as state_color,
       pt.task_number AS parent_task_number, pt.title AS parent_title
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
LEFT JOIN tasks pt ON t.parent_task_id = pt.id AND pt.deleted_at IS NULL
WHERE t.project_id = $1 AND t.deleted_at IS NULL
  AND t.id <> $3::uuid
  AND (t.parent_task_id IS DISTINCT FROM $3::uuid)
  AND NOT EXISTS (
      SELECT 1 FROM tasks c
      WHERE c.parent_task_id = t.id AND c.deleted_at IS NULL
  )
  AND ($4::text IS NULL
       OR t.title ILIKE '%' || $4 || '%')
ORDER BY t.created_at DESC
LIMIT $2
`

type ListSubtaskCandidatesParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Limit     int32       `json:"limit"`
	ParentID  uuid.UUID   `json:"parent_id"`
	Search    pgtype.Text `json:"search"`
}

type ListSubtaskCandidatesRow struct {
	ID               uuid.UUID   `json:"id"`
	ProjectID        uuid.UUID   `json:"project_id"`
	TaskNumber       int32       `json:"task_number"`
	Title            string      `json:"title"`
	StateID          uuid.UUID   `json:"state_id"`
	Priority         int32       `json:"priority"`
	ProjectKey       string      `json:"project_key"`
	StateName        string      `json:"state_name"`
	StateType        string      `json:"state_type"`
	StateColor       pgtype.Text `json:"state_color"`
	ParentTaskNumber pgtype.Int4 `json:"parent_task_number"`
	ParentTitle      pgtype.Text `json:"parent_title"`
}

// Picker source for "attach an existing task as a subtask". Returns project
// tasks eligible to become a child of the given parent. Excludes: the parent
// itself, tasks already parented to this same parent, and tasks that already
// have their own children (attaching one would break the one-level rule).
// Tasks parented elsewhere ARE included (they can be re-parented) and flagged
// via has_parent so the UI can warn.
func (q *Queries) ListSubtaskCandidates(ctx context.Context, arg ListSubtaskCandidatesParams) ([]ListSubtaskCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSubtaskCandidates,
		arg.ProjectID,
		arg.Limit,
		arg.ParentID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtaskCandidatesRow{}
	for rows.Next() {
		var i ListSubtaskCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.ParentTaskNumber,
			&i.ParentTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtaskIDsForMove = `-- name: ListSubtaskIDsForMove :many
SELECT t.id, ps.name as state_name
FROM tasks t
JOIN project_states ps ON t.state_id = ps.id
WHERE t.parent_task_id = $1::uuid AND t.deleted_at IS NULL
ORDER BY t.task_number ASC
`

type ListSubtaskIDsForMoveRow struct {
	ID        uuid.UUID `json:"id"`
	StateName string    `json:"state_name"`
}

// Child ids + state name of a task, used to cascade a cross-project move.
func (q *Queries) ListSubtaskIDsForMove(ctx context.Context, parentID uuid.UUID) ([]ListSubtaskIDsForMoveRow, error) {
	rows, err := q.db.Query(ctx, listSubtaskIDsForMove, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtaskIDsForMoveRow{}
	for rows.Next() {
		var i ListSubtaskIDsForMoveRow
		if err := rows.Scan(&i.ID, &i.StateName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       t.created_by, u.first_name as creator_first_name, u.last_name as creator_last_name, u.avatar_url as creator_avatar_url,
       p.project_key, ps.name as state_name, ps.state_type, ps.color as state_color
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.parent_task_id = $1::uuid AND t.deleted_at IS NULL
ORDER BY t.task_number ASC
`

type ListSubtasksRow struct {
	ID               uuid.UUID   `json:"id"`
	ProjectID        uuid.UUID   `json:"project_id"`
	TaskNumber       int32       `json:"task_number"`
	Title            string      `json:"title"`
	StateID          uuid.UUID   `json:"state_id"`
	Priority         int32       `json:"priority"`
	CreatedBy        uuid.UUID   `json:"created_by"`
	CreatorFirstName string      `json:"creator_first_name"`
	CreatorLastName  string      `json:"creator_last_name"`
	CreatorAvatarUrl pgtype.Text `json:"creator_avatar_url"`
	ProjectKey       string      `json:"project_key"`
	StateName        string      `json:"state_name"`
	StateType        string      `json:"state_type"`
	StateColor       pgtype.Text `json:"state_color"`
}

// Direct children of a task, in task-number order. Used on the parent's detail page.
func (q *Queries) ListSubtasks(ctx context.Context, parentID uuid.UUID) ([]ListSubtasksRow, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubtasksRow{}
	for rows.Next() {
		var i ListSubtasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.CreatedBy,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.CreatorAvatarUrl,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT al.id, al.task_id, al.activity_type, al.actor_id, al.field_name, al.old_value, al.new_value, al.created_at, al.checksum,
       u.username, u.first_name, u.last_name, u.avatar_url
FROM activity_log al
JOIN users u ON al.actor_id = u.id
WHERE al.task_id = $1
ORDER BY al.created_at ASC
`

type ListTaskActivityRow struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Checksum     string             `json:"checksum"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListTaskActivity(ctx context.Context, taskID uuid.UUID) ([]ListTaskActivityRow, error) {
	rows, err := q.db.Query(ctx, listTaskActivity, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskActivityRow{}
	for rows.Next() {
		var i ListTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.Checksum,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT ta.id, ta.task_id, ta.user_id, ta.assigned_at, ta.assigned_by,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM task_assignees ta
JOIN users u ON ta.user_id = u.id
WHERE ta.task_id = $1
ORDER BY ta.assigned_at ASC
`

type ListTaskAssigneesRow struct {
	ID         uuid.UUID          `json:"id"`
	TaskID     uuid.UUID          `json:"task_id"`
	UserID     uuid.UUID          `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy uuid.UUID          `json:"assigned_by"`
	Username   string             `json:"username"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	AvatarUrl  pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssigneesRow{}
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT c.id, c.task_id, c.content, c.version, c.created_by, c.created_at, c.updated_at, c.deleted_at,
       u.username, u.first_name, u.last_name, u.avatar_url
FROM comments c
JOIN users u ON c.created_by = u.id
WHERE c.task_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
`

type ListTaskCommentsRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  string             `json:"username"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommentsRow{}
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLabels = `-- name: ListTaskLabels :many
SELECT tl.task_id, tl.label_id, tl.added_at, tl.added_by,
       pl.name, pl.color
FROM task_labels tl
JOIN project_labels pl ON tl.label_id = pl.id
WHERE tl.task_id = $1
ORDER BY pl.name ASC
`

type ListTaskLabelsRow struct {
	TaskID  uuid.UUID          `json:"task_id"`
	LabelID uuid.UUID          `json:"label_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	AddedBy uuid.UUID          `json:"added_by"`
	Name    string             `json:"name"`
	Color   pgtype.Text        `json:"color"`
}

func (q *Queries) ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]ListTaskLabelsRow, error) {
	rows, err := q.db.Query(ctx, listTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskLabelsRow{}
	for rows.Next() {
		var i ListTaskLabelsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LabelID,
			&i.AddedAt,
			&i.AddedBy,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskParticipants = `-- name: ListTaskParticipants :many

SELECT DISTINCT user_id FROM (
  SELECT t.created_by AS user_id
  FROM tasks t
  WHERE t.id = $1 AND t.deleted_at IS NULL

  UNION

  SELECT ta.user_id
  FROM task_assignees ta
  WHERE ta.task_id = $1

  UNION

  SELECT c.created_by AS user_id
  FROM comments c
  WHERE c.task_id = $1 AND c.deleted_at IS NULL
) participants
`

// ==================== TASK PARTICIPANTS ====================
// Everyone involved with a task: its creator, current assignees, and anyone who
// has commented (non-deleted comments). Used to fan out notifications.
func (q *Queries) ListTaskParticipants(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTaskParticipants, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTemplates = `-- name: ListTaskTemplates :many
SELECT id, project_id, name, title, description, created_by, created_at, updated_at FROM task_templates WHERE project_id = $1 ORDER BY name ASC
`

func (q *Queries) ListTaskTemplates(ctx context.Context, projectID uuid.UUID) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTaskTemplates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       p.project_key, ps.name as state_name, ps.state_type, ps.color as state_color
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN task_assignees ta ON t.id = ta.task_id
WHERE ta.user_id = $1 AND t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND ps.state_type NOT IN ('completed', 'cancelled')
  AND ($4::uuid IS NULL OR p.workspace_id = $4)
ORDER BY t.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByAssigneeParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ListTasksByAssigneeRow struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	TaskNumber int32       `json:"task_number"`
	Title      string      `json:"title"`
	StateID    uuid.UUID   `json:"state_id"`
	Priority   int32       `json:"priority"`
	ProjectKey string      `json:"project_key"`
	StateName  string      `json:"state_name"`
	StateType  string      `json:"state_type"`
	StateColor pgtype.Text `json:"state_color"`
}

func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByAssigneeRow{}
	for rows.Next() {
		var i ListTasksByAssigneeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivity = `-- name: ListUserActivity :many

SELECT id, task_id, activity_type, actor_id, field_name, old_value, new_value, created_at,
       username, first_name, last_name,
       task_number, project_key, task_title
FROM (
  -- Activities from activity_log
  SELECT al.id, al.task_id, al.activity_type, al.actor_id, al.field_name, al.old_value, al.new_value, al.created_at,
         u.username, u.first_name, u.last_name,
         t.task_number, p.project_key, t.title as task_title
  FROM activity_log al
  JOIN users u ON al.actor_id = u.id
  JOIN tasks t ON al.task_id = t.id
  JOIN projects p ON t.project_id = p.id
  WHERE al.actor_id = $1

  UNION ALL

  -- Synthetic "task_created" entries for imported tasks with no activity_log
  SELECT t.id as id, t.id as task_id, 'task_created'::activity_type as activity_type, t.created_by as actor_id,
         NULL::varchar(100) as field_name, NULL::jsonb as old_value, NULL::jsonb as new_value, t.created_at,
         u.username, u.first_name, u.last_name,
         t.task_number, p.project_key, t.title as task_title
  FROM tasks t
  JOIN users u ON t.created_by = u.id
  JOIN projects p ON t.project_id = p.id
  WHERE t.created_by = $1
    AND t.deleted_at IS NULL
    AND NOT EXISTS (
      SELECT 1 FROM activity_log al
      WHERE al.task_id = t.id AND al.actor_id = $1 AND al.activity_type = 'task_created'
    )
) combined
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserActivityParams struct {
	ActorID uuid.UUID `json:"actor_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListUserActivityRow struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	TaskNumber   int32              `json:"task_number"`
	ProjectKey   string             `json:"project_key"`
	TaskTitle    string             `json:"task_title"`
}

// ==================== USER ACTIVITY ====================
func (q *Queries) ListUserActivity(ctx context.Context, arg ListUserActivityParams) ([]ListUserActivityRow, error) {
	rows, err := q.db.Query(ctx, listUserActivity, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActivityRow{}
	for rows.Next() {
		var i ListUserActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.TaskNumber,
			&i.ProjectKey,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivityDates = `-- name: ListUserActivityDates :many
SELECT activity_date, SUM(cnt)::int as activity_count
FROM (
  SELECT DATE(al.created_at AT TIME ZONE 'UTC') as activity_date, COUNT(*) as cnt
  FROM activity_log al
  WHERE al.actor_id = $1 AND al.created_at >= $2
  GROUP BY DATE(al.created_at AT TIME ZONE 'UTC')

  UNION ALL

  SELECT DATE(t.created_at AT TIME ZONE 'UTC') as activity_date, COUNT(*) as cnt
  FROM tasks t
  WHERE t.created_by = $1 AND t.deleted_at IS NULL AND t.created_at >= $2
    AND NOT EXISTS (
      SELECT 1 FROM activity_log al
      WHERE al.task_id = t.id AND al.actor_id = $1 AND al.activity_type = 'task_created'
    )
  GROUP BY DATE(t.created_at AT TIME ZONE 'UTC')
) combined
GROUP BY activity_date
ORDER BY activity_date ASC
`

type ListUserActivityDatesParams struct {
	ActorID   uuid.UUID          `json:"actor_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListUserActivityDatesRow struct {
	ActivityDate  pgtype.Date `json:"activity_date"`
	ActivityCount int32       `json:"activity_count"`
}

func (q *Queries) ListUserActivityDates(ctx context.Context, arg ListUserActivityDatesParams) ([]ListUserActivityDatesRow, error) {
	rows, err := q.db.Query(ctx, listUserActivityDates, arg.ActorID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActivityDatesRow{}
	for rows.Next() {
		var i ListUserActivityDatesRow
		if err := rows.Scan(&i.ActivityDate, &i.ActivityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.workspace_id, pm.role
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
ORDER BY p.name ASC
LIMIT $2 OFFSET $3
`

type ListUserProjectsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListUserProjectsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Role        string             `json:"role"`
}

func (q *Queries) ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listUserProjects, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsRow{}
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkspaceID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectsFiltered = `-- name: ListUserProjectsFiltered :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.workspace_id, pm.role
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
  AND ($4::uuid IS NULL OR p.workspace_id = $4)
  AND ($5::text IS NULL OR p.name ILIKE '%' || $5 || '%' OR p.project_key ILIKE '%' || $5 || '%' OR p.description ILIKE '%' || $5 || '%')
ORDER BY p.name ASC
LIMIT $2 OFFSET $3
`

type ListUserProjectsFilteredParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Search      pgtype.Text `json:"search"`
}

type ListUserProjectsFilteredRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Role        string             `json:"role"`
}

func (q *Queries) ListUserProjectsFiltered(ctx context.Context, arg ListUserProjectsFilteredParams) ([]ListUserProjectsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listUserProjectsFiltered,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.WorkspaceID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsFilteredRow{}
	for rows.Next() {
		var i ListUserProjectsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkspaceID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET project_id = $1,
    task_number = $2,
    state_id = $3,
    updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, project_id, task_number, title, description, state_id, priority, created_by, start_date, due_date, parent_task_id, created_at, updated_at, deleted_at
`

type MoveTaskParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	TaskNumber int32     `json:"task_number"`
	StateID    uuid.UUID `json:"state_id"`
	ID         uuid.UUID `json:"id"`
}

type MoveTaskRow struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	TaskNumber   int32              `json:"task_number"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StateID      uuid.UUID          `json:"state_id"`
	Priority     int32              `json:"priority"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// Move a task to a different project, assigning a new project-local task number
// and state. Cycle/module links and labels are handled separately by the caller.
func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (MoveTaskRow, error) {
	row := q.db.QueryRow(ctx, moveTask,
		arg.ProjectID,
		arg.TaskNumber,
		arg.StateID,
		arg.ID,
	)
	var i MoveTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.StartDate,
		&i.DueDate,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const projectKeyExists = `-- name: ProjectKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM projects
    WHERE project_key = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ProjectKeyExists(ctx context.Context, projectKey string) (bool, error) {
	row := q.db.QueryRow(ctx, projectKeyExists, projectKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const removeTaskAssignee = `-- name: RemoveTaskAssignee :exec
DELETE FROM task_assignees
WHERE task_id = $1 AND user_id = $2
`

type RemoveTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const removeTaskLabel = `-- name: RemoveTaskLabel :exec
DELETE FROM task_labels
WHERE task_id = $1 AND label_id = $2
`

type RemoveTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error {
	_, err := q.db.Exec(ctx, removeTaskLabel, arg.TaskID, arg.LabelID)
	return err
}

const searchAllProjects = `-- name: SearchAllProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id
FROM projects p
WHERE p.deleted_at IS NULL
  AND (
    p.project_key ILIKE '%' || $1::text || '%'
    OR p.name ILIKE '%' || $1::text || '%'
    OR p.description ILIKE '%' || $1::text || '%'
  )
ORDER BY
  CASE WHEN p.project_key ILIKE $1::text || '%' THEN 0
       WHEN p.name ILIKE $1::text || '%' THEN 1
       ELSE 2 END,
  p.name ASC
LIMIT $2
`

type SearchAllProjectsParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

type SearchAllProjectsRow struct {
	ID          uuid.UUID   `json:"id"`
	ProjectKey  string      `json:"project_key"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
}

// Admin variant: matches across all projects.
func (q *Queries) SearchAllProjects(ctx context.Context, arg SearchAllProjectsParams) ([]SearchAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchAllProjects, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAllProjectsRow{}
	for rows.Next() {
		var i SearchAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllTasks = `-- name: SearchAllTasks :many
SELECT t.id, t.task_number, t.title, t.description,
       p.id AS project_id, p.project_key, p.name AS project_name,
       ps.name AS state_name, ps.state_type, ps.color AS state_color,
       t.updated_at
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND (
    t.title ILIKE '%' || $1::text || '%'
    OR t.description ILIKE '%' || $1::text || '%'
    OR (p.project_key || '-' || t.task_number::text) ILIKE '%' || $1::text || '%'
  )
ORDER BY
  CASE WHEN (p.project_key || '-' || t.task_number::text) ILIKE $1::text || '%' THEN 0
       WHEN t.title ILIKE $1::text || '%' THEN 1
       ELSE 2 END,
  t.updated_at DESC
LIMIT $2
`

type SearchAllTasksParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

type SearchAllTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	TaskNumber  int32              `json:"task_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ProjectID   uuid.UUID          `json:"project_id"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
	StateName   string             `json:"state_name"`
	StateType   string             `json:"state_type"`
	StateColor  pgtype.Text        `json:"state_color"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Admin variant: matches across all projects.
func (q *Queries) SearchAllTasks(ctx context.Context, arg SearchAllTasksParams) ([]SearchAllTasksRow, error) {
	rows, err := q.db.Query(ctx, searchAllTasks, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAllTasksRow{}
	for rows.Next() {
		var i SearchAllTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserProjects = `-- name: SearchUserProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
  AND (
    p.project_key ILIKE '%' || $2::text || '%'
    OR p.name ILIKE '%' || $2::text || '%'
    OR p.description ILIKE '%' || $2::text || '%'
  )
ORDER BY
  CASE WHEN p.project_key ILIKE $2::text || '%' THEN 0
       WHEN p.name ILIKE $2::text || '%' THEN 1
       ELSE 2 END,
  p.name ASC
LIMIT $3
`

type SearchUserProjectsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Query      string    `json:"query"`
	LimitCount int32     `json:"limit_count"`
}

type SearchUserProjectsRow struct {
	ID          uuid.UUID   `json:"id"`
	ProjectKey  string      `json:"project_key"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
}

// Matches projects by key, name, or description across projects the user is a member of.
func (q *Queries) SearchUserProjects(ctx context.Context, arg SearchUserProjectsParams) ([]SearchUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchUserProjects, arg.UserID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUserProjectsRow{}
	for rows.Next() {
		var i SearchUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserTasks = `-- name: SearchUserTasks :many

SELECT t.id, t.task_number, t.title, t.description,
       p.id AS project_id, p.project_key, p.name AS project_name,
       ps.name AS state_name, ps.state_type, ps.color AS state_color,
       t.updated_at
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
WHERE EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id = p.id AND pm.user_id = $1)
  AND t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND (
    t.title ILIKE '%' || $2::text || '%'
    OR t.description ILIKE '%' || $2::text || '%'
    OR (p.project_key || '-' || t.task_number::text) ILIKE '%' || $2::text || '%'
  )
ORDER BY
  CASE WHEN (p.project_key || '-' || t.task_number::text) ILIKE $2::text || '%' THEN 0
       WHEN t.title ILIKE $2::text || '%' THEN 1
       ELSE 2 END,
  t.updated_at DESC
LIMIT $3
`

type SearchUserTasksParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Query      string    `json:"query"`
	LimitCount int32     `json:"limit_count"`
}

type SearchUserTasksRow struct {
	ID          uuid.UUID          `json:"id"`
	TaskNumber  int32              `json:"task_number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ProjectID   uuid.UUID          `json:"project_id"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
	StateName   string             `json:"state_name"`
	StateType   string             `json:"state_type"`
	StateColor  pgtype.Text        `json:"state_color"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// ==================== GLOBAL SEARCH ====================
// Matches tasks by title, description, or composed task key ("KEY-123") across
// projects the user is a member of.
func (q *Queries) SearchUserTasks(ctx context.Context, arg SearchUserTasksParams) ([]SearchUserTasksRow, error) {
	rows, err := q.db.Query(ctx, searchUserTasks, arg.UserID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUserTasksRow{}
	for rows.Next() {
		var i SearchUserTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectDisabled = `-- name: SetProjectDisabled :one
UPDATE projects
SET disabled = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
`

type SetProjectDisabledParams struct {
	Disabled bool      `json:"disabled"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetProjectDisabled(ctx context.Context, arg SetProjectDisabledParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectDisabled, arg.Disabled, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const setTaskParent = `-- name: SetTaskParent :exec
UPDATE tasks
SET parent_task_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SetTaskParentParams struct {
	ID           uuid.UUID   `json:"id"`
	ParentTaskID pgtype.UUID `json:"parent_task_id"`
}

// Sets (or clears) a task's parent. Used to attach/re-parent an existing task
// as a subtask.
func (q *Queries) SetTaskParent(ctx context.Context, arg SetTaskParentParams) error {
	_, err := q.db.Exec(ctx, setTaskParent, arg.ID, arg.ParentTaskID)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, task_id, content, version, created_by, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    icon_id = COALESCE($4, icon_id),
    cover_id = COALESCE($5, cover_id),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
	CoverID     pgtype.UUID `json:"cover_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IconID,
		arg.CoverID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const updateProjectLabel = `-- name: UpdateProjectLabel :one
UPDATE project_labels
SET name = COALESCE($2, name),
    color = COALESCE($3, color)
WHERE id = $1
RETURNING id, project_id, name, color, created_at
`

type UpdateProjectLabelParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateProjectLabel(ctx context.Context, arg UpdateProjectLabelParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, updateProjectLabel, arg.ID, arg.Name, arg.Color)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const updateProjectState = `-- name: UpdateProjectState :one
UPDATE project_states
SET name = COALESCE($2, name),
    color = COALESCE($3, color),
    position = COALESCE($4, position)
WHERE id = $1
RETURNING id, project_id, state_type, name, color, position, is_default, created_at
`

type UpdateProjectStateParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     pgtype.Text `json:"name"`
	Color    pgtype.Text `json:"color"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, updateProjectState,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectWorkspace = `-- name: UpdateProjectWorkspace :one
UPDATE projects
SET workspace_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at, disabled, workspace_id
`

type UpdateProjectWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateProjectWorkspace(ctx context.Context, arg UpdateProjectWorkspaceParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectWorkspace, arg.ID, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.WorkspaceID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    state_id = COALESCE($4, state_id),
    priority = COALESCE($5, priority),
    start_date = CASE WHEN $6::bool THEN $7 ELSE start_date END,
    due_date = CASE WHEN $8::bool THEN $9 ELSE due_date END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, task_number, title, description, state_id, priority, created_by, start_date, due_date, parent_task_id, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID              uuid.UUID          `json:"id"`
	Title           pgtype.Text        `json:"title"`
	Description     pgtype.Text        `json:"description"`
	StateID         pgtype.UUID        `json:"state_id"`
	Priority        pgtype.Int4        `json:"priority"`
	UpdateStartDate bool               `json:"update_start_date"`
	StartDate       pgtype.Timestamptz `json:"start_date"`
	UpdateDueDate   bool               `json:"update_due_date"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
}

type UpdateTaskRow struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	TaskNumber   int32              `json:"task_number"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	StateID      uuid.UUID          `json:"state_id"`
	Priority     int32              `json:"priority"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.Priority,
		arg.UpdateStartDate,
		arg.StartDate,
		arg.UpdateDueDate,
		arg.DueDate,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.StartDate,
		&i.DueDate,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaskTemplate = `-- name: UpdateTaskTemplate :one
UPDATE task_templates
SET name = COALESCE($2, name),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, title, description, created_by, created_at, updated_at
`

type UpdateTaskTemplateParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, updateTaskTemplate,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Description,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyActivityChain = `-- name: VerifyActivityChain :many
SELECT id, task_id, activity_type, actor_id, field_name, old_value, new_value, created_at, checksum
FROM activity_log
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) VerifyActivityChain(ctx context.Context, taskID uuid.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, verifyActivityChain, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
