// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// All activity_log events except comment lifecycle events (state changes,
	// assignee/label edits, task lifecycle, etc.).
	ActivityCreatedPerDay(ctx context.Context, arg ActivityCreatedPerDayParams) ([]ActivityCreatedPerDayRow, error)
	// ==================== MODULE MEMBERS ====================
	AddModuleMember(ctx context.Context, arg AddModuleMemberParams) error
	AddModuleMembersBulk(ctx context.Context, arg AddModuleMembersBulkParams) error
	// ==================== MODULE TASKS ====================
	AddModuleTasksBulk(ctx context.Context, arg AddModuleTasksBulkParams) error
	// ==================== PROJECT MEMBERS ====================
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	// Adds every member of the project as a member of the workspace, skipping any
	// who are already members. Used when moving a project to keep members' access.
	AddProjectMembersToWorkspace(ctx context.Context, arg AddProjectMembersToWorkspaceParams) error
	AddTaskArea(ctx context.Context, arg AddTaskAreaParams) error
	// ==================== TASK ASSIGNEES ====================
	AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error)
	AddTaskBlocker(ctx context.Context, arg AddTaskBlockerParams) (int64, error)
	// ==================== TASK LABELS ====================
	AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error
	AddTaskOriginator(ctx context.Context, arg AddTaskOriginatorParams) (TaskOriginator, error)
	AddTaskWatcher(ctx context.Context, arg AddTaskWatcherParams) (TaskWatcher, error)
	// ==================== CYCLE TASKS ====================
	AddTasksToCycle(ctx context.Context, arg AddTasksToCycleParams) error
	// ==================== WORKSPACE MEMBERS ====================
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	AttachmentsCreatedPerDay(ctx context.Context, arg AttachmentsCreatedPerDayParams) ([]AttachmentsCreatedPerDayRow, error)
	AttachmentsTotalSize(ctx context.Context) (int64, error)
	// True if blocked_id already (transitively) blocks blocker_id, so adding
	// "blocker_id blocks blocked_id" would close a cycle.
	BlockerLinkWouldCycle(ctx context.Context, arg BlockerLinkWouldCycleParams) (bool, error)
	// Soft-delete all children of a task (cascade-together on parent delete).
	CascadeSoftDeleteSubtasks(ctx context.Context, parentID uuid.UUID) error
	CheckCycleOverlap(ctx context.Context, arg CheckCycleOverlapParams) (int32, error)
	ClearProjectDefaultView(ctx context.Context, projectID uuid.UUID) error
	// Merge a new activity into an existing open notification: bump the count,
	// update the latest actor/type/comment, and re-surface as unread.
	CoalesceNotification(ctx context.Context, arg CoalesceNotificationParams) error
	CommentsCreatedPerDay(ctx context.Context, arg CommentsCreatedPerDayParams) ([]CommentsCreatedPerDayRow, error)
	CountActiveProjectPriorities(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountActiveRefreshTokens(ctx context.Context) (int64, error)
	CountAllProjects(ctx context.Context) (int64, error)
	CountAllProjectsFiltered(ctx context.Context, arg CountAllProjectsFilteredParams) (int64, error)
	CountAllWorkspaces(ctx context.Context) (int64, error)
	CountAllWorkspacesFiltered(ctx context.Context, search pgtype.Text) (int64, error)
	CountAttachments(ctx context.Context) (int64, error)
	CountAttachmentsByUpload(ctx context.Context, uploadID uuid.UUID) (int64, error)
	CountDeletedProjects(ctx context.Context) (int64, error)
	CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountPages(ctx context.Context) (int64, error)
	CountProjectCycles(ctx context.Context, arg CountProjectCyclesParams) (int64, error)
	CountProjectMembers(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjectModules(ctx context.Context, arg CountProjectModulesParams) (int64, error)
	CountProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error)
	// Count-only sibling of ListProjectTasksInNoModule, for the backlog card badge.
	CountProjectTasksInNoModule(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountSubtasks(ctx context.Context) (int64, error)
	CountTaskComments(ctx context.Context, taskID uuid.UUID) (int64, error)
	CountTaskOriginators(ctx context.Context, taskID uuid.UUID) (int64, error)
	CountTasksByAssignee(ctx context.Context, arg CountTasksByAssigneeParams) (int64, error)
	CountTasksInPriority(ctx context.Context, priorityID uuid.UUID) (int64, error)
	CountTasksInState(ctx context.Context, stateID uuid.UUID) (int64, error)
	CountTopLevelTasks(ctx context.Context) (int64, error)
	// Count-only sibling of ListUnassignedProjectTasks, for the backlog card badge.
	CountUnassignedProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUserActivity(ctx context.Context, actorID uuid.UUID) (int64, error)
	CountUserProjects(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserProjectsFiltered(ctx context.Context, arg CountUserProjectsFilteredParams) (int64, error)
	CountUserWorkspaces(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserWorkspacesFiltered(ctx context.Context, arg CountUserWorkspacesFilteredParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// The three tab counts in one row, so the admin page shows all of them
	// regardless of which tab is selected.
	CountUsersByState(ctx context.Context) (CountUsersByStateRow, error)
	// Total rows matching the selected state and search, for pagination.
	CountUsersByStateSearch(ctx context.Context, arg CountUsersByStateSearchParams) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	// ==================== ACTIVITY LOG ====================
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	// ==================== COMMENTS ====================
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// ==================== CYCLES ====================
	CreateCycle(ctx context.Context, arg CreateCycleParams) (Cycle, error)
	// ==================== MODULES ====================
	// The handler is responsible for defaulting `status` to 'backlog' when the
	// caller doesn't supply one, so the SQL can keep the arg non-nullable. This
	// sidesteps sqlc's handling of nullable enum args under a string override.
	CreateModule(ctx context.Context, arg CreateModuleParams) (CreateModuleRow, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error)
	// ==================== PROJECTS ====================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ==================== PROJECT AREAS ====================
	// Areas are admin-defined classification values (multi-select per task),
	// mirroring labels structurally but managed as a controlled list.
	CreateProjectArea(ctx context.Context, arg CreateProjectAreaParams) (ProjectArea, error)
	// ==================== PROJECT LABELS ====================
	CreateProjectLabel(ctx context.Context, arg CreateProjectLabelParams) (ProjectLabel, error)
	// ==================== PROJECT PRIORITIES ====================
	// Per-project priority sets; tasks reference a row by id, so renames and
	// recolors apply everywhere instantly. Rank drives ordering (higher = more
	// urgent); deactivated values stay on tasks but leave the pickers.
	CreateProjectPriority(ctx context.Context, arg CreateProjectPriorityParams) (ProjectPriority, error)
	// ==================== PROJECT STATES ====================
	CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error)
	// ==================== PROJECT VIEWS ====================
	CreateProjectView(ctx context.Context, arg CreateProjectViewParams) (CreateProjectViewRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (CreateSSOUserRow, error)
	// ==================== TASKS ====================
	// Requesters/originators live in task_originators; the caller inserts them after
	// creating the task (defaulting to the creator when none are given).
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	// ==================== TASK TEMPLATES ====================
	CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ==================== WORKSPACES ====================
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	CyclesCreatedPerDay(ctx context.Context, arg CyclesCreatedPerDayParams) ([]CyclesCreatedPerDayRow, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	DeleteAllNotifications(ctx context.Context, recipientID uuid.UUID) error
	// Scoped to the routed entity so a cross-task/comment id can't delete someone
	// else's attachment. Returns the upload_id so the caller can clean up the
	// underlying file once no attachment references it anymore.
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (uuid.UUID, error)
	DeleteAttachmentsByEntity(ctx context.Context, arg DeleteAttachmentsByEntityParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteGlobalPreference(ctx context.Context, arg DeleteGlobalPreferenceParams) error
	DeletePersonalAccessToken(ctx context.Context, arg DeletePersonalAccessTokenParams) error
	DeleteProjectArea(ctx context.Context, id uuid.UUID) error
	DeleteProjectLabel(ctx context.Context, id uuid.UUID) error
	DeleteProjectPreference(ctx context.Context, arg DeleteProjectPreferenceParams) error
	DeleteProjectPriority(ctx context.Context, id uuid.UUID) error
	DeleteProjectState(ctx context.Context, id uuid.UUID) error
	DeleteTaskBlockerLinks(ctx context.Context, taskID uuid.UUID) error
	DeleteTaskCycleLinks(ctx context.Context, taskID uuid.UUID) error
	DeleteTaskModuleLinks(ctx context.Context, taskID uuid.UUID) error
	DeleteTaskTemplate(ctx context.Context, id uuid.UUID) error
	DeleteUpload(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetBlockerTaskRef(ctx context.Context, id uuid.UUID) (GetBlockerTaskRefRow, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error)
	GetCycleByID(ctx context.Context, id uuid.UUID) (GetCycleByIDRow, error)
	GetCycleMetrics(ctx context.Context, cycleID uuid.UUID) (GetCycleMetricsRow, error)
	GetCycleStateBreakdown(ctx context.Context, cycleID uuid.UUID) ([]GetCycleStateBreakdownRow, error)
	// The level new tasks fall back to: the lowest-ranked active one.
	GetDefaultProjectPriority(ctx context.Context, projectID uuid.UUID) (ProjectPriority, error)
	GetDefaultProjectState(ctx context.Context, projectID uuid.UUID) (ProjectState, error)
	// A single global preference row for one user, or no rows when unset (the
	// caller then applies the registry default). Used off the request path, e.g.
	// the notifier checking whether a recipient wants email.
	GetGlobalPreference(ctx context.Context, arg GetGlobalPreferenceParams) (GetGlobalPreferenceRow, error)
	GetLastActivityChecksum(ctx context.Context, taskID uuid.UUID) (string, error)
	// COALESCE the joined user fields because LEFT JOIN on nullable lead_id would
	// otherwise trip sqlc's (column-nullability-based) assumption that the fields
	// are non-null.
	GetModuleByID(ctx context.Context, id uuid.UUID) (GetModuleByIDRow, error)
	GetModuleMetrics(ctx context.Context, moduleID uuid.UUID) (GetModuleMetricsRow, error)
	GetModuleStateBreakdown(ctx context.Context, moduleID uuid.UUID) ([]GetModuleStateBreakdownRow, error)
	GetNextPageNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	GetNextTaskNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	// ==================== NOTIFICATIONS ====================
	// Most recent notification for a (recipient, task) pair still within the
	// coalescing window. Used to merge new activity into an existing notification
	// instead of creating a new one (max 1 notification per task per window).
	GetOpenNotification(ctx context.Context, arg GetOpenNotificationParams) (GetOpenNotificationRow, error)
	GetPageByProjectAndNumber(ctx context.Context, arg GetPageByProjectAndNumberParams) (GetPageByProjectAndNumberRow, error)
	GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (GetPersonalAccessTokenByHashRow, error)
	GetProjectAreaByID(ctx context.Context, id uuid.UUID) (ProjectArea, error)
	GetProjectAreaByProjectAndName(ctx context.Context, arg GetProjectAreaByProjectAndNameParams) (ProjectArea, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByKey(ctx context.Context, projectKey string) (Project, error)
	GetProjectLabelByID(ctx context.Context, id uuid.UUID) (ProjectLabel, error)
	GetProjectLabelByProjectAndName(ctx context.Context, arg GetProjectLabelByProjectAndNameParams) (ProjectLabel, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error)
	GetProjectPriorityByID(ctx context.Context, id uuid.UUID) (ProjectPriority, error)
	GetProjectPriorityByProjectAndName(ctx context.Context, arg GetProjectPriorityByProjectAndNameParams) (ProjectPriority, error)
	GetProjectPriorityByProjectAndRank(ctx context.Context, arg GetProjectPriorityByProjectAndRankParams) (ProjectPriority, error)
	GetProjectStateByID(ctx context.Context, id uuid.UUID) (ProjectState, error)
	// ==================== IMPORT HELPERS ====================
	GetProjectStateByProjectAndName(ctx context.Context, arg GetProjectStateByProjectAndNameParams) (ProjectState, error)
	GetProjectViewByID(ctx context.Context, id uuid.UUID) (GetProjectViewByIDRow, error)
	GetProjectViewBySlug(ctx context.Context, arg GetProjectViewBySlugParams) (GetProjectViewBySlugRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	// Given a set of task IDs, return the distinct user IDs of their assignees.
	// Used to auto-seed module members when tasks are linked to a module.
	GetTaskAssigneesForSeeding(ctx context.Context, taskIds []uuid.UUID) ([]uuid.UUID, error)
	// Validates a candidate before attaching it as a subtask: its project and
	// whether it already has children (which would break the one-level rule).
	GetTaskAttachEligibility(ctx context.Context, id uuid.UUID) (GetTaskAttachEligibilityRow, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error)
	GetTaskByProjectAndNumber(ctx context.Context, arg GetTaskByProjectAndNumberParams) (GetTaskByProjectAndNumberRow, error)
	GetTaskCycleID(ctx context.Context, taskID uuid.UUID) (uuid.UUID, error)
	GetTaskTemplateByID(ctx context.Context, id uuid.UUID) (TaskTemplate, error)
	GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error)
	// Deliberately narrow: only the password hash, so it is never carried around on
	// the general-purpose user row. Used to verify the current password on change.
	GetUserPasswordHash(ctx context.Context, id uuid.UUID) (pgtype.Text, error)
	// The state of the account that owns a conflicting email/username, so create
	// can explain whether it's active, deactivated or deleted.
	GetUserStatusByEmailOrUsername(ctx context.Context, arg GetUserStatusByEmailOrUsernameParams) (GetUserStatusByEmailOrUsernameRow, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceByKey(ctx context.Context, workspaceKey string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (bool, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error)
	IsTaskOriginator(ctx context.Context, arg IsTaskOriginatorParams) (bool, error)
	IsTaskWatcher(ctx context.Context, arg IsTaskWatcherParams) (bool, error)
	IsUserActive(ctx context.Context, id uuid.UUID) (bool, error)
	IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error)
	LinkProviderToUser(ctx context.Context, arg LinkProviderToUserParams) error
	ListActiveCyclesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveCyclesForUserRow, error)
	// "Active" modules across all projects the user is a member of. Uses the
	// explicit status enum (modules don't derive status from dates the way cycles
	// do). in_progress is the natural "currently being worked on" state.
	ListActiveModulesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveModulesForUserRow, error)
	ListActiveRefreshTokens(ctx context.Context, arg ListActiveRefreshTokensParams) ([]ListActiveRefreshTokensRow, error)
	ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]ListAllProjectsRow, error)
	ListAllProjectsFiltered(ctx context.Context, arg ListAllProjectsFilteredParams) ([]ListAllProjectsFilteredRow, error)
	ListAllWorkspaces(ctx context.Context, arg ListAllWorkspacesParams) ([]Workspace, error)
	ListAllWorkspacesFiltered(ctx context.Context, arg ListAllWorkspacesFilteredParams) ([]Workspace, error)
	ListAreasForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAreasForTasksRow, error)
	// Filtered list and count are now built dynamically by internal/store/tasks_filter.go
	// from a FilterTree. The projection here is documented for reference by that runner.
	ListAssigneesForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesForTasksRow, error)
	ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]ListAttachmentsByEntityRow, error)
	// Project tasks that can be linked to the given task in either direction:
	// excludes the task itself and tasks already linked to it.
	ListBlockerCandidates(ctx context.Context, arg ListBlockerCandidatesParams) ([]ListBlockerCandidatesRow, error)
	// Blocker links where both tasks are already on the graph.
	ListBlockerLinksForGraph(ctx context.Context, taskIds []uuid.UUID) ([]ListBlockerLinksForGraphRow, error)
	ListCycleAssignees(ctx context.Context, cycleID uuid.UUID) ([]ListCycleAssigneesRow, error)
	ListCycleTasks(ctx context.Context, arg ListCycleTasksParams) ([]ListCycleTasksRow, error)
	ListDeletedProjects(ctx context.Context, arg ListDeletedProjectsParams) ([]ListDeletedProjectsRow, error)
	// ==================== USER PREFERENCES ====================
	//
	// Rows hold only user overrides; a missing row means "use the registry
	// default". Reads return the whole set for a scope so the API can fold in
	// defaults. Writes are revision-aware (optimistic concurrency): the caller
	// passes the revision it last saw, and the update only applies when the stored
	// revision still matches. A brand-new row is created at revision 1 regardless.
	ListGlobalPreferences(ctx context.Context, userID uuid.UUID) ([]ListGlobalPreferencesRow, error)
	ListGraphProjectOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphProjectOptionsRow, error)
	ListGraphUserOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphUserOptionsRow, error)
	ListGraphWorkspaceOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphWorkspaceOptionsRow, error)
	ListLabelsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListLabelsForTasksRow, error)
	ListModuleMembers(ctx context.Context, moduleID uuid.UUID) ([]ListModuleMembersRow, error)
	// Used for hydrating the list view with member avatars. Returns up to 4 members
	// per module so the card can show 3 + "+N more".
	ListModuleMembersForModules(ctx context.Context, moduleIds []uuid.UUID) ([]ListModuleMembersForModulesRow, error)
	// Used by the duplicate dialog to pre-populate the issues checklist.
	ListModuleTaskIDs(ctx context.Context, moduleID uuid.UUID) ([]uuid.UUID, error)
	ListModuleTasks(ctx context.Context, arg ListModuleTasksParams) ([]ListModuleTasksRow, error)
	// A recipient's notifications, newest first, with task/project/actor display fields.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// ==================== TASK ORIGINATORS ====================
	// Requesters/originators, many-to-many, mirroring task assignees. "to" is a SQL
	// keyword so the join table is aliased to2/o.
	ListOriginatorsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListOriginatorsForTasksRow, error)
	// Picker source for re-parenting a sub-task: top-level tasks that could be its
	// parent. One level only, so tasks that are themselves sub-tasks are out.
	// Server-searched and capped — never meant to list a whole project.
	ListParentCandidates(ctx context.Context, arg ListParentCandidatesParams) ([]ListParentCandidatesRow, error)
	ListPersonalAccessTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListPersonalAccessTokensByUserRow, error)
	ListProjectAreas(ctx context.Context, projectID uuid.UUID) ([]ProjectArea, error)
	ListProjectCycles(ctx context.Context, arg ListProjectCyclesParams) ([]ListProjectCyclesRow, error)
	ListProjectCyclesAll(ctx context.Context, projectID uuid.UUID) ([]ListProjectCyclesAllRow, error)
	ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]ProjectLabel, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	// Project members who are NOT members of the given workspace. Used to preview
	// who would lose visibility of the project when it moves to that workspace.
	ListProjectMembersMissingFromWorkspace(ctx context.Context, arg ListProjectMembersMissingFromWorkspaceParams) ([]ListProjectMembersMissingFromWorkspaceRow, error)
	ListProjectModules(ctx context.Context, arg ListProjectModulesParams) ([]ListProjectModulesRow, error)
	// Optional case-insensitive search over the title and the page's visible text
	// (HTML tags stripped from content so markup/attributes don't produce matches).
	ListProjectPages(ctx context.Context, arg ListProjectPagesParams) ([]ListProjectPagesRow, error)
	ListProjectPreferences(ctx context.Context, arg ListProjectPreferencesParams) ([]ListProjectPreferencesRow, error)
	// task_count lets the settings UI warn what an edit or delete touches.
	ListProjectPriorities(ctx context.Context, projectID uuid.UUID) ([]ListProjectPrioritiesRow, error)
	// task_count lets the settings UI warn how many tasks a state edit touches.
	ListProjectStates(ctx context.Context, projectID uuid.UUID) ([]ListProjectStatesRow, error)
	ListProjectTaskIDsIn(ctx context.Context, arg ListProjectTaskIDsInParams) ([]uuid.UUID, error)
	ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error)
	// Backlog source ("Tasks Without an Epic"): project top-level tasks that are in
	// no module at all. Unlike the picker above, this excludes tasks in ANY module.
	// A task with no module can still be in a cycle, so we surface its sprint too.
	ListProjectTasksInNoModule(ctx context.Context, arg ListProjectTasksInNoModuleParams) ([]ListProjectTasksInNoModuleRow, error)
	// Picker source: project tasks that are NOT already in the given module. A task
	// can belong to many modules, so we only exclude by the target module.
	ListProjectTasksNotInModule(ctx context.Context, arg ListProjectTasksNotInModuleParams) ([]ListProjectTasksNotInModuleRow, error)
	// Returns every shared view in the project plus private views owned by the caller.
	ListProjectViews(ctx context.Context, arg ListProjectViewsParams) ([]ListProjectViewsRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	// Picker source for "attach an existing task as a subtask". Returns project
	// tasks eligible to become a child of the given parent. Excludes: the parent
	// itself, tasks already parented to this same parent, and tasks that already
	// have their own children (attaching one would break the one-level rule).
	// Tasks parented elsewhere ARE included (they can be re-parented) and flagged
	// via has_parent so the UI can warn.
	ListSubtaskCandidates(ctx context.Context, arg ListSubtaskCandidatesParams) ([]ListSubtaskCandidatesRow, error)
	// Child ids + state name of a task, used to cascade a cross-project move.
	ListSubtaskIDsForMove(ctx context.Context, parentID uuid.UUID) ([]ListSubtaskIDsForMoveRow, error)
	// Direct children of a task, in task-number order. Used on the parent's detail page.
	ListSubtasks(ctx context.Context, parentID uuid.UUID) ([]ListSubtasksRow, error)
	ListTaskActivity(ctx context.Context, taskID uuid.UUID) ([]ListTaskActivityRow, error)
	ListTaskAreas(ctx context.Context, taskID uuid.UUID) ([]ListTaskAreasRow, error)
	ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error)
	// One row per (task, assignee); unassigned tasks come back once with NULL user columns.
	ListTaskAssignmentsForGraph(ctx context.Context, arg ListTaskAssignmentsForGraphParams) ([]ListTaskAssignmentsForGraphRow, error)
	// ==================== TASK BLOCKERS ====================
	// Both sides of a task's blocker links: is_blocked_by is true when the row is a
	// blocker of the given task, false when the given task blocks it.
	ListTaskBlockerLinks(ctx context.Context, taskID uuid.UUID) ([]ListTaskBlockerLinksRow, error)
	ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error)
	ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]ListTaskLabelsRow, error)
	// The modules a task belongs to (a task can be in more than one).
	ListTaskModules(ctx context.Context, taskID uuid.UUID) ([]ListTaskModulesRow, error)
	ListTaskOriginators(ctx context.Context, taskID uuid.UUID) ([]ListTaskOriginatorsRow, error)
	// ==================== TASK PARTICIPANTS ====================
	// Everyone involved with a task: its creator, current assignees, watchers, and
	// anyone who has commented (non-deleted comments). Used to fan out in-app
	// notifications.
	ListTaskParticipants(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error)
	ListTaskTemplates(ctx context.Context, projectID uuid.UUID) ([]TaskTemplate, error)
	ListTaskWatchers(ctx context.Context, taskID uuid.UUID) ([]ListTaskWatchersRow, error)
	ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error)
	ListUnassignedProjectTasks(ctx context.Context, arg ListUnassignedProjectTasksParams) ([]ListUnassignedProjectTasksRow, error)
	ListUploadsByUser(ctx context.Context, arg ListUploadsByUserParams) ([]Upload, error)
	// ==================== USER ACTIVITY ====================
	ListUserActivity(ctx context.Context, arg ListUserActivityParams) ([]ListUserActivityRow, error)
	ListUserActivityDates(ctx context.Context, arg ListUserActivityDatesParams) ([]ListUserActivityDatesRow, error)
	ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error)
	ListUserProjectsFiltered(ctx context.Context, arg ListUserProjectsFilteredParams) ([]ListUserProjectsFilteredRow, error)
	ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]Workspace, error)
	ListUserWorkspacesFiltered(ctx context.Context, arg ListUserWorkspacesFilteredParams) ([]Workspace, error)
	// One page of users in the selected state, filtered by an optional search.
	// Actor names for who deactivated/deleted are folded in via LEFT JOINs and
	// COALESCEd to non-null strings ('' when unknown).
	ListUsersByState(ctx context.Context, arg ListUsersByStateParams) ([]ListUsersByStateRow, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error)
	// ==================== TASK WATCHERS ====================
	// Users following a task to receive its updates, many-to-many, mirroring task
	// assignees. Zero or more per task.
	ListWatchersForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListWatchersForTasksRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	// Serializes blocker writes per project so concurrent adds can't form a cycle.
	LockProjectBlockers(ctx context.Context, projectID uuid.UUID) error
	MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MergeCopyModuleMembers(ctx context.Context, arg MergeCopyModuleMembersParams) (int64, error)
	MergeCopyPrivateViews(ctx context.Context, arg MergeCopyPrivateViewsParams) (int64, error)
	MergeCopyProjectMembers(ctx context.Context, arg MergeCopyProjectMembersParams) (int64, error)
	MergeCopyTaskAssignees(ctx context.Context, arg MergeCopyTaskAssigneesParams) (int64, error)
	// Admin "merge user": additively grants the target everything the source has.
	// The source user is never modified and activity_log is never touched.
	MergeCopyWorkspaceMembers(ctx context.Context, arg MergeCopyWorkspaceMembersParams) (int64, error)
	// The target starts watching every task the source created, watched or
	// commented on, so the merged account keeps receiving those updates.
	MergeWatchSourceTasks(ctx context.Context, arg MergeWatchSourceTasksParams) (int64, error)
	ModulesCreatedPerDay(ctx context.Context, arg ModulesCreatedPerDayParams) ([]ModulesCreatedPerDayRow, error)
	// Move a task to a different project, assigning a new project-local task number
	// and state. Cycle/module links and labels are handled separately by the caller.
	MoveTask(ctx context.Context, arg MoveTaskParams) (MoveTaskRow, error)
	PagesCreatedPerDay(ctx context.Context, arg PagesCreatedPerDayParams) ([]PagesCreatedPerDayRow, error)
	ProjectKeyExists(ctx context.Context, projectKey string) (bool, error)
	ProjectViewSlugExists(ctx context.Context, arg ProjectViewSlugExistsParams) (bool, error)
	ProjectsPerWorkspace(ctx context.Context) ([]ProjectsPerWorkspaceRow, error)
	ReactivateUser(ctx context.Context, id uuid.UUID) error
	RemoveModuleMember(ctx context.Context, arg RemoveModuleMemberParams) error
	RemoveModuleTask(ctx context.Context, arg RemoveModuleTaskParams) error
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RemoveTaskArea(ctx context.Context, arg RemoveTaskAreaParams) error
	RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error
	// Removes the link between two tasks in whichever direction it exists.
	RemoveTaskBlockerLink(ctx context.Context, arg RemoveTaskBlockerLinkParams) ([]RemoveTaskBlockerLinkRow, error)
	RemoveTaskFromCycle(ctx context.Context, arg RemoveTaskFromCycleParams) error
	RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error
	RemoveTaskOriginator(ctx context.Context, arg RemoveTaskOriginatorParams) error
	RemoveTaskWatcher(ctx context.Context, arg RemoveTaskWatcherParams) error
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	// Pass a JSON array of {id, new_position} objects.
	ReorderProjectViews(ctx context.Context, arg ReorderProjectViewsParams) error
	// Pass a JSON array of {id, new_position} objects. Site-admin only
	// (enforced in the route); positions are one global order for everyone.
	ReorderProjects(ctx context.Context, items []byte) error
	RestoreProject(ctx context.Context, id uuid.UUID) error
	// Restores a deleted account back to Active (usable right away).
	RestoreUser(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Admin variant: matches across all projects.
	SearchAllCycles(ctx context.Context, arg SearchAllCyclesParams) ([]SearchAllCyclesRow, error)
	// Admin variant: matches across all projects.
	SearchAllProjects(ctx context.Context, arg SearchAllProjectsParams) ([]SearchAllProjectsRow, error)
	// Admin variant: matches across all projects.
	SearchAllTasks(ctx context.Context, arg SearchAllTasksParams) ([]SearchAllTasksRow, error)
	// ==================== GLOBAL SEARCH ====================
	// Matches cycles by title across projects the user is a member of.
	SearchUserCycles(ctx context.Context, arg SearchUserCyclesParams) ([]SearchUserCyclesRow, error)
	// Matches projects by key, name, or description across projects the user is a member of.
	SearchUserProjects(ctx context.Context, arg SearchUserProjectsParams) ([]SearchUserProjectsRow, error)
	// ==================== GLOBAL SEARCH ====================
	// Matches tasks by title, description, or composed task key ("KEY-123") across
	// projects the user is a member of.
	SearchUserTasks(ctx context.Context, arg SearchUserTasksParams) ([]SearchUserTasksRow, error)
	// Used to find people to add to a project/workspace, so deleted users are
	// excluded: a removed account must never be re-addable.
	SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]SearchUsersPaginatedRow, error)
	// Marks exactly one state as default for the project, clearing any previous
	// default. Atomic in a single statement (no transaction needed).
	SetDefaultProjectState(ctx context.Context, arg SetDefaultProjectStateParams) error
	// Points the project's single default at one view: sets the flag there and
	// clears it everywhere else in one statement.
	SetProjectDefaultView(ctx context.Context, arg SetProjectDefaultViewParams) error
	SetProjectDisabled(ctx context.Context, arg SetProjectDisabledParams) (Project, error)
	// Sets (or clears) a task's parent. Used to attach/re-parent an existing task
	// as a subtask.
	SetTaskParent(ctx context.Context, arg SetTaskParentParams) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeleteCycle(ctx context.Context, id uuid.UUID) error
	SoftDeleteModule(ctx context.Context, id uuid.UUID) error
	// When a member leaves a project, their private views are soft-deleted.
	SoftDeleteOwnedPrivateViews(ctx context.Context, arg SoftDeleteOwnedPrivateViewsParams) error
	SoftDeletePage(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteProjectView(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) error
	SubtasksCreatedPerDay(ctx context.Context, arg SubtasksCreatedPerDayParams) ([]SubtasksCreatedPerDayRow, error)
	// Instance-wide aggregate: priorities are per-project entities, so tasks are
	// grouped by level name (most urgent first by each name's highest rank).
	TasksByPriority(ctx context.Context) ([]TasksByPriorityRow, error)
	TasksByStateType(ctx context.Context) ([]TasksByStateTypeRow, error)
	TasksCreatedPerDay(ctx context.Context, arg TasksCreatedPerDayParams) ([]TasksCreatedPerDayRow, error)
	TopProjectsByTaskCount(ctx context.Context) ([]TopProjectsByTaskCountRow, error)
	// When a member leaves a project, keep their shared views alive by reassigning ownership.
	TransferOwnedSharedViews(ctx context.Context, arg TransferOwnedSharedViewsParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateCycle(ctx context.Context, arg UpdateCycleParams) (Cycle, error)
	// `status` is passed as plain text; when empty string, no change. Avoids narg
	// around the enum type under the string override.
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (UpdateModuleRow, error)
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePersonalAccessTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdatePersonalAccessTokenScope(ctx context.Context, arg UpdatePersonalAccessTokenScopeParams) (UpdatePersonalAccessTokenScopeRow, error)
	// clear_icon removes the icon (icon_id NULL); otherwise icon_id follows the
	// usual COALESCE keep-or-replace pattern.
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectArea(ctx context.Context, arg UpdateProjectAreaParams) (ProjectArea, error)
	UpdateProjectLabel(ctx context.Context, arg UpdateProjectLabelParams) (ProjectLabel, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error
	UpdateProjectPriority(ctx context.Context, arg UpdateProjectPriorityParams) (ProjectPriority, error)
	// `state_type` is passed as plain text; when empty string, no change. Avoids
	// narg around the enum type under the string override.
	UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (ProjectState, error)
	UpdateProjectView(ctx context.Context, arg UpdateProjectViewParams) (UpdateProjectViewRow, error)
	UpdateProjectWorkspace(ctx context.Context, arg UpdateProjectWorkspaceParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error)
	UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) (TaskTemplate, error)
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Admin edit of a user's identity fields. Nil args leave a field unchanged.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	// On a matching revision the row is bumped; on a stale revision no row is
	// returned (the handler maps that to 409). A first write (no existing row)
	// inserts at revision 1.
	UpsertGlobalPreference(ctx context.Context, arg UpsertGlobalPreferenceParams) (UpsertGlobalPreferenceRow, error)
	UpsertProjectPreference(ctx context.Context, arg UpsertProjectPreferenceParams) (UpsertProjectPreferenceRow, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
	// Whether a DIFFERENT user (active, deactivated or soft-deleted alike) already
	// owns this email or username. Used by admin profile edits, where the target's
	// own current values must not count as a conflict.
	UserConflictsWithOther(ctx context.Context, arg UserConflictsWithOtherParams) (bool, error)
	UserExistsByEmailOrUsername(ctx context.Context, arg UserExistsByEmailOrUsernameParams) (bool, error)
	VerifyActivityChain(ctx context.Context, taskID uuid.UUID) ([]ActivityLog, error)
	ViewsCreatedPerDay(ctx context.Context, arg ViewsCreatedPerDayParams) ([]ViewsCreatedPerDayRow, error)
	WorkspaceKeyExists(ctx context.Context, workspaceKey string) (bool, error)
}

var _ Querier = (*Queries)(nil)
