// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ==================== MODULE MEMBERS ====================
	AddModuleMember(ctx context.Context, arg AddModuleMemberParams) error
	AddModuleMembersBulk(ctx context.Context, arg AddModuleMembersBulkParams) error
	// ==================== MODULE TASKS ====================
	AddModuleTasksBulk(ctx context.Context, arg AddModuleTasksBulkParams) error
	// ==================== PROJECT MEMBERS ====================
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	// Adds every member of the project as a member of the workspace, skipping any
	// who are already members. Used when moving a project to keep members' access.
	AddProjectMembersToWorkspace(ctx context.Context, arg AddProjectMembersToWorkspaceParams) error
	// ==================== TASK ASSIGNEES ====================
	AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error)
	// ==================== TASK LABELS ====================
	AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error
	// ==================== CYCLE TASKS ====================
	AddTasksToCycle(ctx context.Context, arg AddTasksToCycleParams) error
	// ==================== WORKSPACE MEMBERS ====================
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	// Soft-delete all children of a task (cascade-together on parent delete).
	CascadeSoftDeleteSubtasks(ctx context.Context, parentID uuid.UUID) error
	CheckCycleOverlap(ctx context.Context, arg CheckCycleOverlapParams) (int32, error)
	// Merge a new activity into an existing open notification: bump the count,
	// update the latest actor/type/comment, and re-surface as unread.
	CoalesceNotification(ctx context.Context, arg CoalesceNotificationParams) error
	CountActiveRefreshTokens(ctx context.Context) (int64, error)
	CountAllProjects(ctx context.Context) (int64, error)
	CountAllProjectsFiltered(ctx context.Context, arg CountAllProjectsFilteredParams) (int64, error)
	CountAllWorkspaces(ctx context.Context) (int64, error)
	CountAllWorkspacesFiltered(ctx context.Context, search pgtype.Text) (int64, error)
	CountNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountPages(ctx context.Context) (int64, error)
	CountProjectCycles(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjectMembers(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjectModules(ctx context.Context, arg CountProjectModulesParams) (int64, error)
	CountProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountSubtasks(ctx context.Context) (int64, error)
	CountTaskComments(ctx context.Context, taskID uuid.UUID) (int64, error)
	CountTasksByAssignee(ctx context.Context, arg CountTasksByAssigneeParams) (int64, error)
	CountTasksInState(ctx context.Context, stateID uuid.UUID) (int64, error)
	CountTopLevelTasks(ctx context.Context) (int64, error)
	CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUserActivity(ctx context.Context, actorID uuid.UUID) (int64, error)
	CountUserProjects(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserProjectsFiltered(ctx context.Context, arg CountUserProjectsFilteredParams) (int64, error)
	CountUserWorkspaces(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserWorkspacesFiltered(ctx context.Context, arg CountUserWorkspacesFilteredParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	// ==================== ACTIVITY LOG ====================
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	// ==================== COMMENTS ====================
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// ==================== CYCLES ====================
	CreateCycle(ctx context.Context, arg CreateCycleParams) (Cycle, error)
	// ==================== MODULES ====================
	// The handler is responsible for defaulting `status` to 'backlog' when the
	// caller doesn't supply one, so the SQL can keep the arg non-nullable. This
	// sidesteps sqlc's handling of nullable enum args under a string override.
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error)
	// ==================== PROJECTS ====================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ==================== PROJECT LABELS ====================
	CreateProjectLabel(ctx context.Context, arg CreateProjectLabelParams) (ProjectLabel, error)
	// ==================== PROJECT STATES ====================
	CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error)
	// ==================== PROJECT VIEWS ====================
	CreateProjectView(ctx context.Context, arg CreateProjectViewParams) (CreateProjectViewRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (CreateSSOUserRow, error)
	// ==================== TASKS ====================
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	// ==================== TASK TEMPLATES ====================
	CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ==================== WORKSPACES ====================
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteAttachmentsByEntity(ctx context.Context, arg DeleteAttachmentsByEntityParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeletePersonalAccessToken(ctx context.Context, arg DeletePersonalAccessTokenParams) error
	DeleteProjectLabel(ctx context.Context, id uuid.UUID) error
	DeleteProjectState(ctx context.Context, id uuid.UUID) error
	DeleteTaskCycleLinks(ctx context.Context, taskID uuid.UUID) error
	DeleteTaskModuleLinks(ctx context.Context, taskID uuid.UUID) error
	DeleteTaskTemplate(ctx context.Context, id uuid.UUID) error
	DeleteUpload(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error)
	GetCycleByID(ctx context.Context, id uuid.UUID) (GetCycleByIDRow, error)
	GetCycleMetrics(ctx context.Context, cycleID uuid.UUID) (GetCycleMetricsRow, error)
	GetCycleStateBreakdown(ctx context.Context, cycleID uuid.UUID) ([]GetCycleStateBreakdownRow, error)
	GetDefaultProjectState(ctx context.Context, projectID uuid.UUID) (ProjectState, error)
	GetLastActivityChecksum(ctx context.Context, taskID uuid.UUID) (string, error)
	// COALESCE the joined user fields because LEFT JOIN on nullable lead_id would
	// otherwise trip sqlc's (column-nullability-based) assumption that the fields
	// are non-null.
	GetModuleByID(ctx context.Context, id uuid.UUID) (GetModuleByIDRow, error)
	GetModuleMetrics(ctx context.Context, moduleID uuid.UUID) (GetModuleMetricsRow, error)
	GetModuleStateBreakdown(ctx context.Context, moduleID uuid.UUID) ([]GetModuleStateBreakdownRow, error)
	GetNextPageNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	GetNextTaskNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	// ==================== NOTIFICATIONS ====================
	// Most recent notification for a (recipient, task) pair still within the
	// coalescing window. Used to merge new activity into an existing notification
	// instead of creating a new one (max 1 notification per task per window).
	GetOpenNotification(ctx context.Context, arg GetOpenNotificationParams) (GetOpenNotificationRow, error)
	GetPageByProjectAndNumber(ctx context.Context, arg GetPageByProjectAndNumberParams) (GetPageByProjectAndNumberRow, error)
	GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (GetPersonalAccessTokenByHashRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByKey(ctx context.Context, projectKey string) (Project, error)
	GetProjectLabelByID(ctx context.Context, id uuid.UUID) (ProjectLabel, error)
	GetProjectLabelByProjectAndName(ctx context.Context, arg GetProjectLabelByProjectAndNameParams) (ProjectLabel, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error)
	GetProjectStateByID(ctx context.Context, id uuid.UUID) (ProjectState, error)
	// ==================== IMPORT HELPERS ====================
	GetProjectStateByProjectAndName(ctx context.Context, arg GetProjectStateByProjectAndNameParams) (ProjectState, error)
	GetProjectViewByID(ctx context.Context, id uuid.UUID) (GetProjectViewByIDRow, error)
	GetProjectViewBySlug(ctx context.Context, arg GetProjectViewBySlugParams) (GetProjectViewBySlugRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	// Given a set of task IDs, return the distinct user IDs of their assignees.
	// Used to auto-seed module members when tasks are linked to a module.
	GetTaskAssigneesForSeeding(ctx context.Context, taskIds []uuid.UUID) ([]uuid.UUID, error)
	// Validates a candidate before attaching it as a subtask: its project and
	// whether it already has children (which would break the one-level rule).
	GetTaskAttachEligibility(ctx context.Context, id uuid.UUID) (GetTaskAttachEligibilityRow, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error)
	GetTaskByProjectAndNumber(ctx context.Context, arg GetTaskByProjectAndNumberParams) (GetTaskByProjectAndNumberRow, error)
	GetTaskCycleID(ctx context.Context, taskID uuid.UUID) (uuid.UUID, error)
	GetTaskTemplateByID(ctx context.Context, id uuid.UUID) (TaskTemplate, error)
	GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceByKey(ctx context.Context, workspaceKey string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (bool, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error)
	IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error)
	LinkProviderToUser(ctx context.Context, arg LinkProviderToUserParams) error
	ListActiveCyclesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveCyclesForUserRow, error)
	// "Active" modules across all projects the user is a member of. Uses the
	// explicit status enum (modules don't derive status from dates the way cycles
	// do). in_progress is the natural "currently being worked on" state.
	ListActiveModulesForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveModulesForUserRow, error)
	ListActiveRefreshTokens(ctx context.Context, arg ListActiveRefreshTokensParams) ([]ListActiveRefreshTokensRow, error)
	ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]ListAllProjectsRow, error)
	ListAllProjectsFiltered(ctx context.Context, arg ListAllProjectsFilteredParams) ([]ListAllProjectsFilteredRow, error)
	ListAllWorkspaces(ctx context.Context, arg ListAllWorkspacesParams) ([]Workspace, error)
	ListAllWorkspacesFiltered(ctx context.Context, arg ListAllWorkspacesFilteredParams) ([]Workspace, error)
	// Filtered list and count are now built dynamically by internal/store/tasks_filter.go
	// from a FilterTree. The projection here is documented for reference by that runner.
	ListAssigneesForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesForTasksRow, error)
	ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]ListAttachmentsByEntityRow, error)
	ListCycleAssignees(ctx context.Context, cycleID uuid.UUID) ([]ListCycleAssigneesRow, error)
	ListCycleTasks(ctx context.Context, arg ListCycleTasksParams) ([]ListCycleTasksRow, error)
	ListLabelsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListLabelsForTasksRow, error)
	ListModuleMembers(ctx context.Context, moduleID uuid.UUID) ([]ListModuleMembersRow, error)
	// Used for hydrating the list view with member avatars. Returns up to 4 members
	// per module so the card can show 3 + "+N more".
	ListModuleMembersForModules(ctx context.Context, moduleIds []uuid.UUID) ([]ListModuleMembersForModulesRow, error)
	// Used by the duplicate dialog to pre-populate the issues checklist.
	ListModuleTaskIDs(ctx context.Context, moduleID uuid.UUID) ([]uuid.UUID, error)
	ListModuleTasks(ctx context.Context, arg ListModuleTasksParams) ([]ListModuleTasksRow, error)
	// A recipient's notifications, newest first, with task/project/actor display fields.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListPersonalAccessTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListPersonalAccessTokensByUserRow, error)
	ListProjectCycles(ctx context.Context, arg ListProjectCyclesParams) ([]ListProjectCyclesRow, error)
	ListProjectCyclesAll(ctx context.Context, projectID uuid.UUID) ([]ListProjectCyclesAllRow, error)
	ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]ProjectLabel, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	// Project members who are NOT members of the given workspace. Used to preview
	// who would lose visibility of the project when it moves to that workspace.
	ListProjectMembersMissingFromWorkspace(ctx context.Context, arg ListProjectMembersMissingFromWorkspaceParams) ([]ListProjectMembersMissingFromWorkspaceRow, error)
	ListProjectModules(ctx context.Context, arg ListProjectModulesParams) ([]ListProjectModulesRow, error)
	// Optional case-insensitive search over the title and the page's visible text
	// (HTML tags stripped from content so markup/attributes don't produce matches).
	ListProjectPages(ctx context.Context, arg ListProjectPagesParams) ([]ListProjectPagesRow, error)
	ListProjectStates(ctx context.Context, projectID uuid.UUID) ([]ProjectState, error)
	ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error)
	// Picker source: project tasks that are NOT already in the given module. A task
	// can belong to many modules, so we only exclude by the target module.
	ListProjectTasksNotInModule(ctx context.Context, arg ListProjectTasksNotInModuleParams) ([]ListProjectTasksNotInModuleRow, error)
	// Returns every shared view in the project plus private views owned by the caller.
	ListProjectViews(ctx context.Context, arg ListProjectViewsParams) ([]ListProjectViewsRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	// Picker source for "attach an existing task as a subtask". Returns project
	// tasks eligible to become a child of the given parent. Excludes: the parent
	// itself, tasks already parented to this same parent, and tasks that already
	// have their own children (attaching one would break the one-level rule).
	// Tasks parented elsewhere ARE included (they can be re-parented) and flagged
	// via has_parent so the UI can warn.
	ListSubtaskCandidates(ctx context.Context, arg ListSubtaskCandidatesParams) ([]ListSubtaskCandidatesRow, error)
	// Child ids + state name of a task, used to cascade a cross-project move.
	ListSubtaskIDsForMove(ctx context.Context, parentID uuid.UUID) ([]ListSubtaskIDsForMoveRow, error)
	// Direct children of a task, in task-number order. Used on the parent's detail page.
	ListSubtasks(ctx context.Context, parentID uuid.UUID) ([]ListSubtasksRow, error)
	ListTaskActivity(ctx context.Context, taskID uuid.UUID) ([]ListTaskActivityRow, error)
	ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error)
	ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error)
	ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]ListTaskLabelsRow, error)
	// ==================== TASK PARTICIPANTS ====================
	// Everyone involved with a task: its creator, current assignees, and anyone who
	// has commented (non-deleted comments). Used to fan out notifications.
	ListTaskParticipants(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error)
	ListTaskTemplates(ctx context.Context, projectID uuid.UUID) ([]TaskTemplate, error)
	ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error)
	ListUnassignedProjectTasks(ctx context.Context, arg ListUnassignedProjectTasksParams) ([]ListUnassignedProjectTasksRow, error)
	ListUploadsByUser(ctx context.Context, arg ListUploadsByUserParams) ([]Upload, error)
	// ==================== USER ACTIVITY ====================
	ListUserActivity(ctx context.Context, arg ListUserActivityParams) ([]ListUserActivityRow, error)
	ListUserActivityDates(ctx context.Context, arg ListUserActivityDatesParams) ([]ListUserActivityDatesRow, error)
	ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error)
	ListUserProjectsFiltered(ctx context.Context, arg ListUserProjectsFilteredParams) ([]ListUserProjectsFilteredRow, error)
	ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]Workspace, error)
	ListUserWorkspacesFiltered(ctx context.Context, arg ListUserWorkspacesFilteredParams) ([]Workspace, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	// Move a task to a different project, assigning a new project-local task number
	// and state. Cycle/module links and labels are handled separately by the caller.
	MoveTask(ctx context.Context, arg MoveTaskParams) (MoveTaskRow, error)
	PagesCreatedPerDay(ctx context.Context, arg PagesCreatedPerDayParams) ([]PagesCreatedPerDayRow, error)
	ProjectKeyExists(ctx context.Context, projectKey string) (bool, error)
	ProjectViewSlugExists(ctx context.Context, arg ProjectViewSlugExistsParams) (bool, error)
	ProjectsPerWorkspace(ctx context.Context) ([]ProjectsPerWorkspaceRow, error)
	RemoveModuleMember(ctx context.Context, arg RemoveModuleMemberParams) error
	RemoveModuleTask(ctx context.Context, arg RemoveModuleTaskParams) error
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error
	RemoveTaskFromCycle(ctx context.Context, arg RemoveTaskFromCycleParams) error
	RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	// Pass a JSON array of {id, new_position} objects.
	ReorderProjectViews(ctx context.Context, arg ReorderProjectViewsParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Admin variant: matches across all projects.
	SearchAllCycles(ctx context.Context, arg SearchAllCyclesParams) ([]SearchAllCyclesRow, error)
	// Admin variant: matches across all projects.
	SearchAllProjects(ctx context.Context, arg SearchAllProjectsParams) ([]SearchAllProjectsRow, error)
	// Admin variant: matches across all projects.
	SearchAllTasks(ctx context.Context, arg SearchAllTasksParams) ([]SearchAllTasksRow, error)
	// ==================== GLOBAL SEARCH ====================
	// Matches cycles by title across projects the user is a member of.
	SearchUserCycles(ctx context.Context, arg SearchUserCyclesParams) ([]SearchUserCyclesRow, error)
	// Matches projects by key, name, or description across projects the user is a member of.
	SearchUserProjects(ctx context.Context, arg SearchUserProjectsParams) ([]SearchUserProjectsRow, error)
	// ==================== GLOBAL SEARCH ====================
	// Matches tasks by title, description, or composed task key ("KEY-123") across
	// projects the user is a member of.
	SearchUserTasks(ctx context.Context, arg SearchUserTasksParams) ([]SearchUserTasksRow, error)
	SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]SearchUsersPaginatedRow, error)
	SetProjectDisabled(ctx context.Context, arg SetProjectDisabledParams) (Project, error)
	// Sets (or clears) a task's parent. Used to attach/re-parent an existing task
	// as a subtask.
	SetTaskParent(ctx context.Context, arg SetTaskParentParams) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeleteCycle(ctx context.Context, id uuid.UUID) error
	SoftDeleteModule(ctx context.Context, id uuid.UUID) error
	// When a member leaves a project, their private views are soft-deleted.
	SoftDeleteOwnedPrivateViews(ctx context.Context, arg SoftDeleteOwnedPrivateViewsParams) error
	SoftDeletePage(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteProjectView(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) error
	SubtasksCreatedPerDay(ctx context.Context, arg SubtasksCreatedPerDayParams) ([]SubtasksCreatedPerDayRow, error)
	TasksByPriority(ctx context.Context) ([]TasksByPriorityRow, error)
	TasksByStateType(ctx context.Context) ([]TasksByStateTypeRow, error)
	TasksCreatedPerDay(ctx context.Context, arg TasksCreatedPerDayParams) ([]TasksCreatedPerDayRow, error)
	TopProjectsByTaskCount(ctx context.Context) ([]TopProjectsByTaskCountRow, error)
	// When a member leaves a project, keep their shared views alive by reassigning ownership.
	TransferOwnedSharedViews(ctx context.Context, arg TransferOwnedSharedViewsParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateCycle(ctx context.Context, arg UpdateCycleParams) (Cycle, error)
	// `status` is passed as plain text; when empty string, no change. Avoids narg
	// around the enum type under the string override.
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePersonalAccessTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdatePersonalAccessTokenScope(ctx context.Context, arg UpdatePersonalAccessTokenScopeParams) (UpdatePersonalAccessTokenScopeRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectLabel(ctx context.Context, arg UpdateProjectLabelParams) (ProjectLabel, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error
	UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (ProjectState, error)
	UpdateProjectView(ctx context.Context, arg UpdateProjectViewParams) (UpdateProjectViewRow, error)
	UpdateProjectWorkspace(ctx context.Context, arg UpdateProjectWorkspaceParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error)
	UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) (TaskTemplate, error)
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
	UserExistsByEmailOrUsername(ctx context.Context, arg UserExistsByEmailOrUsernameParams) (bool, error)
	VerifyActivityChain(ctx context.Context, taskID uuid.UUID) ([]ActivityLog, error)
	WorkspaceKeyExists(ctx context.Context, workspaceKey string) (bool, error)
}

var _ Querier = (*Queries)(nil)
