// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activityCreatedPerDay = `-- name: ActivityCreatedPerDay :many
SELECT d::date AS day, COUNT(al.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN activity_log al
    ON al.created_at::date = d::date
    AND al.activity_type NOT IN ('comment_created', 'comment_updated', 'comment_deleted')
GROUP BY d
ORDER BY d ASC
`

type ActivityCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ActivityCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

// All activity_log events except comment lifecycle events (state changes,
// assignee/label edits, task lifecycle, etc.).
func (q *Queries) ActivityCreatedPerDay(ctx context.Context, arg ActivityCreatedPerDayParams) ([]ActivityCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, activityCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityCreatedPerDayRow{}
	for rows.Next() {
		var i ActivityCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachmentsCreatedPerDay = `-- name: AttachmentsCreatedPerDay :many
SELECT d::date AS day, COUNT(a.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN attachments a
    ON a.created_at::date = d::date
GROUP BY d
ORDER BY d ASC
`

type AttachmentsCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type AttachmentsCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) AttachmentsCreatedPerDay(ctx context.Context, arg AttachmentsCreatedPerDayParams) ([]AttachmentsCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, attachmentsCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttachmentsCreatedPerDayRow{}
	for rows.Next() {
		var i AttachmentsCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachmentsTotalSize = `-- name: AttachmentsTotalSize :one
SELECT COALESCE(SUM(u.size_bytes), 0)::bigint AS total_bytes
FROM attachments a
JOIN uploads u ON u.id = a.upload_id
`

func (q *Queries) AttachmentsTotalSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, attachmentsTotalSize)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const commentsCreatedPerDay = `-- name: CommentsCreatedPerDay :many
SELECT d::date AS day, COUNT(c.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN comments c
    ON c.created_at::date = d::date
    AND c.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type CommentsCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type CommentsCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) CommentsCreatedPerDay(ctx context.Context, arg CommentsCreatedPerDayParams) ([]CommentsCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, commentsCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentsCreatedPerDayRow{}
	for rows.Next() {
		var i CommentsCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttachments = `-- name: CountAttachments :one
SELECT COUNT(*) FROM attachments
`

func (q *Queries) CountAttachments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages WHERE deleted_at IS NULL
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects WHERE deleted_at IS NULL
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubtasks = `-- name: CountSubtasks :one
SELECT COUNT(*) FROM tasks WHERE deleted_at IS NULL AND parent_task_id IS NOT NULL
`

func (q *Queries) CountSubtasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubtasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelTasks = `-- name: CountTopLevelTasks :one
SELECT COUNT(*) FROM tasks WHERE deleted_at IS NULL AND parent_task_id IS NULL
`

func (q *Queries) CountTopLevelTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTopLevelTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT COUNT(*) FROM workspaces WHERE deleted_at IS NULL
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cyclesCreatedPerDay = `-- name: CyclesCreatedPerDay :many
SELECT d::date AS day, COUNT(cy.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN cycles cy
    ON cy.created_at::date = d::date
    AND cy.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type CyclesCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type CyclesCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) CyclesCreatedPerDay(ctx context.Context, arg CyclesCreatedPerDayParams) ([]CyclesCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, cyclesCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CyclesCreatedPerDayRow{}
	for rows.Next() {
		var i CyclesCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockerLinksForGraph = `-- name: ListBlockerLinksForGraph :many
SELECT task_id, blocker_task_id
FROM task_blockers
WHERE task_id = ANY($1::uuid[])
  AND blocker_task_id = ANY($1::uuid[])
`

type ListBlockerLinksForGraphRow struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
}

// Blocker links where both tasks are already on the graph.
func (q *Queries) ListBlockerLinksForGraph(ctx context.Context, taskIds []uuid.UUID) ([]ListBlockerLinksForGraphRow, error) {
	rows, err := q.db.Query(ctx, listBlockerLinksForGraph, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockerLinksForGraphRow{}
	for rows.Next() {
		var i ListBlockerLinksForGraphRow
		if err := rows.Scan(&i.TaskID, &i.BlockerTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphProjectOptions = `-- name: ListGraphProjectOptions :many
SELECT p.project_key, p.name, w.workspace_key
FROM projects p
JOIN workspaces w ON p.workspace_id = w.id
WHERE p.deleted_at IS NULL AND w.deleted_at IS NULL
  AND ($1::uuid IS NULL OR EXISTS (
      SELECT 1 FROM project_members vm WHERE vm.project_id = p.id AND vm.user_id = $1::uuid))
ORDER BY p.project_key ASC
`

type ListGraphProjectOptionsRow struct {
	ProjectKey   string `json:"project_key"`
	Name         string `json:"name"`
	WorkspaceKey string `json:"workspace_key"`
}

func (q *Queries) ListGraphProjectOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphProjectOptionsRow, error) {
	rows, err := q.db.Query(ctx, listGraphProjectOptions, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphProjectOptionsRow{}
	for rows.Next() {
		var i ListGraphProjectOptionsRow
		if err := rows.Scan(&i.ProjectKey, &i.Name, &i.WorkspaceKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphUserOptions = `-- name: ListGraphUserOptions :many
SELECT u.username, u.email, u.first_name, u.last_name
FROM users u
WHERE $1::uuid IS NULL OR EXISTS (
    SELECT 1 FROM project_members um
    JOIN project_members vm ON vm.project_id = um.project_id
    JOIN projects p ON p.id = um.project_id AND p.deleted_at IS NULL
    WHERE um.user_id = u.id AND vm.user_id = $1::uuid)
ORDER BY u.first_name ASC, u.last_name ASC
`

type ListGraphUserOptionsRow struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) ListGraphUserOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphUserOptionsRow, error) {
	rows, err := q.db.Query(ctx, listGraphUserOptions, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphUserOptionsRow{}
	for rows.Next() {
		var i ListGraphUserOptionsRow
		if err := rows.Scan(
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphWorkspaceOptions = `-- name: ListGraphWorkspaceOptions :many
SELECT w.workspace_key, w.name
FROM workspaces w
WHERE w.deleted_at IS NULL
  AND ($1::uuid IS NULL OR EXISTS (
      SELECT 1 FROM projects p
      JOIN project_members vm ON vm.project_id = p.id
      WHERE p.workspace_id = w.id AND p.deleted_at IS NULL AND vm.user_id = $1::uuid))
ORDER BY w.name ASC
`

type ListGraphWorkspaceOptionsRow struct {
	WorkspaceKey string `json:"workspace_key"`
	Name         string `json:"name"`
}

func (q *Queries) ListGraphWorkspaceOptions(ctx context.Context, viewerID pgtype.UUID) ([]ListGraphWorkspaceOptionsRow, error) {
	rows, err := q.db.Query(ctx, listGraphWorkspaceOptions, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphWorkspaceOptionsRow{}
	for rows.Next() {
		var i ListGraphWorkspaceOptionsRow
		if err := rows.Scan(&i.WorkspaceKey, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignmentsForGraph = `-- name: ListTaskAssignmentsForGraph :many
SELECT t.id AS task_id, t.task_number, t.title,
       (t.parent_task_id IS NOT NULL)::boolean AS is_subtask, t.parent_task_id,
       p.project_key, p.name AS project_name,
       w.id AS workspace_id, w.workspace_key, w.name AS workspace_name,
       ps.name AS state_name, ps.state_type, ps.color AS state_color,
       u.id AS user_id, u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN workspaces w ON p.workspace_id = w.id
JOIN project_states ps ON t.state_id = ps.id
LEFT JOIN task_assignees ta ON ta.task_id = t.id
LEFT JOIN users u ON ta.user_id = u.id
WHERE t.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND w.deleted_at IS NULL
  AND ($1::text IS NULL OR w.workspace_key = $1::text)
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR p.project_key = ANY($2::text[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR ps.state_type::text = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR u.username = ANY($4::text[]))
  AND ($5::uuid IS NULL OR EXISTS (
      SELECT 1 FROM project_members vm WHERE vm.project_id = p.id AND vm.user_id = $5::uuid))
ORDER BY p.project_key ASC, t.task_number ASC
`

type ListTaskAssignmentsForGraphParams struct {
	WorkspaceKey pgtype.Text `json:"workspace_key"`
	ProjectKeys  []string    `json:"project_keys"`
	StateTypes   []string    `json:"state_types"`
	Usernames    []string    `json:"usernames"`
	ViewerID     pgtype.UUID `json:"viewer_id"`
}

type ListTaskAssignmentsForGraphRow struct {
	TaskID        uuid.UUID   `json:"task_id"`
	TaskNumber    int32       `json:"task_number"`
	Title         string      `json:"title"`
	IsSubtask     bool        `json:"is_subtask"`
	ParentTaskID  pgtype.UUID `json:"parent_task_id"`
	ProjectKey    string      `json:"project_key"`
	ProjectName   string      `json:"project_name"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	WorkspaceKey  string      `json:"workspace_key"`
	WorkspaceName string      `json:"workspace_name"`
	StateName     string      `json:"state_name"`
	StateType     string      `json:"state_type"`
	StateColor    pgtype.Text `json:"state_color"`
	UserID        pgtype.UUID `json:"user_id"`
	Username      pgtype.Text `json:"username"`
	Email         pgtype.Text `json:"email"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
}

// One row per (task, assignee); unassigned tasks come back once with NULL user columns.
func (q *Queries) ListTaskAssignmentsForGraph(ctx context.Context, arg ListTaskAssignmentsForGraphParams) ([]ListTaskAssignmentsForGraphRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignmentsForGraph,
		arg.WorkspaceKey,
		arg.ProjectKeys,
		arg.StateTypes,
		arg.Usernames,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssignmentsForGraphRow{}
	for rows.Next() {
		var i ListTaskAssignmentsForGraphRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskNumber,
			&i.Title,
			&i.IsSubtask,
			&i.ParentTaskID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.WorkspaceID,
			&i.WorkspaceKey,
			&i.WorkspaceName,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modulesCreatedPerDay = `-- name: ModulesCreatedPerDay :many
SELECT d::date AS day, COUNT(m.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN modules m
    ON m.created_at::date = d::date
    AND m.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type ModulesCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ModulesCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) ModulesCreatedPerDay(ctx context.Context, arg ModulesCreatedPerDayParams) ([]ModulesCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, modulesCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModulesCreatedPerDayRow{}
	for rows.Next() {
		var i ModulesCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pagesCreatedPerDay = `-- name: PagesCreatedPerDay :many
SELECT d::date AS day, COUNT(pg.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN pages pg
    ON pg.created_at::date = d::date
    AND pg.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type PagesCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type PagesCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) PagesCreatedPerDay(ctx context.Context, arg PagesCreatedPerDayParams) ([]PagesCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, pagesCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PagesCreatedPerDayRow{}
	for rows.Next() {
		var i PagesCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsPerWorkspace = `-- name: ProjectsPerWorkspace :many
SELECT w.id AS workspace_id, w.name, w.workspace_key, COUNT(p.id)::int AS project_count
FROM workspaces w
LEFT JOIN projects p ON p.workspace_id = w.id AND p.deleted_at IS NULL
WHERE w.deleted_at IS NULL
GROUP BY w.id, w.name, w.workspace_key
ORDER BY project_count DESC
`

type ProjectsPerWorkspaceRow struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Name         string    `json:"name"`
	WorkspaceKey string    `json:"workspace_key"`
	ProjectCount int32     `json:"project_count"`
}

func (q *Queries) ProjectsPerWorkspace(ctx context.Context) ([]ProjectsPerWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, projectsPerWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsPerWorkspaceRow{}
	for rows.Next() {
		var i ProjectsPerWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.WorkspaceKey,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtasksCreatedPerDay = `-- name: SubtasksCreatedPerDay :many
SELECT d::date AS day, COUNT(t.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN tasks t
    ON t.created_at::date = d::date
    AND t.deleted_at IS NULL
    AND t.parent_task_id IS NOT NULL
GROUP BY d
ORDER BY d ASC
`

type SubtasksCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type SubtasksCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) SubtasksCreatedPerDay(ctx context.Context, arg SubtasksCreatedPerDayParams) ([]SubtasksCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, subtasksCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubtasksCreatedPerDayRow{}
	for rows.Next() {
		var i SubtasksCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksByPriority = `-- name: TasksByPriority :many
SELECT pp.name AS priority, COUNT(*)::int AS count
FROM tasks t
JOIN project_priorities pp ON t.priority_id = pp.id
WHERE t.deleted_at IS NULL AND t.parent_task_id IS NULL
GROUP BY pp.name
ORDER BY MAX(pp.rank) DESC
`

type TasksByPriorityRow struct {
	Priority string `json:"priority"`
	Count    int32  `json:"count"`
}

// Instance-wide aggregate: priorities are per-project entities, so tasks are
// grouped by level name (most urgent first by each name's highest rank).
func (q *Queries) TasksByPriority(ctx context.Context) ([]TasksByPriorityRow, error) {
	rows, err := q.db.Query(ctx, tasksByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksByPriorityRow{}
	for rows.Next() {
		var i TasksByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksByStateType = `-- name: TasksByStateType :many
SELECT ps.state_type AS state_type, COUNT(t.id)::int AS count
FROM tasks t
JOIN project_states ps ON t.state_id = ps.id
WHERE t.deleted_at IS NULL AND t.parent_task_id IS NULL
GROUP BY ps.state_type
ORDER BY count DESC
`

type TasksByStateTypeRow struct {
	StateType string `json:"state_type"`
	Count     int32  `json:"count"`
}

func (q *Queries) TasksByStateType(ctx context.Context) ([]TasksByStateTypeRow, error) {
	rows, err := q.db.Query(ctx, tasksByStateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksByStateTypeRow{}
	for rows.Next() {
		var i TasksByStateTypeRow
		if err := rows.Scan(&i.StateType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksCreatedPerDay = `-- name: TasksCreatedPerDay :many
SELECT d::date AS day, COUNT(t.id)::int AS count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN tasks t
    ON t.created_at::date = d::date
    AND t.deleted_at IS NULL
    AND t.parent_task_id IS NULL
GROUP BY d
ORDER BY d ASC
`

type TasksCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type TasksCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) TasksCreatedPerDay(ctx context.Context, arg TasksCreatedPerDayParams) ([]TasksCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, tasksCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksCreatedPerDayRow{}
	for rows.Next() {
		var i TasksCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topProjectsByTaskCount = `-- name: TopProjectsByTaskCount :many
SELECT p.id AS project_id, p.name, p.project_key, COUNT(t.id)::int AS task_count
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id AND t.deleted_at IS NULL
WHERE p.deleted_at IS NULL
GROUP BY p.id, p.name, p.project_key
ORDER BY task_count DESC
LIMIT 10
`

type TopProjectsByTaskCountRow struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Name       string    `json:"name"`
	ProjectKey string    `json:"project_key"`
	TaskCount  int32     `json:"task_count"`
}

func (q *Queries) TopProjectsByTaskCount(ctx context.Context) ([]TopProjectsByTaskCountRow, error) {
	rows, err := q.db.Query(ctx, topProjectsByTaskCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopProjectsByTaskCountRow{}
	for rows.Next() {
		var i TopProjectsByTaskCountRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.ProjectKey,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewsCreatedPerDay = `-- name: ViewsCreatedPerDay :many
SELECT
    d::date AS day,
    (COUNT(v.id) FILTER (WHERE v.visibility = 'private'))::int AS private_count,
    (COUNT(v.id) FILTER (WHERE v.visibility = 'shared'))::int AS shared_count
FROM generate_series(
    $1::date,
    $2::date,
    INTERVAL '1 day'
) d
LEFT JOIN project_views v
    ON v.created_at::date = d::date
    AND v.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type ViewsCreatedPerDayParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ViewsCreatedPerDayRow struct {
	Day          pgtype.Date `json:"day"`
	PrivateCount int32       `json:"private_count"`
	SharedCount  int32       `json:"shared_count"`
}

func (q *Queries) ViewsCreatedPerDay(ctx context.Context, arg ViewsCreatedPerDayParams) ([]ViewsCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, viewsCreatedPerDay, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewsCreatedPerDayRow{}
	for rows.Next() {
		var i ViewsCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.PrivateCount, &i.SharedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
