// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages WHERE deleted_at IS NULL
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects WHERE deleted_at IS NULL
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubtasks = `-- name: CountSubtasks :one
SELECT COUNT(*) FROM tasks WHERE deleted_at IS NULL AND parent_task_id IS NOT NULL
`

func (q *Queries) CountSubtasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubtasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelTasks = `-- name: CountTopLevelTasks :one
SELECT COUNT(*) FROM tasks WHERE deleted_at IS NULL AND parent_task_id IS NULL
`

func (q *Queries) CountTopLevelTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTopLevelTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT COUNT(*) FROM workspaces WHERE deleted_at IS NULL
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pagesCreatedPerDay = `-- name: PagesCreatedPerDay :many
SELECT d::date AS day, COUNT(pg.id)::int AS count
FROM generate_series(
    CURRENT_DATE - (($1::int - 1) * INTERVAL '1 day'),
    CURRENT_DATE,
    INTERVAL '1 day'
) d
LEFT JOIN pages pg
    ON pg.created_at::date = d::date
    AND pg.deleted_at IS NULL
GROUP BY d
ORDER BY d ASC
`

type PagesCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) PagesCreatedPerDay(ctx context.Context, days int32) ([]PagesCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, pagesCreatedPerDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PagesCreatedPerDayRow{}
	for rows.Next() {
		var i PagesCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsPerWorkspace = `-- name: ProjectsPerWorkspace :many
SELECT w.id AS workspace_id, w.name, w.workspace_key, COUNT(p.id)::int AS project_count
FROM workspaces w
LEFT JOIN projects p ON p.workspace_id = w.id AND p.deleted_at IS NULL
WHERE w.deleted_at IS NULL
GROUP BY w.id, w.name, w.workspace_key
ORDER BY project_count DESC
`

type ProjectsPerWorkspaceRow struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Name         string    `json:"name"`
	WorkspaceKey string    `json:"workspace_key"`
	ProjectCount int32     `json:"project_count"`
}

func (q *Queries) ProjectsPerWorkspace(ctx context.Context) ([]ProjectsPerWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, projectsPerWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsPerWorkspaceRow{}
	for rows.Next() {
		var i ProjectsPerWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.WorkspaceKey,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtasksCreatedPerDay = `-- name: SubtasksCreatedPerDay :many
SELECT d::date AS day, COUNT(t.id)::int AS count
FROM generate_series(
    CURRENT_DATE - (($1::int - 1) * INTERVAL '1 day'),
    CURRENT_DATE,
    INTERVAL '1 day'
) d
LEFT JOIN tasks t
    ON t.created_at::date = d::date
    AND t.deleted_at IS NULL
    AND t.parent_task_id IS NOT NULL
GROUP BY d
ORDER BY d ASC
`

type SubtasksCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) SubtasksCreatedPerDay(ctx context.Context, days int32) ([]SubtasksCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, subtasksCreatedPerDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubtasksCreatedPerDayRow{}
	for rows.Next() {
		var i SubtasksCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksByPriority = `-- name: TasksByPriority :many
SELECT t.priority AS priority, COUNT(*)::int AS count
FROM tasks t
WHERE t.deleted_at IS NULL AND t.parent_task_id IS NULL
GROUP BY t.priority
ORDER BY t.priority ASC
`

type TasksByPriorityRow struct {
	Priority int32 `json:"priority"`
	Count    int32 `json:"count"`
}

func (q *Queries) TasksByPriority(ctx context.Context) ([]TasksByPriorityRow, error) {
	rows, err := q.db.Query(ctx, tasksByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksByPriorityRow{}
	for rows.Next() {
		var i TasksByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksByStateType = `-- name: TasksByStateType :many
SELECT ps.state_type AS state_type, COUNT(t.id)::int AS count
FROM tasks t
JOIN project_states ps ON t.state_id = ps.id
WHERE t.deleted_at IS NULL AND t.parent_task_id IS NULL
GROUP BY ps.state_type
ORDER BY count DESC
`

type TasksByStateTypeRow struct {
	StateType string `json:"state_type"`
	Count     int32  `json:"count"`
}

func (q *Queries) TasksByStateType(ctx context.Context) ([]TasksByStateTypeRow, error) {
	rows, err := q.db.Query(ctx, tasksByStateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksByStateTypeRow{}
	for rows.Next() {
		var i TasksByStateTypeRow
		if err := rows.Scan(&i.StateType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksCreatedPerDay = `-- name: TasksCreatedPerDay :many
SELECT d::date AS day, COUNT(t.id)::int AS count
FROM generate_series(
    CURRENT_DATE - (($1::int - 1) * INTERVAL '1 day'),
    CURRENT_DATE,
    INTERVAL '1 day'
) d
LEFT JOIN tasks t
    ON t.created_at::date = d::date
    AND t.deleted_at IS NULL
    AND t.parent_task_id IS NULL
GROUP BY d
ORDER BY d ASC
`

type TasksCreatedPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) TasksCreatedPerDay(ctx context.Context, days int32) ([]TasksCreatedPerDayRow, error) {
	rows, err := q.db.Query(ctx, tasksCreatedPerDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksCreatedPerDayRow{}
	for rows.Next() {
		var i TasksCreatedPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topProjectsByTaskCount = `-- name: TopProjectsByTaskCount :many
SELECT p.id AS project_id, p.name, p.project_key, COUNT(t.id)::int AS task_count
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id AND t.deleted_at IS NULL
WHERE p.deleted_at IS NULL
GROUP BY p.id, p.name, p.project_key
ORDER BY task_count DESC
LIMIT 10
`

type TopProjectsByTaskCountRow struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Name       string    `json:"name"`
	ProjectKey string    `json:"project_key"`
	TaskCount  int32     `json:"task_count"`
}

func (q *Queries) TopProjectsByTaskCount(ctx context.Context) ([]TopProjectsByTaskCountRow, error) {
	rows, err := q.db.Query(ctx, topProjectsByTaskCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopProjectsByTaskCountRow{}
	for rows.Next() {
		var i TopProjectsByTaskCountRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.ProjectKey,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
