// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearProjectDefaultView = `-- name: ClearProjectDefaultView :exec
UPDATE project_views
SET is_default = FALSE, updated_at = NOW()
WHERE project_id = $1 AND is_default AND deleted_at IS NULL
`

func (q *Queries) ClearProjectDefaultView(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearProjectDefaultView, projectID)
	return err
}

const createProjectView = `-- name: CreateProjectView :one

INSERT INTO project_views (
    project_id, slug, name, description, visibility, owner_id,
    filter_tree, group_by, sort_by, sort_dir, default_tab, position
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, slug, name, description, visibility, owner_id,
          filter_tree, group_by, sort_by, sort_dir, default_tab, position,
          is_default, created_at, updated_at, deleted_at
`

type CreateProjectViewParams struct {
	ProjectID   uuid.UUID      `json:"project_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Visibility  ViewVisibility `json:"visibility"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	FilterTree  []byte         `json:"filter_tree"`
	GroupBy     string         `json:"group_by"`
	SortBy      string         `json:"sort_by"`
	SortDir     string         `json:"sort_dir"`
	DefaultTab  string         `json:"default_tab"`
	Position    int32          `json:"position"`
}

type CreateProjectViewRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	DefaultTab  string             `json:"default_tab"`
	Position    int32              `json:"position"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// ==================== PROJECT VIEWS ====================
func (q *Queries) CreateProjectView(ctx context.Context, arg CreateProjectViewParams) (CreateProjectViewRow, error) {
	row := q.db.QueryRow(ctx, createProjectView,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.OwnerID,
		arg.FilterTree,
		arg.GroupBy,
		arg.SortBy,
		arg.SortDir,
		arg.DefaultTab,
		arg.Position,
	)
	var i CreateProjectViewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.OwnerID,
		&i.FilterTree,
		&i.GroupBy,
		&i.SortBy,
		&i.SortDir,
		&i.DefaultTab,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectViewByID = `-- name: GetProjectViewByID :one
SELECT id, project_id, slug, name, description, visibility, owner_id,
       filter_tree, group_by, sort_by, sort_dir, default_tab, position,
       is_default, created_at, updated_at, deleted_at
FROM project_views
WHERE id = $1 AND deleted_at IS NULL
`

type GetProjectViewByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	DefaultTab  string             `json:"default_tab"`
	Position    int32              `json:"position"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectViewByID(ctx context.Context, id uuid.UUID) (GetProjectViewByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectViewByID, id)
	var i GetProjectViewByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.OwnerID,
		&i.FilterTree,
		&i.GroupBy,
		&i.SortBy,
		&i.SortDir,
		&i.DefaultTab,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectViewBySlug = `-- name: GetProjectViewBySlug :one
SELECT id, project_id, slug, name, description, visibility, owner_id,
       filter_tree, group_by, sort_by, sort_dir, default_tab, position,
       is_default, created_at, updated_at, deleted_at
FROM project_views
WHERE project_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetProjectViewBySlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

type GetProjectViewBySlugRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	DefaultTab  string             `json:"default_tab"`
	Position    int32              `json:"position"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetProjectViewBySlug(ctx context.Context, arg GetProjectViewBySlugParams) (GetProjectViewBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectViewBySlug, arg.ProjectID, arg.Slug)
	var i GetProjectViewBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.OwnerID,
		&i.FilterTree,
		&i.GroupBy,
		&i.SortBy,
		&i.SortDir,
		&i.DefaultTab,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectViews = `-- name: ListProjectViews :many
SELECT id, project_id, slug, name, description, visibility, owner_id,
       filter_tree, group_by, sort_by, sort_dir, default_tab, position,
       is_default, created_at, updated_at, deleted_at
FROM project_views
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (visibility = 'shared' OR owner_id = $2)
ORDER BY position ASC, created_at ASC
`

type ListProjectViewsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

type ListProjectViewsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	DefaultTab  string             `json:"default_tab"`
	Position    int32              `json:"position"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// Returns every shared view in the project plus private views owned by the caller.
func (q *Queries) ListProjectViews(ctx context.Context, arg ListProjectViewsParams) ([]ListProjectViewsRow, error) {
	rows, err := q.db.Query(ctx, listProjectViews, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectViewsRow{}
	for rows.Next() {
		var i ListProjectViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.OwnerID,
			&i.FilterTree,
			&i.GroupBy,
			&i.SortBy,
			&i.SortDir,
			&i.DefaultTab,
			&i.Position,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectViewSlugExists = `-- name: ProjectViewSlugExists :one
SELECT EXISTS (
    SELECT 1 FROM project_views
    WHERE project_id = $1 AND slug = $2 AND deleted_at IS NULL
) AS exists
`

type ProjectViewSlugExistsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) ProjectViewSlugExists(ctx context.Context, arg ProjectViewSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectViewSlugExists, arg.ProjectID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reorderProjectViews = `-- name: ReorderProjectViews :exec
UPDATE project_views pv
SET position = u.new_position, updated_at = NOW()
FROM jsonb_to_recordset($2::jsonb) AS u(id uuid, new_position int)
WHERE pv.id = u.id AND pv.project_id = $1 AND pv.deleted_at IS NULL
`

type ReorderProjectViewsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Items     []byte    `json:"items"`
}

// Pass a JSON array of {id, new_position} objects.
func (q *Queries) ReorderProjectViews(ctx context.Context, arg ReorderProjectViewsParams) error {
	_, err := q.db.Exec(ctx, reorderProjectViews, arg.ProjectID, arg.Items)
	return err
}

const setProjectDefaultView = `-- name: SetProjectDefaultView :exec
UPDATE project_views
SET is_default = (id = $2::uuid), updated_at = NOW()
WHERE project_id = $1 AND deleted_at IS NULL
  AND is_default IS DISTINCT FROM (id = $2::uuid)
`

type SetProjectDefaultViewParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ViewID    uuid.UUID `json:"view_id"`
}

// Points the project's single default at one view: sets the flag there and
// clears it everywhere else in one statement.
func (q *Queries) SetProjectDefaultView(ctx context.Context, arg SetProjectDefaultViewParams) error {
	_, err := q.db.Exec(ctx, setProjectDefaultView, arg.ProjectID, arg.ViewID)
	return err
}

const softDeleteOwnedPrivateViews = `-- name: SoftDeleteOwnedPrivateViews :exec
UPDATE project_views
SET deleted_at = NOW(), updated_at = NOW()
WHERE project_id = $1 AND owner_id = $2 AND visibility = 'private' AND deleted_at IS NULL
`

type SoftDeleteOwnedPrivateViewsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

// When a member leaves a project, their private views are soft-deleted.
func (q *Queries) SoftDeleteOwnedPrivateViews(ctx context.Context, arg SoftDeleteOwnedPrivateViewsParams) error {
	_, err := q.db.Exec(ctx, softDeleteOwnedPrivateViews, arg.ProjectID, arg.OwnerID)
	return err
}

const softDeleteProjectView = `-- name: SoftDeleteProjectView :exec
UPDATE project_views
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProjectView(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProjectView, id)
	return err
}

const transferOwnedSharedViews = `-- name: TransferOwnedSharedViews :exec
UPDATE project_views
SET owner_id = $3, updated_at = NOW()
WHERE project_id = $1 AND owner_id = $2 AND visibility = 'shared' AND deleted_at IS NULL
`

type TransferOwnedSharedViewsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	OwnerID_2 uuid.UUID `json:"owner_id_2"`
}

// When a member leaves a project, keep their shared views alive by reassigning ownership.
func (q *Queries) TransferOwnedSharedViews(ctx context.Context, arg TransferOwnedSharedViewsParams) error {
	_, err := q.db.Exec(ctx, transferOwnedSharedViews, arg.ProjectID, arg.OwnerID, arg.OwnerID_2)
	return err
}

const updateProjectView = `-- name: UpdateProjectView :one
UPDATE project_views
SET name        = COALESCE($2, name),
    description = COALESCE($3, description),
    visibility  = COALESCE($4, visibility),
    filter_tree = COALESCE($5, filter_tree),
    group_by    = COALESCE($6, group_by),
    sort_by     = COALESCE($7, sort_by),
    sort_dir    = COALESCE($8, sort_dir),
    default_tab = COALESCE($9, default_tab),
    position    = COALESCE($10, position),
    updated_at  = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, slug, name, description, visibility, owner_id,
          filter_tree, group_by, sort_by, sort_dir, default_tab, position,
          is_default, created_at, updated_at, deleted_at
`

type UpdateProjectViewParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  NullViewVisibility `json:"visibility"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     pgtype.Text        `json:"group_by"`
	SortBy      pgtype.Text        `json:"sort_by"`
	SortDir     pgtype.Text        `json:"sort_dir"`
	DefaultTab  pgtype.Text        `json:"default_tab"`
	Position    pgtype.Int4        `json:"position"`
}

type UpdateProjectViewRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Visibility  ViewVisibility     `json:"visibility"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	FilterTree  []byte             `json:"filter_tree"`
	GroupBy     string             `json:"group_by"`
	SortBy      string             `json:"sort_by"`
	SortDir     string             `json:"sort_dir"`
	DefaultTab  string             `json:"default_tab"`
	Position    int32              `json:"position"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateProjectView(ctx context.Context, arg UpdateProjectViewParams) (UpdateProjectViewRow, error) {
	row := q.db.QueryRow(ctx, updateProjectView,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.FilterTree,
		arg.GroupBy,
		arg.SortBy,
		arg.SortDir,
		arg.DefaultTab,
		arg.Position,
	)
	var i UpdateProjectViewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.OwnerID,
		&i.FilterTree,
		&i.GroupBy,
		&i.SortBy,
		&i.SortDir,
		&i.DefaultTab,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
