// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one

INSERT INTO workspace_members (workspace_id, user_id)
VALUES ($1, $2)
RETURNING id, workspace_id, user_id, joined_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// ==================== WORKSPACE MEMBERS ====================
func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const countAllWorkspaces = `-- name: CountAllWorkspaces :one
SELECT COUNT(*)
FROM workspaces w
WHERE w.deleted_at IS NULL
`

func (q *Queries) CountAllWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllWorkspacesFiltered = `-- name: CountAllWorkspacesFiltered :one
SELECT COUNT(*)
FROM workspaces w
WHERE w.deleted_at IS NULL
  AND ($1::text IS NULL OR w.name ILIKE '%' || $1 || '%' OR w.workspace_key ILIKE '%' || $1 || '%' OR w.description ILIKE '%' || $1 || '%')
`

func (q *Queries) CountAllWorkspacesFiltered(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAllWorkspacesFiltered, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserWorkspaces = `-- name: CountUserWorkspaces :one
SELECT COUNT(*)
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
`

func (q *Queries) CountUserWorkspaces(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWorkspaces, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserWorkspacesFiltered = `-- name: CountUserWorkspacesFiltered :one
SELECT COUNT(*)
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
  AND ($2::text IS NULL OR w.name ILIKE '%' || $2 || '%' OR w.workspace_key ILIKE '%' || $2 || '%' OR w.description ILIKE '%' || $2 || '%')
`

type CountUserWorkspacesFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountUserWorkspacesFiltered(ctx context.Context, arg CountUserWorkspacesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWorkspacesFiltered, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one

INSERT INTO workspaces (workspace_key, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_key, name, description, created_by, created_at, updated_at, deleted_at
`

type CreateWorkspaceParams struct {
	WorkspaceKey string      `json:"workspace_key"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	CreatedBy    uuid.UUID   `json:"created_by"`
}

// ==================== WORKSPACES ====================
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.WorkspaceKey,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceKey,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, workspace_key, name, description, created_by, created_at, updated_at, deleted_at
FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceKey,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceByKey = `-- name: GetWorkspaceByKey :one
SELECT id, workspace_key, name, description, created_by, created_at, updated_at, deleted_at
FROM workspaces
WHERE workspace_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByKey(ctx context.Context, workspaceKey string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByKey, workspaceKey)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceKey,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT wm.id, wm.workspace_id, wm.user_id, wm.joined_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1 AND wm.user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type GetWorkspaceMemberRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.JoinedAt,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
	)
	return i, err
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = $1 AND user_id = $2
) AS is_member
`

type IsWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listAllWorkspaces = `-- name: ListAllWorkspaces :many
SELECT w.id, w.workspace_key, w.name, w.description, w.created_by, w.created_at, w.updated_at, w.deleted_at
FROM workspaces w
WHERE w.deleted_at IS NULL
ORDER BY w.name ASC
LIMIT $1 OFFSET $2
`

type ListAllWorkspacesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllWorkspaces(ctx context.Context, arg ListAllWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listAllWorkspaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceKey,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkspacesFiltered = `-- name: ListAllWorkspacesFiltered :many
SELECT w.id, w.workspace_key, w.name, w.description, w.created_by, w.created_at, w.updated_at, w.deleted_at
FROM workspaces w
WHERE w.deleted_at IS NULL
  AND ($3::text IS NULL OR w.name ILIKE '%' || $3 || '%' OR w.workspace_key ILIKE '%' || $3 || '%' OR w.description ILIKE '%' || $3 || '%')
ORDER BY w.name ASC
LIMIT $1 OFFSET $2
`

type ListAllWorkspacesFilteredParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListAllWorkspacesFiltered(ctx context.Context, arg ListAllWorkspacesFilteredParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listAllWorkspacesFiltered, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceKey,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.id, w.workspace_key, w.name, w.description, w.created_by, w.created_at, w.updated_at, w.deleted_at
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.name ASC
LIMIT $2 OFFSET $3
`

type ListUserWorkspacesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaces, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceKey,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkspacesFiltered = `-- name: ListUserWorkspacesFiltered :many
SELECT w.id, w.workspace_key, w.name, w.description, w.created_by, w.created_at, w.updated_at, w.deleted_at
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
  AND ($4::text IS NULL OR w.name ILIKE '%' || $4 || '%' OR w.workspace_key ILIKE '%' || $4 || '%' OR w.description ILIKE '%' || $4 || '%')
ORDER BY w.name ASC
LIMIT $2 OFFSET $3
`

type ListUserWorkspacesFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListUserWorkspacesFiltered(ctx context.Context, arg ListUserWorkspacesFilteredParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listUserWorkspacesFiltered,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceKey,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.joined_at,
       u.username, u.email, u.first_name, u.last_name, u.avatar_url
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1
ORDER BY wm.joined_at ASC
`

type ListWorkspaceMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_key, name, description, created_by, created_at, updated_at, deleted_at
`

type UpdateWorkspaceParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.Description)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceKey,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const workspaceKeyExists = `-- name: WorkspaceKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM workspaces
    WHERE workspace_key = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) WorkspaceKeyExists(ctx context.Context, workspaceKey string) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceKeyExists, workspaceKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
